-- +goose Up
-- Seed item templates from price lists
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x4x92 5/8"', 'ea', 3.27);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x4x104 5/8"', 'ea', 4.27);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x4x116"', 'ea', 4.62);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x4x8', 'ea', 4.18);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x4x10', 'ea', 5.24);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x4x12', 'ea', 6.28);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x4x14', 'ea', 6.28);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x4x16', 'ea', 8.37);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x4x20', 'ea', 12.09);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x6x92 5/8"', 'ea', 4.86);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x6x104 5/8"', 'ea', 6.4);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x6x116"', 'ea', 7.23);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x6x8', 'ea', 6.28);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x6x10', 'ea', 7.85);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x6x12', 'ea', 9.42);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x6x14', 'ea', 10.98);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x6x16', 'ea', 12.55);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x6x20', 'ea', 18.15);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x6x16 PT', 'ea', 12.96);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x6x12 T&G Pine', 'ea', 18.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x6x16 T&G Pine', 'ea', 24.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x8x8', 'ea', 11.44);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x8x10', 'ea', 14.3);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x8x12', 'ea', 17.16);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x8x14', 'ea', 20.02);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x8x16', 'ea', 22.89);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x8x20', 'ea', 31.87);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x8x16 PT', 'ea', 17.6);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x10x8', 'ea', 14.3);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x10x10', 'ea', 17.88);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x10x12', 'ea', 21.45);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x10x14', 'ea', 25.02);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x10x16', 'ea', 28.61);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x10x20', 'ea', 39.84);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x10x16 PT', 'ea', 23.68);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x12x8', 'ea', 17.45);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x12x10', 'ea', 21.82);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x12x12', 'ea', 26.18);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x12x14', 'ea', 30.54);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x12x16', 'ea', 38.84);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x12x20', 'ea', 60.8);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x12x16 PT', 'ea', 36.64);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '1 3/4"x11 7/8" LVL', 'ea', 6.72);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '1 3/4"x14" LVL', 'ea', 7.58);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '1 3/4"x16" LVL', 'ea', 10.18);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '4x4x8 DF', 'ea', 29.35);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '4x4x10 DF', 'ea', 36.69);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '4x4x12 DF', 'ea', 44.04);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '4x4x14 DF', 'ea', 51.38);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '4x4x16 DF', 'ea', 58.72);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '4x4x18 DF', 'ea', 66.06);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '4x4x20 DF', 'ea', 73.4);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '4x4x8 PT', 'ea', 20.48);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '4x4x10 PT', 'ea', 25.6);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '4x4x12 PT', 'ea', 30.72);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '4x4x14 PT', 'ea', 35.84);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '4x4x16 PT', 'ea', 40.96);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '4x4x18 PT', 'ea', 46.08);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '4x4x20 PT', 'ea', 51.2);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6x6x8 DF', 'ea', 113.67);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6x6x10 DF', 'ea', 136.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6x6x12 DF', 'ea', 150.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6x6x14 DF', 'ea', 164.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6x6x16 DF', 'ea', 178.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6x6x18 DF', 'ea', 192.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6x6x20 DF', 'ea', 206.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6x6x8 PT', 'ea', 16.08);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6x6x10 PT', 'ea', 20.1);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6x6x12 PT', 'ea', 28.14);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6x6x14 PT', 'ea', 28.14);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6x6x16 PT', 'ea', 32.16);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6x6x18 PT', 'ea', 36.18);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6x6x20 PT', 'ea', 40.2);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', 'GL 3 1/2"x9"', 'ea', 11.33);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', 'GL 3 1/2"x11-7/8"', 'ea', 12.97);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', 'GL 3 1/2"x15"', 'ea', 17.26);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', 'GL 3 1/2"x18"', 'ea', 20.83);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', 'GL 5 1/2x7-1/2"', 'ea', 13.34);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', 'GL 5 1/2x9"', 'ea', 15.14);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', 'GL 5 1/2x11-7/8"', 'ea', 17.64);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', 'GL 5 1/2x15"', 'ea', 23.49);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', 'GL 5 1/2x18"', 'ea', 29.43);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', 'BCI 11 7/8 5000 1''', 'lnft', 17.65);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '11 7/8 Rim Joist 1''', 'lnft', 20.79);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '3/8 CDX', 'ea', 2.84);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '1/2 CDX', 'ea', 2.5);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '5/8 CDX', 'ea', 1.97);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '3/4" Advantech T&G', 'ea', 44.5);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x6 Hangers', 'ea', 2.2);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x8 Hangers', 'ea', 2.6);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x10 Hangers', 'ea', 2.97);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '2x12 Hangers', 'ea', 3.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '9 1/2 BCI Hangers', 'ea', 5.9);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '11 7/8 BCI Hangers', 'ea', 6.9);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6" Truss Screw 50/Box', 'ea', 39.55);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '1/2"x5" Titan anchor bolt', 'ea', 5.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', 'Plate Washers 5/8 50/box', 'ea', 70.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '4x4 Knife Post Base', 'ea', 40.1);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '6x6 Knife Post Base', 'ea', 55.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '8x8 Knife Post Base', 'ea', 91.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', 'SUBFLOOR Glue 28OZ', 'ea', 7.14);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '9''x150'' House Wrap', 'ea', 80.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '9''x100'' Tyvek', 'ea', 124.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', 'Ice and Water Sheild 3''x67''', 'ea', 26.6);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', 'Tigerpaw Underlayment Felt 1000sqft', 'sqft', 155.8);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', 'Window Tape 4"x75'' Frogtape', 'ea', 33.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '5 1/2"x50'' Sill Seal', 'ea', 8.05);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Lumber', '80lb Concrete Sackrete', 'ea', 7.5);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'R13 Fiberglass Batts 2x4 16" O/C 1 Sqft', 'sqft', 0.47);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'R13 Fiberglass Batts 2x4 24" O/C 1 Sqft', 'sqft', 0.47);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'R21 Fiberglass Batts 2x6 16" O/C 1 Sqft', 'sqft', 0.68);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'R21 Fiberglass Batts 2x6 24" O/C 1 Sqft', 'sqft', 0.68);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'R30 10" Fiberglass Batts 16" O/C 1 Sqft', 'sqft', 0.96);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'R30 10" Fiberglass Batts 24" O/C 1 Sqft', 'sqft', 0.96);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'R38  12" Fiberglass Batts 16" O/C 1 Sqft', 'sqft', 1.12);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'R38 12" Fiberglass Batts 24" O/C 1 Sqft', 'sqft', 1.12);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x12'' Full Treat', 'ea', 70.26);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x14'' Full Treat', 'ea', 90.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x16'' Full Treat', 'ea', 110.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x18'' Full Treat', 'ea', 130.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x20'' Full Treat', 'ea', 150.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x22'' Full Treat', 'ea', 170.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x24'' Full Treat', 'ea', 190.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x26'' Full Treat', 'ea', 210.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x28'' Full Treat', 'ea', 230.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x30'' Full Treat', 'ea', 250.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x32'' Full Treat', 'ea', 270.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x34'' Full Treat', 'ea', 290.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x12'' Treated Bottom', 'ea', 70.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x14'' Treated Bottom', 'ea', 81.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x16'' Treated Bottom', 'ea', 93.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x18'' Treated Bottom', 'ea', 105.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x20'' Treated Bottom', 'ea', 117.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x22'' Treated Bottom', 'ea', 128.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x24'' Treated Bottom', 'ea', 140.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x26'' Treated Bottom', 'ea', 153.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x28'' Treated Bottom', 'ea', 165.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x30'' Treated Bottom', 'ea', 177.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x32'' Treated Bottom', 'ea', 189.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x6x34'' Treated Bottom', 'ea', 202.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x6x12'' Treated Bottom', 'ea', 93.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x6x14'' Treated Bottom', 'ea', 103.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x6x16'' Treated Bottom', 'ea', 118.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x6x18'' Treated Bottom', 'ea', 133.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x6x20'' Treated Bottom', 'ea', 148.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x6x22'' Treated Bottom', 'ea', 163.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x6x24'' Treated Bottom', 'ea', 177.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x6x26'' Treated Bottom', 'ea', 192.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x6x28'' Treated Bottom', 'ea', 210.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x6x30'' Treated Bottom', 'ea', 225.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x6x32'' Treated Bottom', 'ea', 240.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x6x34'' Treated Bottom', 'ea', 255.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x8x12'' Treated Bottom', 'ea', 87.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x8x14'' Treated Bottom', 'ea', 102.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x8x16'' Treated Bottom', 'ea', 116.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x8x18'' Treated Bottom', 'ea', 131.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x8x20'' Treated Bottom', 'ea', 145.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x8x22'' Treated Bottom', 'ea', 160.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x8x24'' Treated Bottom', 'ea', 188.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x8x26'' Treated Bottom', 'ea', 204.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x8x28'' Treated Bottom', 'ea', 220.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x8x30'' Treated Bottom', 'ea', 235.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x8x32'' Treated Bottom', 'ea', 351.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '3 Ply 2x8x34'' Treated Bottom', 'ea', 367.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x8x12'' Treated Bottom', 'ea', 100.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x8x14'' Treated Bottom', 'ea', 130.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x8x16'' Treated Bottom', 'ea', 148.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x8x18'' Treated Bottom', 'ea', 166.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x8x20'' Treated Bottom', 'ea', 185.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x8x22'' Treated Bottom', 'ea', 204.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x8x24'' Treated Bottom', 'ea', 222.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x8x26'' Treated Bottom', 'ea', 246.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x8x28'' Treated Bottom', 'ea', 265.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x8x30'' Treated Bottom', 'ea', 283.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x8x32'' Treated Bottom', 'ea', 302.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4 Ply 2x8x34'' Treated Bottom', 'ea', 321.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '24 ga Roof Standing Seam with trim (Elite Metal Supplies)', 'ea', 7.2);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '26 ga Roof Standing Seam with trim (Elite Metal Supplies)', 'ea', 5.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '26ga Steel Siding with trim sqft (Elite Metal Supplies)', 'sqft', 5.8);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Standing Seam sqft (Elite Metal Supplies)', 'sqft', 2.6);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '10" Steel Board & Batt per sqft', 'sqft', 3.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Pacific Rib per sqft', 'sqft', 1.2);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Post Rib per sqft', 'sqft', 1.13);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad vented soffit 11 5/8"', 'ea', 3.33);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Gable Trim 10''', 'ea', 26.92);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Drip Edge 10''', 'ea', 14.54);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad 5 1/2 Fascia 10''', 'ea', 15.62);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Eave Trim 10''', 'ea', 15.64);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad End wall 10''', 'ea', 24.13);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Drip Flash 10''', 'ea', 9.12);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Ridge Cap 10''', 'ea', 26.17);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad W Valley 10''', 'ea', 36.19);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Hip Cap 10''', 'ea', 27.35);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Mini Angle 10''', 'ea', 6.61);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Outside Corner 10''', 'ea', 21.8);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Inside Corner 10''', 'ea', 28.12);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad J Channel 10''', 'ea', 8.9);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad  F J Combo 10''', 'ea', 19.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad 2" Face J Channel 10''', 'ea', 13.6);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad 2" Face F J Combo 10''', 'ea', 23.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad F Channel 10''', 'ea', 13.4);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Highside Trim 10''', 'ea', 25.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Sidewall 10''', 'ea', 24.13);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Double Angle 10''', 'ea', 9.76);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Base Guard 10''', 'ea', 9.51);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad 2" Face Overhead Door 10"', 'ea', 36.2);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad Track Cover 10''', 'ea', 27.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad #10 1" Screws 250', 'ea', 17.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad #10 1.5" Screws 250', 'ea', 19.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad #10 2" Screws 250', 'ea', 30.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad #14 1" Screws 250', 'ea', 28.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad #14 1.5" Screws 250', 'ea', 30.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Triad #14 2" Screws 250', 'ea', 32.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Em seal 20''', 'ea', 22.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'flex vent 20''', 'ea', 36.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Butyl Tape 3/4"x3/32"x50''', 'ea', 8.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Profile vent 3"x25''', 'ea', 30.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '1.625"X65'' PRO-TAC JOIST TAPE', 'ea', 23.5);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '12" Sonotube per foot', 'lnft', 5.05);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '12X12X8 PIER W/ 4X4 BRACKET', 'ea', 17.67);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '7/16"X20'' #4 LITE BAR', 'ea', 6.74);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '1/2"x20'' Steel Rebar', 'ea', 7.86);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Gravel per Yd', 'yd', 22.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'GAF Shingles sqft', 'sqft', 1.12);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'GAF Starter 120''', 'ea', 75.84);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'GAF Ridge Cap 20''', 'ea', 73.4);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Quarrix Ridge Vent 20''', 'ea', 48.52);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', 'Steel Drip Edge 10''', 'ea', 8.6);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('material', 'Insulation', '4"X4"X14" STEP FLASHING BLACK', 'ea', 2.17);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Rentals', 'Skytrack Day', 'day', 400.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Rentals', 'Skytrack Week', 'wk', 750.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Rentals', 'Skytrack Month', 'mo', 2500.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Rentals', 'Skid Steer Day', 'day', 200.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Rentals', 'Skid Steer Week', 'wk', 1000.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Rentals', 'Skid Steer Month', 'mo', 2000.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Rentals', 'WSC Skid Steer per hr', 'hr', 100.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Rentals', '305 Mini Day', 'day', 375.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Rentals', '305 Mini Week', 'wk', 1000.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Rentals', '305 Mini Month', 'mo', 2000.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Rentals', 'Roller Packer Day', 'day', 300.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Rentals', 'Roller Packer Week', 'wk', 1000.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Rentals', 'Roller Packer Month', 'mo', 2000.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Rentals', 'Equipment Delivery', 'ea', 150.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Rentals', 'Porta Potty per week', 'wk', 105.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Vantassel', 'Crane per hr', 'hr', 150.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Victor Transfer', 'Dump Trailer Load', 'ea', 120.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Out Of Town', 'Meals', 'ea', 120.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Out Of Town', 'Hotel', 'ea', 300.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Out Of Town', 'Fuel (Miles)', 'mi', 1.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('equipment', 'Out Of Town', 'OUT Employee Bounus', 'ea', 100.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('labor', 'Labor', 'Logan per day $20', 'day', 250.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('labor', 'Labor', 'Elias per day $23.50', 'day', 293.75);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('labor', 'Labor', 'Zook Per day $40', 'day', 500.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('labor', 'Labor', 'John Per day', 'day', 900.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('labor', 'Labor', 'Matt Per day', 'day', 900.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('labor', 'Labor', 'WSC Per day', 'day', 900.0);
INSERT INTO item_templates (type, category, name, default_unit, default_price) VALUES ('labor', 'Labor', 'Hourly Labor $100', 'hr', 100.0);

-- +goose Down
DELETE FROM item_templates;
