// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countCategoryAncestors = `-- name: CountCategoryAncestors :one
WITH RECURSIVE ancestors AS (
    SELECT categories.id, categories.parent_id, 0 as depth
    FROM categories
    WHERE categories.id = $1 AND categories.org_id = $2
    UNION ALL
    SELECT c.id, c.parent_id, a.depth + 1
    FROM categories c
    JOIN ancestors a ON c.id = a.parent_id
    WHERE c.org_id = $2
)
SELECT MAX(depth) as max_depth FROM ancestors
`

type CountCategoryAncestorsParams struct {
	ID    string        `json:"id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) CountCategoryAncestors(ctx context.Context, arg CountCategoryAncestorsParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, countCategoryAncestors, arg.ID, arg.OrgID)
	var max_depth interface{}
	err := row.Scan(&max_depth)
	return max_depth, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, org_id, job_id, parent_id, name, surcharge_percent, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, job_id, parent_id, name, surcharge_percent, sort_order, org_id
`

type CreateCategoryParams struct {
	ID               string          `json:"id"`
	OrgID            uuid.NullUUID   `json:"org_id"`
	JobID            string          `json:"job_id"`
	ParentID         sql.NullString  `json:"parent_id"`
	Name             string          `json:"name"`
	SurchargePercent sql.NullFloat64 `json:"surcharge_percent"`
	SortOrder        int64           `json:"sort_order"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.ID,
		arg.OrgID,
		arg.JobID,
		arg.ParentID,
		arg.Name,
		arg.SurchargePercent,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ParentID,
		&i.Name,
		&i.SurchargePercent,
		&i.SortOrder,
		&i.OrgID,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1 AND org_id = $2
`

type DeleteCategoryParams struct {
	ID    string        `json:"id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, arg.ID, arg.OrgID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, job_id, parent_id, name, surcharge_percent, sort_order, org_id FROM categories
WHERE id = $1 AND org_id = $2
`

type GetCategoryParams struct {
	ID    string        `json:"id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, arg.ID, arg.OrgID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ParentID,
		&i.Name,
		&i.SurchargePercent,
		&i.SortOrder,
		&i.OrgID,
	)
	return i, err
}

const listCategoriesByJob = `-- name: ListCategoriesByJob :many
SELECT id, job_id, parent_id, name, surcharge_percent, sort_order, org_id FROM categories
WHERE job_id = $1 AND org_id = $2
ORDER BY sort_order ASC
`

type ListCategoriesByJobParams struct {
	JobID string        `json:"job_id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) ListCategoriesByJob(ctx context.Context, arg ListCategoriesByJobParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByJob, arg.JobID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ParentID,
			&i.Name,
			&i.SurchargePercent,
			&i.SortOrder,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildCategories = `-- name: ListChildCategories :many
SELECT id, job_id, parent_id, name, surcharge_percent, sort_order, org_id FROM categories
WHERE parent_id = $1 AND org_id = $2
ORDER BY sort_order ASC
`

type ListChildCategoriesParams struct {
	ParentID sql.NullString `json:"parent_id"`
	OrgID    uuid.NullUUID  `json:"org_id"`
}

func (q *Queries) ListChildCategories(ctx context.Context, arg ListChildCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listChildCategories, arg.ParentID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ParentID,
			&i.Name,
			&i.SurchargePercent,
			&i.SortOrder,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopLevelCategories = `-- name: ListTopLevelCategories :many
SELECT id, job_id, parent_id, name, surcharge_percent, sort_order, org_id FROM categories
WHERE job_id = $1 AND org_id = $2 AND parent_id IS NULL
ORDER BY sort_order ASC
`

type ListTopLevelCategoriesParams struct {
	JobID string        `json:"job_id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) ListTopLevelCategories(ctx context.Context, arg ListTopLevelCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listTopLevelCategories, arg.JobID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ParentID,
			&i.Name,
			&i.SurchargePercent,
			&i.SortOrder,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET
    name = $1,
    surcharge_percent = $2,
    sort_order = $3
WHERE id = $4 AND org_id = $5
RETURNING id, job_id, parent_id, name, surcharge_percent, sort_order, org_id
`

type UpdateCategoryParams struct {
	Name             string          `json:"name"`
	SurchargePercent sql.NullFloat64 `json:"surcharge_percent"`
	SortOrder        int64           `json:"sort_order"`
	ID               string          `json:"id"`
	OrgID            uuid.NullUUID   `json:"org_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.Name,
		arg.SurchargePercent,
		arg.SortOrder,
		arg.ID,
		arg.OrgID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ParentID,
		&i.Name,
		&i.SurchargePercent,
		&i.SortOrder,
		&i.OrgID,
	)
	return i, err
}

const updateCategoryParent = `-- name: UpdateCategoryParent :one
UPDATE categories SET
    parent_id = $1
WHERE id = $2 AND org_id = $3
RETURNING id, job_id, parent_id, name, surcharge_percent, sort_order, org_id
`

type UpdateCategoryParentParams struct {
	ParentID sql.NullString `json:"parent_id"`
	ID       string         `json:"id"`
	OrgID    uuid.NullUUID  `json:"org_id"`
}

func (q *Queries) UpdateCategoryParent(ctx context.Context, arg UpdateCategoryParentParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategoryParent, arg.ParentID, arg.ID, arg.OrgID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ParentID,
		&i.Name,
		&i.SurchargePercent,
		&i.SortOrder,
		&i.OrgID,
	)
	return i, err
}
