// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package repository

import (
	"context"
	"database/sql"
)

const countCategoryAncestors = `-- name: CountCategoryAncestors :one
WITH RECURSIVE ancestors AS (
    SELECT categories.id, categories.parent_id, 0 as depth
    FROM categories
    WHERE categories.id = ?
    UNION ALL
    SELECT c.id, c.parent_id, a.depth + 1
    FROM categories c
    JOIN ancestors a ON c.id = a.parent_id
)
SELECT MAX(depth) as max_depth FROM ancestors
`

func (q *Queries) CountCategoryAncestors(ctx context.Context, id string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, countCategoryAncestors, id)
	var max_depth interface{}
	err := row.Scan(&max_depth)
	return max_depth, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, job_id, parent_id, name, surcharge_percent, sort_order)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, job_id, parent_id, name, surcharge_percent, sort_order
`

type CreateCategoryParams struct {
	ID               string          `json:"id"`
	JobID            string          `json:"job_id"`
	ParentID         sql.NullString  `json:"parent_id"`
	Name             string          `json:"name"`
	SurchargePercent sql.NullFloat64 `json:"surcharge_percent"`
	SortOrder        int64           `json:"sort_order"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.ID,
		arg.JobID,
		arg.ParentID,
		arg.Name,
		arg.SurchargePercent,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ParentID,
		&i.Name,
		&i.SurchargePercent,
		&i.SortOrder,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, job_id, parent_id, name, surcharge_percent, sort_order FROM categories
WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ParentID,
		&i.Name,
		&i.SurchargePercent,
		&i.SortOrder,
	)
	return i, err
}

const listCategoriesByJob = `-- name: ListCategoriesByJob :many
SELECT id, job_id, parent_id, name, surcharge_percent, sort_order FROM categories
WHERE job_id = ?
ORDER BY sort_order ASC
`

func (q *Queries) ListCategoriesByJob(ctx context.Context, jobID string) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ParentID,
			&i.Name,
			&i.SurchargePercent,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildCategories = `-- name: ListChildCategories :many
SELECT id, job_id, parent_id, name, surcharge_percent, sort_order FROM categories
WHERE parent_id = ?
ORDER BY sort_order ASC
`

func (q *Queries) ListChildCategories(ctx context.Context, parentID sql.NullString) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listChildCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ParentID,
			&i.Name,
			&i.SurchargePercent,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopLevelCategories = `-- name: ListTopLevelCategories :many
SELECT id, job_id, parent_id, name, surcharge_percent, sort_order FROM categories
WHERE job_id = ? AND parent_id IS NULL
ORDER BY sort_order ASC
`

func (q *Queries) ListTopLevelCategories(ctx context.Context, jobID string) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listTopLevelCategories, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ParentID,
			&i.Name,
			&i.SurchargePercent,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET
    name = ?,
    surcharge_percent = ?,
    sort_order = ?
WHERE id = ?
RETURNING id, job_id, parent_id, name, surcharge_percent, sort_order
`

type UpdateCategoryParams struct {
	Name             string          `json:"name"`
	SurchargePercent sql.NullFloat64 `json:"surcharge_percent"`
	SortOrder        int64           `json:"sort_order"`
	ID               string          `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.Name,
		arg.SurchargePercent,
		arg.SortOrder,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ParentID,
		&i.Name,
		&i.SurchargePercent,
		&i.SortOrder,
	)
	return i, err
}

const updateCategoryParent = `-- name: UpdateCategoryParent :one
UPDATE categories SET
    parent_id = ?
WHERE id = ?
RETURNING id, job_id, parent_id, name, surcharge_percent, sort_order
`

type UpdateCategoryParentParams struct {
	ParentID sql.NullString `json:"parent_id"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateCategoryParent(ctx context.Context, arg UpdateCategoryParentParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategoryParent, arg.ParentID, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ParentID,
		&i.Name,
		&i.SurchargePercent,
		&i.SortOrder,
	)
	return i, err
}
