// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package repository

import (
	"context"
	"database/sql"
)

const countClients = `-- name: CountClients :one
SELECT COUNT(*) AS total FROM clients
`

func (q *Queries) CountClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClients)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countProjectsByClient = `-- name: CountProjectsByClient :one
SELECT COUNT(*) AS total FROM projects WHERE client_id = $1
`

func (q *Queries) CountProjectsByClient(ctx context.Context, clientID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectsByClient, clientID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countTotalClientProjects = `-- name: CountTotalClientProjects :one
SELECT COUNT(*) AS total FROM projects WHERE client_id IS NOT NULL
`

func (q *Queries) CountTotalClientProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTotalClientProjects)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (id, company_name, contact_name, email, phone, address, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_name, contact_name, email, phone, address, notes, created_at
`

type CreateClientParams struct {
	ID          string         `json:"id"`
	CompanyName string         `json:"company_name"`
	ContactName sql.NullString `json:"contact_name"`
	Email       sql.NullString `json:"email"`
	Phone       sql.NullString `json:"phone"`
	Address     sql.NullString `json:"address"`
	Notes       sql.NullString `json:"notes"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.ID,
		arg.CompanyName,
		arg.ContactName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.Notes,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClient, id)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, company_name, contact_name, email, phone, address, notes, created_at FROM clients WHERE id = $1
`

func (q *Queries) GetClient(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, company_name, contact_name, email, phone, address, notes, created_at FROM clients ORDER BY company_name ASC
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.ContactName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClients = `-- name: SearchClients :many
SELECT id, company_name, contact_name, email, phone, address, notes, created_at FROM clients
WHERE company_name ILIKE '%' || $1::text || '%'
   OR contact_name ILIKE '%' || $1::text || '%'
   OR email ILIKE '%' || $1::text || '%'
   OR phone ILIKE '%' || $1::text || '%'
ORDER BY company_name ASC
`

func (q *Queries) SearchClients(ctx context.Context, searchTerm string) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, searchClients, searchTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.ContactName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET company_name = $2, contact_name = $3, email = $4, phone = $5, address = $6, notes = $7
WHERE id = $1
RETURNING id, company_name, contact_name, email, phone, address, notes, created_at
`

type UpdateClientParams struct {
	ID          string         `json:"id"`
	CompanyName string         `json:"company_name"`
	ContactName sql.NullString `json:"contact_name"`
	Email       sql.NullString `json:"email"`
	Phone       sql.NullString `json:"phone"`
	Address     sql.NullString `json:"address"`
	Notes       sql.NullString `json:"notes"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.ID,
		arg.CompanyName,
		arg.ContactName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.Notes,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
