// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const clientHasJobs = `-- name: ClientHasJobs :one
SELECT COUNT(*) > 0 FROM jobs WHERE client_id = $1 AND org_id = $2
`

type ClientHasJobsParams struct {
	ClientID sql.NullString `json:"client_id"`
	OrgID    uuid.NullUUID  `json:"org_id"`
}

func (q *Queries) ClientHasJobs(ctx context.Context, arg ClientHasJobsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, clientHasJobs, arg.ClientID, arg.OrgID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const countClients = `-- name: CountClients :one
SELECT COUNT(*) FROM clients
WHERE org_id = $1
  AND ($2 = '' OR name LIKE '%' || $2 || '%' OR company LIKE '%' || $2 || '%')
`

type CountClientsParams struct {
	OrgID  uuid.NullUUID `json:"org_id"`
	Search interface{}   `json:"search"`
}

func (q *Queries) CountClients(ctx context.Context, arg CountClientsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClients, arg.OrgID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (id, org_id, name, company, email, phone, address, city, state, zip, tax_id, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, name, company, email, phone, address, city, state, zip, tax_id, notes, created_at, org_id
`

type CreateClientParams struct {
	ID      string         `json:"id"`
	OrgID   uuid.NullUUID  `json:"org_id"`
	Name    string         `json:"name"`
	Company sql.NullString `json:"company"`
	Email   sql.NullString `json:"email"`
	Phone   sql.NullString `json:"phone"`
	Address sql.NullString `json:"address"`
	City    sql.NullString `json:"city"`
	State   sql.NullString `json:"state"`
	Zip     sql.NullString `json:"zip"`
	TaxID   sql.NullString `json:"tax_id"`
	Notes   sql.NullString `json:"notes"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Company,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.TaxID,
		arg.Notes,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.TaxID,
		&i.Notes,
		&i.CreatedAt,
		&i.OrgID,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = $1 AND org_id = $2
`

type DeleteClientParams struct {
	ID    string        `json:"id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) DeleteClient(ctx context.Context, arg DeleteClientParams) error {
	_, err := q.db.ExecContext(ctx, deleteClient, arg.ID, arg.OrgID)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, name, company, email, phone, address, city, state, zip, tax_id, notes, created_at, org_id FROM clients WHERE id = $1 AND org_id = $2
`

type GetClientParams struct {
	ID    string        `json:"id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) GetClient(ctx context.Context, arg GetClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClient, arg.ID, arg.OrgID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.TaxID,
		&i.Notes,
		&i.CreatedAt,
		&i.OrgID,
	)
	return i, err
}

const getClientByName = `-- name: GetClientByName :one
SELECT id, name, company, email, phone, address, city, state, zip, tax_id, notes, created_at, org_id FROM clients WHERE name = $1 AND org_id = $2
`

type GetClientByNameParams struct {
	Name  string        `json:"name"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) GetClientByName(ctx context.Context, arg GetClientByNameParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByName, arg.Name, arg.OrgID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.TaxID,
		&i.Notes,
		&i.CreatedAt,
		&i.OrgID,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, company, email, phone, address, city, state, zip, tax_id, notes, created_at, org_id FROM clients WHERE org_id = $1 ORDER BY name ASC
`

func (q *Queries) ListClients(ctx context.Context, orgID uuid.NullUUID) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Company,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.TaxID,
			&i.Notes,
			&i.CreatedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientsPaginated = `-- name: ListClientsPaginated :many
SELECT id, name, company, email, phone, address, city, state, zip, tax_id, notes, created_at, org_id FROM clients
WHERE org_id = $1
  AND ($2 = '' OR name LIKE '%' || $2 || '%' OR company LIKE '%' || $2 || '%')
ORDER BY name ASC
LIMIT $4 OFFSET $3
`

type ListClientsPaginatedParams struct {
	OrgID  uuid.NullUUID `json:"org_id"`
	Search interface{}   `json:"search"`
	Offset int32         `json:"offset"`
	Limit  int32         `json:"limit"`
}

func (q *Queries) ListClientsPaginated(ctx context.Context, arg ListClientsPaginatedParams) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClientsPaginated,
		arg.OrgID,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Company,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.TaxID,
			&i.Notes,
			&i.CreatedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients SET
    name = $1,
    company = $2,
    email = $3,
    phone = $4,
    address = $5,
    city = $6,
    state = $7,
    zip = $8,
    tax_id = $9,
    notes = $10
WHERE id = $11 AND org_id = $12
RETURNING id, name, company, email, phone, address, city, state, zip, tax_id, notes, created_at, org_id
`

type UpdateClientParams struct {
	Name    string         `json:"name"`
	Company sql.NullString `json:"company"`
	Email   sql.NullString `json:"email"`
	Phone   sql.NullString `json:"phone"`
	Address sql.NullString `json:"address"`
	City    sql.NullString `json:"city"`
	State   sql.NullString `json:"state"`
	Zip     sql.NullString `json:"zip"`
	TaxID   sql.NullString `json:"tax_id"`
	Notes   sql.NullString `json:"notes"`
	ID      string         `json:"id"`
	OrgID   uuid.NullUUID  `json:"org_id"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.Name,
		arg.Company,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.TaxID,
		arg.Notes,
		arg.ID,
		arg.OrgID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.TaxID,
		&i.Notes,
		&i.CreatedAt,
		&i.OrgID,
	)
	return i, err
}
