// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCompanyProfile = `-- name: CreateCompanyProfile :one
INSERT INTO company_profile (org_id, name, email, phone, address, city, state, zip, logo_path)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING name, email, phone, address, city, state, zip, logo_path, created_at, updated_at, org_id
`

type CreateCompanyProfileParams struct {
	OrgID    uuid.UUID      `json:"org_id"`
	Name     string         `json:"name"`
	Email    sql.NullString `json:"email"`
	Phone    sql.NullString `json:"phone"`
	Address  sql.NullString `json:"address"`
	City     sql.NullString `json:"city"`
	State    sql.NullString `json:"state"`
	Zip      sql.NullString `json:"zip"`
	LogoPath sql.NullString `json:"logo_path"`
}

func (q *Queries) CreateCompanyProfile(ctx context.Context, arg CreateCompanyProfileParams) (CompanyProfile, error) {
	row := q.db.QueryRowContext(ctx, createCompanyProfile,
		arg.OrgID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.LogoPath,
	)
	var i CompanyProfile
	err := row.Scan(
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.LogoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const getCompanyProfile = `-- name: GetCompanyProfile :one
SELECT name, email, phone, address, city, state, zip, logo_path, created_at, updated_at, org_id FROM company_profile WHERE org_id = $1
`

func (q *Queries) GetCompanyProfile(ctx context.Context, orgID uuid.UUID) (CompanyProfile, error) {
	row := q.db.QueryRowContext(ctx, getCompanyProfile, orgID)
	var i CompanyProfile
	err := row.Scan(
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.LogoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const updateCompanyProfile = `-- name: UpdateCompanyProfile :one
UPDATE company_profile SET
    name = $1,
    email = $2,
    phone = $3,
    address = $4,
    city = $5,
    state = $6,
    zip = $7,
    logo_path = $8,
    updated_at = NOW()
WHERE org_id = $9
RETURNING name, email, phone, address, city, state, zip, logo_path, created_at, updated_at, org_id
`

type UpdateCompanyProfileParams struct {
	Name     string         `json:"name"`
	Email    sql.NullString `json:"email"`
	Phone    sql.NullString `json:"phone"`
	Address  sql.NullString `json:"address"`
	City     sql.NullString `json:"city"`
	State    sql.NullString `json:"state"`
	Zip      sql.NullString `json:"zip"`
	LogoPath sql.NullString `json:"logo_path"`
	OrgID    uuid.UUID      `json:"org_id"`
}

func (q *Queries) UpdateCompanyProfile(ctx context.Context, arg UpdateCompanyProfileParams) (CompanyProfile, error) {
	row := q.db.QueryRowContext(ctx, updateCompanyProfile,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.LogoPath,
		arg.OrgID,
	)
	var i CompanyProfile
	err := row.Scan(
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.LogoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}
