// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company.sql

package repository

import (
	"context"
	"database/sql"
)

const getCompanyProfile = `-- name: GetCompanyProfile :one
SELECT id, name, email, phone, address, city, state, zip, logo_path, created_at, updated_at FROM company_profile WHERE id = 'default'
`

func (q *Queries) GetCompanyProfile(ctx context.Context) (CompanyProfile, error) {
	row := q.db.QueryRowContext(ctx, getCompanyProfile)
	var i CompanyProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.LogoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCompanyProfile = `-- name: UpdateCompanyProfile :one
UPDATE company_profile SET
    name = ?,
    email = ?,
    phone = ?,
    address = ?,
    city = ?,
    state = ?,
    zip = ?,
    logo_path = ?,
    updated_at = datetime('now')
WHERE id = 'default'
RETURNING id, name, email, phone, address, city, state, zip, logo_path, created_at, updated_at
`

type UpdateCompanyProfileParams struct {
	Name     string         `json:"name"`
	Email    sql.NullString `json:"email"`
	Phone    sql.NullString `json:"phone"`
	Address  sql.NullString `json:"address"`
	City     sql.NullString `json:"city"`
	State    sql.NullString `json:"state"`
	Zip      sql.NullString `json:"zip"`
	LogoPath sql.NullString `json:"logo_path"`
}

func (q *Queries) UpdateCompanyProfile(ctx context.Context, arg UpdateCompanyProfileParams) (CompanyProfile, error) {
	row := q.db.QueryRowContext(ctx, updateCompanyProfile,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.LogoPath,
	)
	var i CompanyProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.LogoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
