// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company_profile.sql

package repository

import (
	"context"
	"database/sql"
)

const getCompanyProfile = `-- name: GetCompanyProfile :one
SELECT id, name, email, phone, address, city, state, zip, logo_path, updated_at FROM company_profile WHERE id = 'default'
`

func (q *Queries) GetCompanyProfile(ctx context.Context) (CompanyProfile, error) {
	row := q.db.QueryRowContext(ctx, getCompanyProfile)
	var i CompanyProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.LogoPath,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCompanyProfile = `-- name: UpsertCompanyProfile :one
INSERT INTO company_profile (id, name, email, phone, address, city, state, zip)
VALUES ('default', $1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    updated_at = now()
RETURNING id, name, email, phone, address, city, state, zip, logo_path, updated_at
`

type UpsertCompanyProfileParams struct {
	Name    string         `json:"name"`
	Email   sql.NullString `json:"email"`
	Phone   sql.NullString `json:"phone"`
	Address sql.NullString `json:"address"`
	City    sql.NullString `json:"city"`
	State   sql.NullString `json:"state"`
	Zip     sql.NullString `json:"zip"`
}

func (q *Queries) UpsertCompanyProfile(ctx context.Context, arg UpsertCompanyProfileParams) (CompanyProfile, error) {
	row := q.db.QueryRowContext(ctx, upsertCompanyProfile,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
	)
	var i CompanyProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.LogoPath,
		&i.UpdatedAt,
	)
	return i, err
}
