// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: estimates.sql

package repository

import (
	"context"
	"database/sql"
)

const createEstimate = `-- name: CreateEstimate :one
INSERT INTO estimates (id, job_id, version, status, grand_total, notes)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, job_id, version, status, grand_total, notes, sent_at, responded_at, created_at
`

type CreateEstimateParams struct {
	ID         string         `json:"id"`
	JobID      string         `json:"job_id"`
	Version    int64          `json:"version"`
	Status     string         `json:"status"`
	GrandTotal float64        `json:"grand_total"`
	Notes      sql.NullString `json:"notes"`
}

func (q *Queries) CreateEstimate(ctx context.Context, arg CreateEstimateParams) (Estimate, error) {
	row := q.db.QueryRowContext(ctx, createEstimate,
		arg.ID,
		arg.JobID,
		arg.Version,
		arg.Status,
		arg.GrandTotal,
		arg.Notes,
	)
	var i Estimate
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Version,
		&i.Status,
		&i.GrandTotal,
		&i.Notes,
		&i.SentAt,
		&i.RespondedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createEstimateCategory = `-- name: CreateEstimateCategory :one
INSERT INTO estimate_categories (id, estimate_id, category_id, parent_category_id, tier, name, description, total, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, estimate_id, category_id, parent_category_id, tier, name, description, total, sort_order
`

type CreateEstimateCategoryParams struct {
	ID               string         `json:"id"`
	EstimateID       string         `json:"estimate_id"`
	CategoryID       string         `json:"category_id"`
	ParentCategoryID sql.NullString `json:"parent_category_id"`
	Tier             int64          `json:"tier"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	Total            float64        `json:"total"`
	SortOrder        int64          `json:"sort_order"`
}

func (q *Queries) CreateEstimateCategory(ctx context.Context, arg CreateEstimateCategoryParams) (EstimateCategory, error) {
	row := q.db.QueryRowContext(ctx, createEstimateCategory,
		arg.ID,
		arg.EstimateID,
		arg.CategoryID,
		arg.ParentCategoryID,
		arg.Tier,
		arg.Name,
		arg.Description,
		arg.Total,
		arg.SortOrder,
	)
	var i EstimateCategory
	err := row.Scan(
		&i.ID,
		&i.EstimateID,
		&i.CategoryID,
		&i.ParentCategoryID,
		&i.Tier,
		&i.Name,
		&i.Description,
		&i.Total,
		&i.SortOrder,
	)
	return i, err
}

const deleteEstimate = `-- name: DeleteEstimate :exec
DELETE FROM estimates WHERE id = ?
`

func (q *Queries) DeleteEstimate(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEstimate, id)
	return err
}

const deleteEstimateCategoriesByEstimate = `-- name: DeleteEstimateCategoriesByEstimate :exec
DELETE FROM estimate_categories WHERE estimate_id = ?
`

func (q *Queries) DeleteEstimateCategoriesByEstimate(ctx context.Context, estimateID string) error {
	_, err := q.db.ExecContext(ctx, deleteEstimateCategoriesByEstimate, estimateID)
	return err
}

const getEstimate = `-- name: GetEstimate :one
SELECT id, job_id, version, status, grand_total, notes, sent_at, responded_at, created_at FROM estimates WHERE id = ?
`

func (q *Queries) GetEstimate(ctx context.Context, id string) (Estimate, error) {
	row := q.db.QueryRowContext(ctx, getEstimate, id)
	var i Estimate
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Version,
		&i.Status,
		&i.GrandTotal,
		&i.Notes,
		&i.SentAt,
		&i.RespondedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEstimateByJobAndVersion = `-- name: GetEstimateByJobAndVersion :one
SELECT id, job_id, version, status, grand_total, notes, sent_at, responded_at, created_at FROM estimates WHERE job_id = ? AND version = ?
`

type GetEstimateByJobAndVersionParams struct {
	JobID   string `json:"job_id"`
	Version int64  `json:"version"`
}

func (q *Queries) GetEstimateByJobAndVersion(ctx context.Context, arg GetEstimateByJobAndVersionParams) (Estimate, error) {
	row := q.db.QueryRowContext(ctx, getEstimateByJobAndVersion, arg.JobID, arg.Version)
	var i Estimate
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Version,
		&i.Status,
		&i.GrandTotal,
		&i.Notes,
		&i.SentAt,
		&i.RespondedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEstimateCategory = `-- name: GetEstimateCategory :one
SELECT id, estimate_id, category_id, parent_category_id, tier, name, description, total, sort_order FROM estimate_categories WHERE id = ?
`

func (q *Queries) GetEstimateCategory(ctx context.Context, id string) (EstimateCategory, error) {
	row := q.db.QueryRowContext(ctx, getEstimateCategory, id)
	var i EstimateCategory
	err := row.Scan(
		&i.ID,
		&i.EstimateID,
		&i.CategoryID,
		&i.ParentCategoryID,
		&i.Tier,
		&i.Name,
		&i.Description,
		&i.Total,
		&i.SortOrder,
	)
	return i, err
}

const getLatestEstimateVersion = `-- name: GetLatestEstimateVersion :one
SELECT CAST(COALESCE(MAX(version), 0) AS INTEGER) as max_version
FROM estimates
WHERE job_id = ?
`

func (q *Queries) GetLatestEstimateVersion(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLatestEstimateVersion, jobID)
	var max_version int64
	err := row.Scan(&max_version)
	return max_version, err
}

const listEstimateCategoriesByEstimate = `-- name: ListEstimateCategoriesByEstimate :many
SELECT id, estimate_id, category_id, parent_category_id, tier, name, description, total, sort_order FROM estimate_categories
WHERE estimate_id = ?
ORDER BY tier ASC, sort_order ASC
`

func (q *Queries) ListEstimateCategoriesByEstimate(ctx context.Context, estimateID string) ([]EstimateCategory, error) {
	rows, err := q.db.QueryContext(ctx, listEstimateCategoriesByEstimate, estimateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EstimateCategory{}
	for rows.Next() {
		var i EstimateCategory
		if err := rows.Scan(
			&i.ID,
			&i.EstimateID,
			&i.CategoryID,
			&i.ParentCategoryID,
			&i.Tier,
			&i.Name,
			&i.Description,
			&i.Total,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEstimateCategoriesByParent = `-- name: ListEstimateCategoriesByParent :many
SELECT id, estimate_id, category_id, parent_category_id, tier, name, description, total, sort_order FROM estimate_categories
WHERE estimate_id = ? AND parent_category_id = ?
ORDER BY sort_order ASC
`

type ListEstimateCategoriesByParentParams struct {
	EstimateID       string         `json:"estimate_id"`
	ParentCategoryID sql.NullString `json:"parent_category_id"`
}

func (q *Queries) ListEstimateCategoriesByParent(ctx context.Context, arg ListEstimateCategoriesByParentParams) ([]EstimateCategory, error) {
	rows, err := q.db.QueryContext(ctx, listEstimateCategoriesByParent, arg.EstimateID, arg.ParentCategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EstimateCategory{}
	for rows.Next() {
		var i EstimateCategory
		if err := rows.Scan(
			&i.ID,
			&i.EstimateID,
			&i.CategoryID,
			&i.ParentCategoryID,
			&i.Tier,
			&i.Name,
			&i.Description,
			&i.Total,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEstimateCategoriesTier1 = `-- name: ListEstimateCategoriesTier1 :many
SELECT id, estimate_id, category_id, parent_category_id, tier, name, description, total, sort_order FROM estimate_categories
WHERE estimate_id = ? AND tier = 1
ORDER BY sort_order ASC
`

func (q *Queries) ListEstimateCategoriesTier1(ctx context.Context, estimateID string) ([]EstimateCategory, error) {
	rows, err := q.db.QueryContext(ctx, listEstimateCategoriesTier1, estimateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EstimateCategory{}
	for rows.Next() {
		var i EstimateCategory
		if err := rows.Scan(
			&i.ID,
			&i.EstimateID,
			&i.CategoryID,
			&i.ParentCategoryID,
			&i.Tier,
			&i.Name,
			&i.Description,
			&i.Total,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEstimatesByJob = `-- name: ListEstimatesByJob :many
SELECT id, job_id, version, status, grand_total, notes, sent_at, responded_at, created_at FROM estimates
WHERE job_id = ?
ORDER BY version DESC
`

func (q *Queries) ListEstimatesByJob(ctx context.Context, jobID string) ([]Estimate, error) {
	rows, err := q.db.QueryContext(ctx, listEstimatesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Estimate{}
	for rows.Next() {
		var i Estimate
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Version,
			&i.Status,
			&i.GrandTotal,
			&i.Notes,
			&i.SentAt,
			&i.RespondedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEstimate = `-- name: UpdateEstimate :one
UPDATE estimates SET
    status = ?,
    notes = ?,
    sent_at = ?,
    responded_at = ?
WHERE id = ?
RETURNING id, job_id, version, status, grand_total, notes, sent_at, responded_at, created_at
`

type UpdateEstimateParams struct {
	Status      string         `json:"status"`
	Notes       sql.NullString `json:"notes"`
	SentAt      sql.NullString `json:"sent_at"`
	RespondedAt sql.NullString `json:"responded_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateEstimate(ctx context.Context, arg UpdateEstimateParams) (Estimate, error) {
	row := q.db.QueryRowContext(ctx, updateEstimate,
		arg.Status,
		arg.Notes,
		arg.SentAt,
		arg.RespondedAt,
		arg.ID,
	)
	var i Estimate
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Version,
		&i.Status,
		&i.GrandTotal,
		&i.Notes,
		&i.SentAt,
		&i.RespondedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateEstimateCategoryDescription = `-- name: UpdateEstimateCategoryDescription :one
UPDATE estimate_categories SET description = ?
WHERE id = ?
RETURNING id, estimate_id, category_id, parent_category_id, tier, name, description, total, sort_order
`

type UpdateEstimateCategoryDescriptionParams struct {
	Description sql.NullString `json:"description"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateEstimateCategoryDescription(ctx context.Context, arg UpdateEstimateCategoryDescriptionParams) (EstimateCategory, error) {
	row := q.db.QueryRowContext(ctx, updateEstimateCategoryDescription, arg.Description, arg.ID)
	var i EstimateCategory
	err := row.Scan(
		&i.ID,
		&i.EstimateID,
		&i.CategoryID,
		&i.ParentCategoryID,
		&i.Tier,
		&i.Name,
		&i.Description,
		&i.Total,
		&i.SortOrder,
	)
	return i, err
}
