// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: estimate_builder.sql

package repository

import (
	"context"
	"database/sql"
)

const createComponentGroup = `-- name: CreateComponentGroup :one
INSERT INTO component_groups (id, subcategory_id, name, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, subcategory_id, name, sort_order
`

type CreateComponentGroupParams struct {
	ID            string `json:"id"`
	SubcategoryID string `json:"subcategory_id"`
	Name          string `json:"name"`
	SortOrder     int64  `json:"sort_order"`
}

func (q *Queries) CreateComponentGroup(ctx context.Context, arg CreateComponentGroupParams) (ComponentGroup, error) {
	row := q.db.QueryRowContext(ctx, createComponentGroup,
		arg.ID,
		arg.SubcategoryID,
		arg.Name,
		arg.SortOrder,
	)
	var i ComponentGroup
	err := row.Scan(
		&i.ID,
		&i.SubcategoryID,
		&i.Name,
		&i.SortOrder,
	)
	return i, err
}

const createLineItem = `-- name: CreateLineItem :one
INSERT INTO line_items (
    id, subcategory_id, component_group_id, category_type, item_name,
    quantity, unit, unit_price, is_custom, material_id,
    price_override, description, sort_order
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13
)
RETURNING id, subcategory_id, component_group_id, category_type, item_name, quantity, unit, unit_price, is_custom, material_id, price_override, description, sort_order
`

type CreateLineItemParams struct {
	ID               string         `json:"id"`
	SubcategoryID    string         `json:"subcategory_id"`
	ComponentGroupID sql.NullString `json:"component_group_id"`
	CategoryType     string         `json:"category_type"`
	ItemName         string         `json:"item_name"`
	Quantity         float64        `json:"quantity"`
	Unit             string         `json:"unit"`
	UnitPrice        float64        `json:"unit_price"`
	IsCustom         bool           `json:"is_custom"`
	MaterialID       sql.NullString `json:"material_id"`
	PriceOverride    bool           `json:"price_override"`
	Description      sql.NullString `json:"description"`
	SortOrder        int64          `json:"sort_order"`
}

func (q *Queries) CreateLineItem(ctx context.Context, arg CreateLineItemParams) (LineItem, error) {
	row := q.db.QueryRowContext(ctx, createLineItem,
		arg.ID,
		arg.SubcategoryID,
		arg.ComponentGroupID,
		arg.CategoryType,
		arg.ItemName,
		arg.Quantity,
		arg.Unit,
		arg.UnitPrice,
		arg.IsCustom,
		arg.MaterialID,
		arg.PriceOverride,
		arg.Description,
		arg.SortOrder,
	)
	var i LineItem
	err := row.Scan(
		&i.ID,
		&i.SubcategoryID,
		&i.ComponentGroupID,
		&i.CategoryType,
		&i.ItemName,
		&i.Quantity,
		&i.Unit,
		&i.UnitPrice,
		&i.IsCustom,
		&i.MaterialID,
		&i.PriceOverride,
		&i.Description,
		&i.SortOrder,
	)
	return i, err
}

const createSection = `-- name: CreateSection :one
INSERT INTO sections (id, project_id, name, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, sort_order
`

type CreateSectionParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error) {
	row := q.db.QueryRowContext(ctx, createSection,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.SortOrder,
	)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.SortOrder,
	)
	return i, err
}

const createSubcategory = `-- name: CreateSubcategory :one
INSERT INTO subcategories (
    id, section_id, name, sort_order, lump_sum,
    materials_markup, labor_markup, equipment_markup, subs_markup, other_markup,
    materials_markup_enabled, labor_markup_enabled, equipment_markup_enabled,
    subs_markup_enabled, other_markup_enabled
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15
)
RETURNING id, section_id, name, sort_order, lump_sum, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup, materials_markup_enabled, labor_markup_enabled, equipment_markup_enabled, subs_markup_enabled, other_markup_enabled
`

type CreateSubcategoryParams struct {
	ID                     string          `json:"id"`
	SectionID              string          `json:"section_id"`
	Name                   string          `json:"name"`
	SortOrder              int64           `json:"sort_order"`
	LumpSum                float64         `json:"lump_sum"`
	MaterialsMarkup        sql.NullFloat64 `json:"materials_markup"`
	LaborMarkup            sql.NullFloat64 `json:"labor_markup"`
	EquipmentMarkup        sql.NullFloat64 `json:"equipment_markup"`
	SubsMarkup             sql.NullFloat64 `json:"subs_markup"`
	OtherMarkup            sql.NullFloat64 `json:"other_markup"`
	MaterialsMarkupEnabled bool            `json:"materials_markup_enabled"`
	LaborMarkupEnabled     bool            `json:"labor_markup_enabled"`
	EquipmentMarkupEnabled bool            `json:"equipment_markup_enabled"`
	SubsMarkupEnabled      bool            `json:"subs_markup_enabled"`
	OtherMarkupEnabled     bool            `json:"other_markup_enabled"`
}

func (q *Queries) CreateSubcategory(ctx context.Context, arg CreateSubcategoryParams) (Subcategory, error) {
	row := q.db.QueryRowContext(ctx, createSubcategory,
		arg.ID,
		arg.SectionID,
		arg.Name,
		arg.SortOrder,
		arg.LumpSum,
		arg.MaterialsMarkup,
		arg.LaborMarkup,
		arg.EquipmentMarkup,
		arg.SubsMarkup,
		arg.OtherMarkup,
		arg.MaterialsMarkupEnabled,
		arg.LaborMarkupEnabled,
		arg.EquipmentMarkupEnabled,
		arg.SubsMarkupEnabled,
		arg.OtherMarkupEnabled,
	)
	var i Subcategory
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Name,
		&i.SortOrder,
		&i.LumpSum,
		&i.MaterialsMarkup,
		&i.LaborMarkup,
		&i.EquipmentMarkup,
		&i.SubsMarkup,
		&i.OtherMarkup,
		&i.MaterialsMarkupEnabled,
		&i.LaborMarkupEnabled,
		&i.EquipmentMarkupEnabled,
		&i.SubsMarkupEnabled,
		&i.OtherMarkupEnabled,
	)
	return i, err
}

const deleteSectionsByProject = `-- name: DeleteSectionsByProject :exec
DELETE FROM sections WHERE project_id = $1
`

func (q *Queries) DeleteSectionsByProject(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteSectionsByProject, projectID)
	return err
}

const getProjectMarkups = `-- name: GetProjectMarkups :one
SELECT materials_markup, labor_markup, equipment_markup, subs_markup, other_markup
FROM projects WHERE id = $1
`

type GetProjectMarkupsRow struct {
	MaterialsMarkup float64 `json:"materials_markup"`
	LaborMarkup     float64 `json:"labor_markup"`
	EquipmentMarkup float64 `json:"equipment_markup"`
	SubsMarkup      float64 `json:"subs_markup"`
	OtherMarkup     float64 `json:"other_markup"`
}

// Project markup globals
func (q *Queries) GetProjectMarkups(ctx context.Context, id string) (GetProjectMarkupsRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectMarkups, id)
	var i GetProjectMarkupsRow
	err := row.Scan(
		&i.MaterialsMarkup,
		&i.LaborMarkup,
		&i.EquipmentMarkup,
		&i.SubsMarkup,
		&i.OtherMarkup,
	)
	return i, err
}

const listComponentGroupsBySubcategory = `-- name: ListComponentGroupsBySubcategory :many
SELECT id, subcategory_id, name, sort_order FROM component_groups WHERE subcategory_id = $1 ORDER BY sort_order ASC
`

// Component Groups
func (q *Queries) ListComponentGroupsBySubcategory(ctx context.Context, subcategoryID string) ([]ComponentGroup, error) {
	rows, err := q.db.QueryContext(ctx, listComponentGroupsBySubcategory, subcategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComponentGroup{}
	for rows.Next() {
		var i ComponentGroup
		if err := rows.Scan(
			&i.ID,
			&i.SubcategoryID,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLineItemsBySubcategory = `-- name: ListLineItemsBySubcategory :many
SELECT id, subcategory_id, component_group_id, category_type, item_name, quantity, unit, unit_price, is_custom, material_id, price_override, description, sort_order FROM line_items WHERE subcategory_id = $1 ORDER BY sort_order ASC
`

// Line Items
func (q *Queries) ListLineItemsBySubcategory(ctx context.Context, subcategoryID string) ([]LineItem, error) {
	rows, err := q.db.QueryContext(ctx, listLineItemsBySubcategory, subcategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LineItem{}
	for rows.Next() {
		var i LineItem
		if err := rows.Scan(
			&i.ID,
			&i.SubcategoryID,
			&i.ComponentGroupID,
			&i.CategoryType,
			&i.ItemName,
			&i.Quantity,
			&i.Unit,
			&i.UnitPrice,
			&i.IsCustom,
			&i.MaterialID,
			&i.PriceOverride,
			&i.Description,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByProject = `-- name: ListSectionsByProject :many
SELECT id, project_id, name, sort_order FROM sections WHERE project_id = $1 ORDER BY sort_order ASC
`

// Sections
func (q *Queries) ListSectionsByProject(ctx context.Context, projectID string) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, listSectionsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Section{}
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubcategoriesBySection = `-- name: ListSubcategoriesBySection :many
SELECT id, section_id, name, sort_order, lump_sum, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup, materials_markup_enabled, labor_markup_enabled, equipment_markup_enabled, subs_markup_enabled, other_markup_enabled FROM subcategories WHERE section_id = $1 ORDER BY sort_order ASC
`

// Subcategories (joined through sections)
func (q *Queries) ListSubcategoriesBySection(ctx context.Context, sectionID string) ([]Subcategory, error) {
	rows, err := q.db.QueryContext(ctx, listSubcategoriesBySection, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subcategory{}
	for rows.Next() {
		var i Subcategory
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Name,
			&i.SortOrder,
			&i.LumpSum,
			&i.MaterialsMarkup,
			&i.LaborMarkup,
			&i.EquipmentMarkup,
			&i.SubsMarkup,
			&i.OtherMarkup,
			&i.MaterialsMarkupEnabled,
			&i.LaborMarkupEnabled,
			&i.EquipmentMarkupEnabled,
			&i.SubsMarkupEnabled,
			&i.OtherMarkupEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectMarkups = `-- name: UpdateProjectMarkups :exec
UPDATE projects
SET materials_markup = $2, labor_markup = $3, equipment_markup = $4,
    subs_markup = $5, other_markup = $6, updated_at = now()
WHERE id = $1
`

type UpdateProjectMarkupsParams struct {
	ID              string  `json:"id"`
	MaterialsMarkup float64 `json:"materials_markup"`
	LaborMarkup     float64 `json:"labor_markup"`
	EquipmentMarkup float64 `json:"equipment_markup"`
	SubsMarkup      float64 `json:"subs_markup"`
	OtherMarkup     float64 `json:"other_markup"`
}

func (q *Queries) UpdateProjectMarkups(ctx context.Context, arg UpdateProjectMarkupsParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectMarkups,
		arg.ID,
		arg.MaterialsMarkup,
		arg.LaborMarkup,
		arg.EquipmentMarkup,
		arg.SubsMarkup,
		arg.OtherMarkup,
	)
	return err
}
