// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: estimate_builder.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createComponentGroup = `-- name: CreateComponentGroup :one
INSERT INTO component_groups (id, org_id, subcategory_id, name, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, subcategory_id, name, sort_order
`

type CreateComponentGroupParams struct {
	ID            string        `json:"id"`
	OrgID         uuid.NullUUID `json:"org_id"`
	SubcategoryID string        `json:"subcategory_id"`
	Name          string        `json:"name"`
	SortOrder     int64         `json:"sort_order"`
}

func (q *Queries) CreateComponentGroup(ctx context.Context, arg CreateComponentGroupParams) (ComponentGroup, error) {
	row := q.db.QueryRowContext(ctx, createComponentGroup,
		arg.ID,
		arg.OrgID,
		arg.SubcategoryID,
		arg.Name,
		arg.SortOrder,
	)
	var i ComponentGroup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SubcategoryID,
		&i.Name,
		&i.SortOrder,
	)
	return i, err
}

const createEstimateLineItem = `-- name: CreateEstimateLineItem :one
INSERT INTO estimate_line_items (
    id, org_id, subcategory_id, component_group_id, category_type,
    item_name, quantity, unit, unit_price,
    is_custom, material_id, price_override, description, sort_order
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14
)
RETURNING id, org_id, subcategory_id, component_group_id, category_type, item_name, quantity, unit, unit_price, is_custom, material_id, price_override, description, sort_order
`

type CreateEstimateLineItemParams struct {
	ID               string         `json:"id"`
	OrgID            uuid.NullUUID  `json:"org_id"`
	SubcategoryID    string         `json:"subcategory_id"`
	ComponentGroupID sql.NullString `json:"component_group_id"`
	CategoryType     string         `json:"category_type"`
	ItemName         string         `json:"item_name"`
	Quantity         float64        `json:"quantity"`
	Unit             string         `json:"unit"`
	UnitPrice        float64        `json:"unit_price"`
	IsCustom         bool           `json:"is_custom"`
	MaterialID       sql.NullInt32  `json:"material_id"`
	PriceOverride    bool           `json:"price_override"`
	Description      sql.NullString `json:"description"`
	SortOrder        int64          `json:"sort_order"`
}

func (q *Queries) CreateEstimateLineItem(ctx context.Context, arg CreateEstimateLineItemParams) (EstimateLineItem, error) {
	row := q.db.QueryRowContext(ctx, createEstimateLineItem,
		arg.ID,
		arg.OrgID,
		arg.SubcategoryID,
		arg.ComponentGroupID,
		arg.CategoryType,
		arg.ItemName,
		arg.Quantity,
		arg.Unit,
		arg.UnitPrice,
		arg.IsCustom,
		arg.MaterialID,
		arg.PriceOverride,
		arg.Description,
		arg.SortOrder,
	)
	var i EstimateLineItem
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SubcategoryID,
		&i.ComponentGroupID,
		&i.CategoryType,
		&i.ItemName,
		&i.Quantity,
		&i.Unit,
		&i.UnitPrice,
		&i.IsCustom,
		&i.MaterialID,
		&i.PriceOverride,
		&i.Description,
		&i.SortOrder,
	)
	return i, err
}

const createSection = `-- name: CreateSection :one
INSERT INTO sections (id, org_id, job_id, name, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, job_id, name, sort_order
`

type CreateSectionParams struct {
	ID        string        `json:"id"`
	OrgID     uuid.NullUUID `json:"org_id"`
	JobID     string        `json:"job_id"`
	Name      string        `json:"name"`
	SortOrder int64         `json:"sort_order"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error) {
	row := q.db.QueryRowContext(ctx, createSection,
		arg.ID,
		arg.OrgID,
		arg.JobID,
		arg.Name,
		arg.SortOrder,
	)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.Name,
		&i.SortOrder,
	)
	return i, err
}

const createSubcategory = `-- name: CreateSubcategory :one
INSERT INTO subcategories (
    id, org_id, section_id, name, sort_order, lump_sum,
    materials_markup, labor_markup, equipment_markup, subs_markup, other_markup,
    materials_markup_enabled, labor_markup_enabled, equipment_markup_enabled,
    subs_markup_enabled, other_markup_enabled
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16
)
RETURNING id, org_id, section_id, name, sort_order, lump_sum, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup, materials_markup_enabled, labor_markup_enabled, equipment_markup_enabled, subs_markup_enabled, other_markup_enabled
`

type CreateSubcategoryParams struct {
	ID                     string          `json:"id"`
	OrgID                  uuid.NullUUID   `json:"org_id"`
	SectionID              string          `json:"section_id"`
	Name                   string          `json:"name"`
	SortOrder              int64           `json:"sort_order"`
	LumpSum                float64         `json:"lump_sum"`
	MaterialsMarkup        sql.NullFloat64 `json:"materials_markup"`
	LaborMarkup            sql.NullFloat64 `json:"labor_markup"`
	EquipmentMarkup        sql.NullFloat64 `json:"equipment_markup"`
	SubsMarkup             sql.NullFloat64 `json:"subs_markup"`
	OtherMarkup            sql.NullFloat64 `json:"other_markup"`
	MaterialsMarkupEnabled bool            `json:"materials_markup_enabled"`
	LaborMarkupEnabled     bool            `json:"labor_markup_enabled"`
	EquipmentMarkupEnabled bool            `json:"equipment_markup_enabled"`
	SubsMarkupEnabled      bool            `json:"subs_markup_enabled"`
	OtherMarkupEnabled     bool            `json:"other_markup_enabled"`
}

func (q *Queries) CreateSubcategory(ctx context.Context, arg CreateSubcategoryParams) (Subcategory, error) {
	row := q.db.QueryRowContext(ctx, createSubcategory,
		arg.ID,
		arg.OrgID,
		arg.SectionID,
		arg.Name,
		arg.SortOrder,
		arg.LumpSum,
		arg.MaterialsMarkup,
		arg.LaborMarkup,
		arg.EquipmentMarkup,
		arg.SubsMarkup,
		arg.OtherMarkup,
		arg.MaterialsMarkupEnabled,
		arg.LaborMarkupEnabled,
		arg.EquipmentMarkupEnabled,
		arg.SubsMarkupEnabled,
		arg.OtherMarkupEnabled,
	)
	var i Subcategory
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SectionID,
		&i.Name,
		&i.SortOrder,
		&i.LumpSum,
		&i.MaterialsMarkup,
		&i.LaborMarkup,
		&i.EquipmentMarkup,
		&i.SubsMarkup,
		&i.OtherMarkup,
		&i.MaterialsMarkupEnabled,
		&i.LaborMarkupEnabled,
		&i.EquipmentMarkupEnabled,
		&i.SubsMarkupEnabled,
		&i.OtherMarkupEnabled,
	)
	return i, err
}

const deleteSectionsByJob = `-- name: DeleteSectionsByJob :exec
DELETE FROM sections
WHERE job_id = $1 AND org_id = $2
`

type DeleteSectionsByJobParams struct {
	JobID string        `json:"job_id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) DeleteSectionsByJob(ctx context.Context, arg DeleteSectionsByJobParams) error {
	_, err := q.db.ExecContext(ctx, deleteSectionsByJob, arg.JobID, arg.OrgID)
	return err
}

const getJobMarkupGlobals = `-- name: GetJobMarkupGlobals :one

SELECT id, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup
FROM jobs
WHERE id = $1 AND org_id = $2
`

type GetJobMarkupGlobalsParams struct {
	ID    string        `json:"id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

type GetJobMarkupGlobalsRow struct {
	ID              string  `json:"id"`
	MaterialsMarkup float64 `json:"materials_markup"`
	LaborMarkup     float64 `json:"labor_markup"`
	EquipmentMarkup float64 `json:"equipment_markup"`
	SubsMarkup      float64 `json:"subs_markup"`
	OtherMarkup     float64 `json:"other_markup"`
}

// =====================
// Job markup globals
// =====================
func (q *Queries) GetJobMarkupGlobals(ctx context.Context, arg GetJobMarkupGlobalsParams) (GetJobMarkupGlobalsRow, error) {
	row := q.db.QueryRowContext(ctx, getJobMarkupGlobals, arg.ID, arg.OrgID)
	var i GetJobMarkupGlobalsRow
	err := row.Scan(
		&i.ID,
		&i.MaterialsMarkup,
		&i.LaborMarkup,
		&i.EquipmentMarkup,
		&i.SubsMarkup,
		&i.OtherMarkup,
	)
	return i, err
}

const listComponentGroupsByJob = `-- name: ListComponentGroupsByJob :many

SELECT cg.id, cg.org_id, cg.subcategory_id, cg.name, cg.sort_order FROM component_groups cg
JOIN subcategories sc ON cg.subcategory_id = sc.id
JOIN sections s ON sc.section_id = s.id
WHERE s.job_id = $1 AND cg.org_id = $2
ORDER BY cg.sort_order ASC
`

type ListComponentGroupsByJobParams struct {
	JobID string        `json:"job_id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

// =====================
// Component Groups
// =====================
func (q *Queries) ListComponentGroupsByJob(ctx context.Context, arg ListComponentGroupsByJobParams) ([]ComponentGroup, error) {
	rows, err := q.db.QueryContext(ctx, listComponentGroupsByJob, arg.JobID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComponentGroup{}
	for rows.Next() {
		var i ComponentGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SubcategoryID,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEstimateLineItemsByJob = `-- name: ListEstimateLineItemsByJob :many

SELECT eli.id, eli.org_id, eli.subcategory_id, eli.component_group_id, eli.category_type, eli.item_name, eli.quantity, eli.unit, eli.unit_price, eli.is_custom, eli.material_id, eli.price_override, eli.description, eli.sort_order FROM estimate_line_items eli
JOIN subcategories sc ON eli.subcategory_id = sc.id
JOIN sections s ON sc.section_id = s.id
WHERE s.job_id = $1 AND eli.org_id = $2
ORDER BY eli.sort_order ASC
`

type ListEstimateLineItemsByJobParams struct {
	JobID string        `json:"job_id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

// =====================
// Estimate Line Items
// =====================
func (q *Queries) ListEstimateLineItemsByJob(ctx context.Context, arg ListEstimateLineItemsByJobParams) ([]EstimateLineItem, error) {
	rows, err := q.db.QueryContext(ctx, listEstimateLineItemsByJob, arg.JobID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EstimateLineItem{}
	for rows.Next() {
		var i EstimateLineItem
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SubcategoryID,
			&i.ComponentGroupID,
			&i.CategoryType,
			&i.ItemName,
			&i.Quantity,
			&i.Unit,
			&i.UnitPrice,
			&i.IsCustom,
			&i.MaterialID,
			&i.PriceOverride,
			&i.Description,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByJob = `-- name: ListSectionsByJob :many


SELECT id, org_id, job_id, name, sort_order FROM sections
WHERE job_id = $1 AND org_id = $2
ORDER BY sort_order ASC
`

type ListSectionsByJobParams struct {
	JobID string        `json:"job_id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

// Estimate Builder queries for the 4-level hierarchy
// =====================
// Sections
// =====================
func (q *Queries) ListSectionsByJob(ctx context.Context, arg ListSectionsByJobParams) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, listSectionsByJob, arg.JobID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Section{}
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.JobID,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubcategoriesByJob = `-- name: ListSubcategoriesByJob :many

SELECT sc.id, sc.org_id, sc.section_id, sc.name, sc.sort_order, sc.lump_sum, sc.materials_markup, sc.labor_markup, sc.equipment_markup, sc.subs_markup, sc.other_markup, sc.materials_markup_enabled, sc.labor_markup_enabled, sc.equipment_markup_enabled, sc.subs_markup_enabled, sc.other_markup_enabled FROM subcategories sc
JOIN sections s ON sc.section_id = s.id
WHERE s.job_id = $1 AND sc.org_id = $2
ORDER BY sc.sort_order ASC
`

type ListSubcategoriesByJobParams struct {
	JobID string        `json:"job_id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

// =====================
// Subcategories
// =====================
func (q *Queries) ListSubcategoriesByJob(ctx context.Context, arg ListSubcategoriesByJobParams) ([]Subcategory, error) {
	rows, err := q.db.QueryContext(ctx, listSubcategoriesByJob, arg.JobID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subcategory{}
	for rows.Next() {
		var i Subcategory
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SectionID,
			&i.Name,
			&i.SortOrder,
			&i.LumpSum,
			&i.MaterialsMarkup,
			&i.LaborMarkup,
			&i.EquipmentMarkup,
			&i.SubsMarkup,
			&i.OtherMarkup,
			&i.MaterialsMarkupEnabled,
			&i.LaborMarkupEnabled,
			&i.EquipmentMarkupEnabled,
			&i.SubsMarkupEnabled,
			&i.OtherMarkupEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobMarkupGlobals = `-- name: UpdateJobMarkupGlobals :exec
UPDATE jobs SET
    materials_markup = $1,
    labor_markup = $2,
    equipment_markup = $3,
    subs_markup = $4,
    other_markup = $5
WHERE id = $6 AND org_id = $7
`

type UpdateJobMarkupGlobalsParams struct {
	MaterialsMarkup float64       `json:"materials_markup"`
	LaborMarkup     float64       `json:"labor_markup"`
	EquipmentMarkup float64       `json:"equipment_markup"`
	SubsMarkup      float64       `json:"subs_markup"`
	OtherMarkup     float64       `json:"other_markup"`
	ID              string        `json:"id"`
	OrgID           uuid.NullUUID `json:"org_id"`
}

func (q *Queries) UpdateJobMarkupGlobals(ctx context.Context, arg UpdateJobMarkupGlobalsParams) error {
	_, err := q.db.ExecContext(ctx, updateJobMarkupGlobals,
		arg.MaterialsMarkup,
		arg.LaborMarkup,
		arg.EquipmentMarkup,
		arg.SubsMarkup,
		arg.OtherMarkup,
		arg.ID,
		arg.OrgID,
	)
	return err
}
