// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_templates.sql

package repository

import (
	"context"
	"database/sql"
)

const createItemTemplate = `-- name: CreateItemTemplate :one
INSERT INTO item_templates (type, category, name, default_unit, default_price)
VALUES (?, ?, ?, ?, ?)
RETURNING id, type, category, name, default_unit, default_price
`

type CreateItemTemplateParams struct {
	Type         string  `json:"type"`
	Category     string  `json:"category"`
	Name         string  `json:"name"`
	DefaultUnit  string  `json:"default_unit"`
	DefaultPrice float64 `json:"default_price"`
}

func (q *Queries) CreateItemTemplate(ctx context.Context, arg CreateItemTemplateParams) (ItemTemplate, error) {
	row := q.db.QueryRowContext(ctx, createItemTemplate,
		arg.Type,
		arg.Category,
		arg.Name,
		arg.DefaultUnit,
		arg.DefaultPrice,
	)
	var i ItemTemplate
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Category,
		&i.Name,
		&i.DefaultUnit,
		&i.DefaultPrice,
	)
	return i, err
}

const deleteItemTemplate = `-- name: DeleteItemTemplate :exec
DELETE FROM item_templates
WHERE id = ?
`

func (q *Queries) DeleteItemTemplate(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteItemTemplate, id)
	return err
}

const getItemTemplate = `-- name: GetItemTemplate :one
SELECT id, type, category, name, default_unit, default_price FROM item_templates
WHERE id = ?
`

func (q *Queries) GetItemTemplate(ctx context.Context, id int64) (ItemTemplate, error) {
	row := q.db.QueryRowContext(ctx, getItemTemplate, id)
	var i ItemTemplate
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Category,
		&i.Name,
		&i.DefaultUnit,
		&i.DefaultPrice,
	)
	return i, err
}

const listItemTemplates = `-- name: ListItemTemplates :many
SELECT id, type, category, name, default_unit, default_price FROM item_templates
ORDER BY category, name
`

func (q *Queries) ListItemTemplates(ctx context.Context) ([]ItemTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listItemTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemTemplate{}
	for rows.Next() {
		var i ItemTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Category,
			&i.Name,
			&i.DefaultUnit,
			&i.DefaultPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemTemplatesByCategory = `-- name: ListItemTemplatesByCategory :many
SELECT id, type, category, name, default_unit, default_price FROM item_templates
WHERE category = ?
ORDER BY name
`

func (q *Queries) ListItemTemplatesByCategory(ctx context.Context, category string) ([]ItemTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listItemTemplatesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemTemplate{}
	for rows.Next() {
		var i ItemTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Category,
			&i.Name,
			&i.DefaultUnit,
			&i.DefaultPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItemTemplates = `-- name: SearchItemTemplates :many
SELECT id, type, category, name, default_unit, default_price FROM item_templates
WHERE name LIKE '%' || ? || '%'
ORDER BY name
LIMIT 10
`

func (q *Queries) SearchItemTemplates(ctx context.Context, dollar_1 sql.NullString) ([]ItemTemplate, error) {
	rows, err := q.db.QueryContext(ctx, searchItemTemplates, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemTemplate{}
	for rows.Next() {
		var i ItemTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Category,
			&i.Name,
			&i.DefaultUnit,
			&i.DefaultPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItemTemplatesByType = `-- name: SearchItemTemplatesByType :many
SELECT id, type, category, name, default_unit, default_price FROM item_templates
WHERE type = ? AND name LIKE '%' || ? || '%'
ORDER BY name
LIMIT 10
`

type SearchItemTemplatesByTypeParams struct {
	Type    string         `json:"type"`
	Column2 sql.NullString `json:"column_2"`
}

func (q *Queries) SearchItemTemplatesByType(ctx context.Context, arg SearchItemTemplatesByTypeParams) ([]ItemTemplate, error) {
	rows, err := q.db.QueryContext(ctx, searchItemTemplatesByType, arg.Type, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemTemplate{}
	for rows.Next() {
		var i ItemTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Category,
			&i.Name,
			&i.DefaultUnit,
			&i.DefaultPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemTemplate = `-- name: UpdateItemTemplate :one
UPDATE item_templates
SET type = ?, category = ?, name = ?, default_unit = ?, default_price = ?
WHERE id = ?
RETURNING id, type, category, name, default_unit, default_price
`

type UpdateItemTemplateParams struct {
	Type         string  `json:"type"`
	Category     string  `json:"category"`
	Name         string  `json:"name"`
	DefaultUnit  string  `json:"default_unit"`
	DefaultPrice float64 `json:"default_price"`
	ID           int64   `json:"id"`
}

func (q *Queries) UpdateItemTemplate(ctx context.Context, arg UpdateItemTemplateParams) (ItemTemplate, error) {
	row := q.db.QueryRowContext(ctx, updateItemTemplate,
		arg.Type,
		arg.Category,
		arg.Name,
		arg.DefaultUnit,
		arg.DefaultPrice,
		arg.ID,
	)
	var i ItemTemplate
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Category,
		&i.Name,
		&i.DefaultUnit,
		&i.DefaultPrice,
	)
	return i, err
}
