// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_templates.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const bulkUpdateItemTemplateSubcategory = `-- name: BulkUpdateItemTemplateSubcategory :exec
UPDATE item_templates SET subcategory = $1
WHERE id = ANY($3::bigint[]) AND org_id = $2
`

type BulkUpdateItemTemplateSubcategoryParams struct {
	Subcategory sql.NullString `json:"subcategory"`
	OrgID       uuid.NullUUID  `json:"org_id"`
	Ids         []int64        `json:"ids"`
}

func (q *Queries) BulkUpdateItemTemplateSubcategory(ctx context.Context, arg BulkUpdateItemTemplateSubcategoryParams) error {
	_, err := q.db.ExecContext(ctx, bulkUpdateItemTemplateSubcategory, arg.Subcategory, arg.OrgID, pq.Array(arg.Ids))
	return err
}

const createItemTemplate = `-- name: CreateItemTemplate :one
INSERT INTO item_templates (org_id, type, category, name, default_unit, default_price, subcategory)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, type, category, name, default_unit, default_price, org_id, subcategory
`

type CreateItemTemplateParams struct {
	OrgID        uuid.NullUUID  `json:"org_id"`
	Type         string         `json:"type"`
	Category     string         `json:"category"`
	Name         string         `json:"name"`
	DefaultUnit  string         `json:"default_unit"`
	DefaultPrice float64        `json:"default_price"`
	Subcategory  sql.NullString `json:"subcategory"`
}

func (q *Queries) CreateItemTemplate(ctx context.Context, arg CreateItemTemplateParams) (ItemTemplate, error) {
	row := q.db.QueryRowContext(ctx, createItemTemplate,
		arg.OrgID,
		arg.Type,
		arg.Category,
		arg.Name,
		arg.DefaultUnit,
		arg.DefaultPrice,
		arg.Subcategory,
	)
	var i ItemTemplate
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Category,
		&i.Name,
		&i.DefaultUnit,
		&i.DefaultPrice,
		&i.OrgID,
		&i.Subcategory,
	)
	return i, err
}

const deleteItemTemplate = `-- name: DeleteItemTemplate :exec
DELETE FROM item_templates
WHERE id = $1 AND org_id = $2
`

type DeleteItemTemplateParams struct {
	ID    int64         `json:"id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) DeleteItemTemplate(ctx context.Context, arg DeleteItemTemplateParams) error {
	_, err := q.db.ExecContext(ctx, deleteItemTemplate, arg.ID, arg.OrgID)
	return err
}

const getItemTemplate = `-- name: GetItemTemplate :one
SELECT id, type, category, name, default_unit, default_price, org_id, subcategory FROM item_templates
WHERE id = $1 AND org_id = $2
`

type GetItemTemplateParams struct {
	ID    int64         `json:"id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) GetItemTemplate(ctx context.Context, arg GetItemTemplateParams) (ItemTemplate, error) {
	row := q.db.QueryRowContext(ctx, getItemTemplate, arg.ID, arg.OrgID)
	var i ItemTemplate
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Category,
		&i.Name,
		&i.DefaultUnit,
		&i.DefaultPrice,
		&i.OrgID,
		&i.Subcategory,
	)
	return i, err
}

const listItemTemplateCategories = `-- name: ListItemTemplateCategories :many
SELECT DISTINCT category FROM item_templates
WHERE (org_id = $1 OR org_id IS NULL)
ORDER BY category
`

func (q *Queries) ListItemTemplateCategories(ctx context.Context, orgID uuid.NullUUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listItemTemplateCategories, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemTemplateSubcategories = `-- name: ListItemTemplateSubcategories :many
SELECT subcategory, COUNT(*)::bigint as item_count FROM item_templates
WHERE (org_id = $1 OR org_id IS NULL) AND category = $2
GROUP BY subcategory
ORDER BY subcategory
`

type ListItemTemplateSubcategoriesParams struct {
	OrgID    uuid.NullUUID `json:"org_id"`
	Category string        `json:"category"`
}

type ListItemTemplateSubcategoriesRow struct {
	Subcategory sql.NullString `json:"subcategory"`
	ItemCount   int64          `json:"item_count"`
}

func (q *Queries) ListItemTemplateSubcategories(ctx context.Context, arg ListItemTemplateSubcategoriesParams) ([]ListItemTemplateSubcategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemTemplateSubcategories, arg.OrgID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemTemplateSubcategoriesRow{}
	for rows.Next() {
		var i ListItemTemplateSubcategoriesRow
		if err := rows.Scan(&i.Subcategory, &i.ItemCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemTemplates = `-- name: ListItemTemplates :many
SELECT id, type, category, name, default_unit, default_price, org_id, subcategory FROM item_templates
WHERE (org_id = $1 OR org_id IS NULL)
ORDER BY category, name
`

func (q *Queries) ListItemTemplates(ctx context.Context, orgID uuid.NullUUID) ([]ItemTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listItemTemplates, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemTemplate{}
	for rows.Next() {
		var i ItemTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Category,
			&i.Name,
			&i.DefaultUnit,
			&i.DefaultPrice,
			&i.OrgID,
			&i.Subcategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemTemplatesByCategory = `-- name: ListItemTemplatesByCategory :many
SELECT id, type, category, name, default_unit, default_price, org_id, subcategory FROM item_templates
WHERE (org_id = $1 OR org_id IS NULL) AND category = $2
ORDER BY name
`

type ListItemTemplatesByCategoryParams struct {
	OrgID    uuid.NullUUID `json:"org_id"`
	Category string        `json:"category"`
}

func (q *Queries) ListItemTemplatesByCategory(ctx context.Context, arg ListItemTemplatesByCategoryParams) ([]ItemTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listItemTemplatesByCategory, arg.OrgID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemTemplate{}
	for rows.Next() {
		var i ItemTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Category,
			&i.Name,
			&i.DefaultUnit,
			&i.DefaultPrice,
			&i.OrgID,
			&i.Subcategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemTemplatesBySubcategory = `-- name: ListItemTemplatesBySubcategory :many
SELECT id, type, category, name, default_unit, default_price, org_id, subcategory FROM item_templates
WHERE (org_id = $1 OR org_id IS NULL) AND category = $2 AND subcategory = $3
ORDER BY name
`

type ListItemTemplatesBySubcategoryParams struct {
	OrgID       uuid.NullUUID  `json:"org_id"`
	Category    string         `json:"category"`
	Subcategory sql.NullString `json:"subcategory"`
}

func (q *Queries) ListItemTemplatesBySubcategory(ctx context.Context, arg ListItemTemplatesBySubcategoryParams) ([]ItemTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listItemTemplatesBySubcategory, arg.OrgID, arg.Category, arg.Subcategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemTemplate{}
	for rows.Next() {
		var i ItemTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Category,
			&i.Name,
			&i.DefaultUnit,
			&i.DefaultPrice,
			&i.OrgID,
			&i.Subcategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItemTemplates = `-- name: SearchItemTemplates :many
SELECT id, type, category, name, default_unit, default_price, org_id, subcategory FROM item_templates
WHERE (org_id = $1 OR org_id IS NULL) AND (name ILIKE '%' || $2 || '%' OR category ILIKE '%' || $2 || '%')
ORDER BY name
LIMIT 20
`

type SearchItemTemplatesParams struct {
	OrgID   uuid.NullUUID  `json:"org_id"`
	Column2 sql.NullString `json:"column_2"`
}

func (q *Queries) SearchItemTemplates(ctx context.Context, arg SearchItemTemplatesParams) ([]ItemTemplate, error) {
	rows, err := q.db.QueryContext(ctx, searchItemTemplates, arg.OrgID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemTemplate{}
	for rows.Next() {
		var i ItemTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Category,
			&i.Name,
			&i.DefaultUnit,
			&i.DefaultPrice,
			&i.OrgID,
			&i.Subcategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItemTemplatesByType = `-- name: SearchItemTemplatesByType :many
SELECT id, type, category, name, default_unit, default_price, org_id, subcategory FROM item_templates
WHERE (org_id = $1 OR org_id IS NULL) AND type = $2 AND (name ILIKE '%' || $3 || '%' OR category ILIKE '%' || $3 || '%')
ORDER BY name
LIMIT 20
`

type SearchItemTemplatesByTypeParams struct {
	OrgID   uuid.NullUUID  `json:"org_id"`
	Type    string         `json:"type"`
	Column3 sql.NullString `json:"column_3"`
}

func (q *Queries) SearchItemTemplatesByType(ctx context.Context, arg SearchItemTemplatesByTypeParams) ([]ItemTemplate, error) {
	rows, err := q.db.QueryContext(ctx, searchItemTemplatesByType, arg.OrgID, arg.Type, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemTemplate{}
	for rows.Next() {
		var i ItemTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Category,
			&i.Name,
			&i.DefaultUnit,
			&i.DefaultPrice,
			&i.OrgID,
			&i.Subcategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemTemplate = `-- name: UpdateItemTemplate :one
UPDATE item_templates
SET type = $1, category = $2, name = $3, default_unit = $4, default_price = $5, subcategory = $6
WHERE id = $7 AND org_id = $8
RETURNING id, type, category, name, default_unit, default_price, org_id, subcategory
`

type UpdateItemTemplateParams struct {
	Type         string         `json:"type"`
	Category     string         `json:"category"`
	Name         string         `json:"name"`
	DefaultUnit  string         `json:"default_unit"`
	DefaultPrice float64        `json:"default_price"`
	Subcategory  sql.NullString `json:"subcategory"`
	ID           int64          `json:"id"`
	OrgID        uuid.NullUUID  `json:"org_id"`
}

func (q *Queries) UpdateItemTemplate(ctx context.Context, arg UpdateItemTemplateParams) (ItemTemplate, error) {
	row := q.db.QueryRowContext(ctx, updateItemTemplate,
		arg.Type,
		arg.Category,
		arg.Name,
		arg.DefaultUnit,
		arg.DefaultPrice,
		arg.Subcategory,
		arg.ID,
		arg.OrgID,
	)
	var i ItemTemplate
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Category,
		&i.Name,
		&i.DefaultUnit,
		&i.DefaultPrice,
		&i.OrgID,
		&i.Subcategory,
	)
	return i, err
}

const updateItemTemplatePrice = `-- name: UpdateItemTemplatePrice :exec
UPDATE item_templates SET default_price = $1 WHERE id = $2 AND org_id = $3
`

type UpdateItemTemplatePriceParams struct {
	DefaultPrice float64       `json:"default_price"`
	ID           int64         `json:"id"`
	OrgID        uuid.NullUUID `json:"org_id"`
}

func (q *Queries) UpdateItemTemplatePrice(ctx context.Context, arg UpdateItemTemplatePriceParams) error {
	_, err := q.db.ExecContext(ctx, updateItemTemplatePrice, arg.DefaultPrice, arg.ID, arg.OrgID)
	return err
}

const updateItemTemplatePriceAndName = `-- name: UpdateItemTemplatePriceAndName :exec
UPDATE item_templates SET default_price = $1, name = $2 WHERE id = $3 AND org_id = $4
`

type UpdateItemTemplatePriceAndNameParams struct {
	DefaultPrice float64       `json:"default_price"`
	Name         string        `json:"name"`
	ID           int64         `json:"id"`
	OrgID        uuid.NullUUID `json:"org_id"`
}

func (q *Queries) UpdateItemTemplatePriceAndName(ctx context.Context, arg UpdateItemTemplatePriceAndNameParams) error {
	_, err := q.db.ExecContext(ctx, updateItemTemplatePriceAndName,
		arg.DefaultPrice,
		arg.Name,
		arg.ID,
		arg.OrgID,
	)
	return err
}
