// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_templates.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createItemTemplate = `-- name: CreateItemTemplate :one
INSERT INTO item_templates (org_id, type, category, name, default_unit, default_price)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, type, category, name, default_unit, default_price, org_id
`

type CreateItemTemplateParams struct {
	OrgID        uuid.NullUUID `json:"org_id"`
	Type         string        `json:"type"`
	Category     string        `json:"category"`
	Name         string        `json:"name"`
	DefaultUnit  string        `json:"default_unit"`
	DefaultPrice float64       `json:"default_price"`
}

func (q *Queries) CreateItemTemplate(ctx context.Context, arg CreateItemTemplateParams) (ItemTemplate, error) {
	row := q.db.QueryRowContext(ctx, createItemTemplate,
		arg.OrgID,
		arg.Type,
		arg.Category,
		arg.Name,
		arg.DefaultUnit,
		arg.DefaultPrice,
	)
	var i ItemTemplate
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Category,
		&i.Name,
		&i.DefaultUnit,
		&i.DefaultPrice,
		&i.OrgID,
	)
	return i, err
}

const deleteItemTemplate = `-- name: DeleteItemTemplate :exec
DELETE FROM item_templates
WHERE id = $1 AND org_id = $2
`

type DeleteItemTemplateParams struct {
	ID    int64         `json:"id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) DeleteItemTemplate(ctx context.Context, arg DeleteItemTemplateParams) error {
	_, err := q.db.ExecContext(ctx, deleteItemTemplate, arg.ID, arg.OrgID)
	return err
}

const getItemTemplate = `-- name: GetItemTemplate :one
SELECT id, type, category, name, default_unit, default_price, org_id FROM item_templates
WHERE id = $1 AND org_id = $2
`

type GetItemTemplateParams struct {
	ID    int64         `json:"id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) GetItemTemplate(ctx context.Context, arg GetItemTemplateParams) (ItemTemplate, error) {
	row := q.db.QueryRowContext(ctx, getItemTemplate, arg.ID, arg.OrgID)
	var i ItemTemplate
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Category,
		&i.Name,
		&i.DefaultUnit,
		&i.DefaultPrice,
		&i.OrgID,
	)
	return i, err
}

const listItemTemplateCategories = `-- name: ListItemTemplateCategories :many
SELECT DISTINCT category FROM item_templates
WHERE org_id = $1
ORDER BY category
`

func (q *Queries) ListItemTemplateCategories(ctx context.Context, orgID uuid.NullUUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listItemTemplateCategories, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemTemplates = `-- name: ListItemTemplates :many
SELECT id, type, category, name, default_unit, default_price, org_id FROM item_templates
WHERE org_id = $1
ORDER BY category, name
`

func (q *Queries) ListItemTemplates(ctx context.Context, orgID uuid.NullUUID) ([]ItemTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listItemTemplates, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemTemplate{}
	for rows.Next() {
		var i ItemTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Category,
			&i.Name,
			&i.DefaultUnit,
			&i.DefaultPrice,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemTemplatesByCategory = `-- name: ListItemTemplatesByCategory :many
SELECT id, type, category, name, default_unit, default_price, org_id FROM item_templates
WHERE org_id = $1 AND category = $2
ORDER BY name
`

type ListItemTemplatesByCategoryParams struct {
	OrgID    uuid.NullUUID `json:"org_id"`
	Category string        `json:"category"`
}

func (q *Queries) ListItemTemplatesByCategory(ctx context.Context, arg ListItemTemplatesByCategoryParams) ([]ItemTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listItemTemplatesByCategory, arg.OrgID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemTemplate{}
	for rows.Next() {
		var i ItemTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Category,
			&i.Name,
			&i.DefaultUnit,
			&i.DefaultPrice,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItemTemplates = `-- name: SearchItemTemplates :many
SELECT id, type, category, name, default_unit, default_price, org_id FROM item_templates
WHERE org_id = $1 AND name LIKE '%' || $2 || '%'
ORDER BY name
LIMIT 10
`

type SearchItemTemplatesParams struct {
	OrgID   uuid.NullUUID  `json:"org_id"`
	Column2 sql.NullString `json:"column_2"`
}

func (q *Queries) SearchItemTemplates(ctx context.Context, arg SearchItemTemplatesParams) ([]ItemTemplate, error) {
	rows, err := q.db.QueryContext(ctx, searchItemTemplates, arg.OrgID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemTemplate{}
	for rows.Next() {
		var i ItemTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Category,
			&i.Name,
			&i.DefaultUnit,
			&i.DefaultPrice,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItemTemplatesByType = `-- name: SearchItemTemplatesByType :many
SELECT id, type, category, name, default_unit, default_price, org_id FROM item_templates
WHERE org_id = $1 AND type = $2 AND name LIKE '%' || $3 || '%'
ORDER BY name
LIMIT 10
`

type SearchItemTemplatesByTypeParams struct {
	OrgID   uuid.NullUUID  `json:"org_id"`
	Type    string         `json:"type"`
	Column3 sql.NullString `json:"column_3"`
}

func (q *Queries) SearchItemTemplatesByType(ctx context.Context, arg SearchItemTemplatesByTypeParams) ([]ItemTemplate, error) {
	rows, err := q.db.QueryContext(ctx, searchItemTemplatesByType, arg.OrgID, arg.Type, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemTemplate{}
	for rows.Next() {
		var i ItemTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Category,
			&i.Name,
			&i.DefaultUnit,
			&i.DefaultPrice,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemTemplate = `-- name: UpdateItemTemplate :one
UPDATE item_templates
SET type = $1, category = $2, name = $3, default_unit = $4, default_price = $5
WHERE id = $6 AND org_id = $7
RETURNING id, type, category, name, default_unit, default_price, org_id
`

type UpdateItemTemplateParams struct {
	Type         string        `json:"type"`
	Category     string        `json:"category"`
	Name         string        `json:"name"`
	DefaultUnit  string        `json:"default_unit"`
	DefaultPrice float64       `json:"default_price"`
	ID           int64         `json:"id"`
	OrgID        uuid.NullUUID `json:"org_id"`
}

func (q *Queries) UpdateItemTemplate(ctx context.Context, arg UpdateItemTemplateParams) (ItemTemplate, error) {
	row := q.db.QueryRowContext(ctx, updateItemTemplate,
		arg.Type,
		arg.Category,
		arg.Name,
		arg.DefaultUnit,
		arg.DefaultPrice,
		arg.ID,
		arg.OrgID,
	)
	var i ItemTemplate
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Category,
		&i.Name,
		&i.DefaultUnit,
		&i.DefaultPrice,
		&i.OrgID,
	)
	return i, err
}

const updateItemTemplatePrice = `-- name: UpdateItemTemplatePrice :exec
UPDATE item_templates SET default_price = $1 WHERE id = $2 AND org_id = $3
`

type UpdateItemTemplatePriceParams struct {
	DefaultPrice float64       `json:"default_price"`
	ID           int64         `json:"id"`
	OrgID        uuid.NullUUID `json:"org_id"`
}

func (q *Queries) UpdateItemTemplatePrice(ctx context.Context, arg UpdateItemTemplatePriceParams) error {
	_, err := q.db.ExecContext(ctx, updateItemTemplatePrice, arg.DefaultPrice, arg.ID, arg.OrgID)
	return err
}

const updateItemTemplatePriceAndName = `-- name: UpdateItemTemplatePriceAndName :exec
UPDATE item_templates SET default_price = $1, name = $2 WHERE id = $3 AND org_id = $4
`

type UpdateItemTemplatePriceAndNameParams struct {
	DefaultPrice float64       `json:"default_price"`
	Name         string        `json:"name"`
	ID           int64         `json:"id"`
	OrgID        uuid.NullUUID `json:"org_id"`
}

func (q *Queries) UpdateItemTemplatePriceAndName(ctx context.Context, arg UpdateItemTemplatePriceAndNameParams) error {
	_, err := q.db.ExecContext(ctx, updateItemTemplatePriceAndName,
		arg.DefaultPrice,
		arg.Name,
		arg.ID,
		arg.OrgID,
	)
	return err
}
