// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_item_types.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countLineItemsByType = `-- name: CountLineItemsByType :one
SELECT COUNT(*) FROM line_items li
JOIN categories c ON li.category_id = c.id
WHERE c.job_id = $1 AND c.org_id = $2 AND li.type = $3 AND li.org_id = $2
`

type CountLineItemsByTypeParams struct {
	JobID string        `json:"job_id"`
	OrgID uuid.NullUUID `json:"org_id"`
	Type  string        `json:"type"`
}

func (q *Queries) CountLineItemsByType(ctx context.Context, arg CountLineItemsByTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLineItemsByType, arg.JobID, arg.OrgID, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJobItemType = `-- name: CreateJobItemType :one
INSERT INTO job_item_types (id, org_id, job_id, name, slug, color, sort_order, surcharge_percent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, job_id, name, slug, color, sort_order, created_at, surcharge_percent, org_id
`

type CreateJobItemTypeParams struct {
	ID               string          `json:"id"`
	OrgID            uuid.NullUUID   `json:"org_id"`
	JobID            string          `json:"job_id"`
	Name             string          `json:"name"`
	Slug             string          `json:"slug"`
	Color            string          `json:"color"`
	SortOrder        int64           `json:"sort_order"`
	SurchargePercent sql.NullFloat64 `json:"surcharge_percent"`
}

func (q *Queries) CreateJobItemType(ctx context.Context, arg CreateJobItemTypeParams) (JobItemType, error) {
	row := q.db.QueryRowContext(ctx, createJobItemType,
		arg.ID,
		arg.OrgID,
		arg.JobID,
		arg.Name,
		arg.Slug,
		arg.Color,
		arg.SortOrder,
		arg.SurchargePercent,
	)
	var i JobItemType
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.SurchargePercent,
		&i.OrgID,
	)
	return i, err
}

const deleteJobItemType = `-- name: DeleteJobItemType :exec
DELETE FROM job_item_types WHERE id = $1 AND org_id = $2
`

type DeleteJobItemTypeParams struct {
	ID    string        `json:"id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) DeleteJobItemType(ctx context.Context, arg DeleteJobItemTypeParams) error {
	_, err := q.db.ExecContext(ctx, deleteJobItemType, arg.ID, arg.OrgID)
	return err
}

const getJobItemType = `-- name: GetJobItemType :one
SELECT id, job_id, name, slug, color, sort_order, created_at, surcharge_percent, org_id FROM job_item_types WHERE id = $1 AND org_id = $2
`

type GetJobItemTypeParams struct {
	ID    string        `json:"id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) GetJobItemType(ctx context.Context, arg GetJobItemTypeParams) (JobItemType, error) {
	row := q.db.QueryRowContext(ctx, getJobItemType, arg.ID, arg.OrgID)
	var i JobItemType
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.SurchargePercent,
		&i.OrgID,
	)
	return i, err
}

const getJobItemTypeBySlug = `-- name: GetJobItemTypeBySlug :one
SELECT id, job_id, name, slug, color, sort_order, created_at, surcharge_percent, org_id FROM job_item_types
WHERE job_id = $1 AND org_id = $2 AND slug = $3
`

type GetJobItemTypeBySlugParams struct {
	JobID string        `json:"job_id"`
	OrgID uuid.NullUUID `json:"org_id"`
	Slug  string        `json:"slug"`
}

func (q *Queries) GetJobItemTypeBySlug(ctx context.Context, arg GetJobItemTypeBySlugParams) (JobItemType, error) {
	row := q.db.QueryRowContext(ctx, getJobItemTypeBySlug, arg.JobID, arg.OrgID, arg.Slug)
	var i JobItemType
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.SurchargePercent,
		&i.OrgID,
	)
	return i, err
}

const listJobItemTypes = `-- name: ListJobItemTypes :many
SELECT id, job_id, name, slug, color, sort_order, created_at, surcharge_percent, org_id FROM job_item_types
WHERE job_id = $1 AND org_id = $2
ORDER BY sort_order ASC, name ASC
`

type ListJobItemTypesParams struct {
	JobID string        `json:"job_id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) ListJobItemTypes(ctx context.Context, arg ListJobItemTypesParams) ([]JobItemType, error) {
	rows, err := q.db.QueryContext(ctx, listJobItemTypes, arg.JobID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobItemType{}
	for rows.Next() {
		var i JobItemType
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.SortOrder,
			&i.CreatedAt,
			&i.SurchargePercent,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobItemType = `-- name: UpdateJobItemType :one
UPDATE job_item_types SET
    name = $1,
    slug = $2,
    color = $3,
    sort_order = $4,
    surcharge_percent = $5
WHERE id = $6 AND org_id = $7
RETURNING id, job_id, name, slug, color, sort_order, created_at, surcharge_percent, org_id
`

type UpdateJobItemTypeParams struct {
	Name             string          `json:"name"`
	Slug             string          `json:"slug"`
	Color            string          `json:"color"`
	SortOrder        int64           `json:"sort_order"`
	SurchargePercent sql.NullFloat64 `json:"surcharge_percent"`
	ID               string          `json:"id"`
	OrgID            uuid.NullUUID   `json:"org_id"`
}

func (q *Queries) UpdateJobItemType(ctx context.Context, arg UpdateJobItemTypeParams) (JobItemType, error) {
	row := q.db.QueryRowContext(ctx, updateJobItemType,
		arg.Name,
		arg.Slug,
		arg.Color,
		arg.SortOrder,
		arg.SurchargePercent,
		arg.ID,
		arg.OrgID,
	)
	var i JobItemType
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.SurchargePercent,
		&i.OrgID,
	)
	return i, err
}
