// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package repository

import (
	"context"
	"database/sql"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (id, name, customer_name, surcharge_percent, surcharge_mode)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, customer_name, surcharge_percent, surcharge_mode, created_at
`

type CreateJobParams struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	CustomerName     sql.NullString `json:"customer_name"`
	SurchargePercent float64        `json:"surcharge_percent"`
	SurchargeMode    string         `json:"surcharge_mode"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.ID,
		arg.Name,
		arg.CustomerName,
		arg.SurchargePercent,
		arg.SurchargeMode,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerName,
		&i.SurchargePercent,
		&i.SurchargeMode,
		&i.CreatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = ?
`

func (q *Queries) DeleteJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, name, customer_name, surcharge_percent, surcharge_mode, created_at FROM jobs
WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerName,
		&i.SurchargePercent,
		&i.SurchargeMode,
		&i.CreatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, name, customer_name, surcharge_percent, surcharge_mode, created_at FROM jobs
ORDER BY created_at DESC
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerName,
			&i.SurchargePercent,
			&i.SurchargeMode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs SET
    name = ?,
    customer_name = ?,
    surcharge_percent = ?,
    surcharge_mode = ?
WHERE id = ?
RETURNING id, name, customer_name, surcharge_percent, surcharge_mode, created_at
`

type UpdateJobParams struct {
	Name             string         `json:"name"`
	CustomerName     sql.NullString `json:"customer_name"`
	SurchargePercent float64        `json:"surcharge_percent"`
	SurchargeMode    string         `json:"surcharge_mode"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJob,
		arg.Name,
		arg.CustomerName,
		arg.SurchargePercent,
		arg.SurchargeMode,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerName,
		&i.SurchargePercent,
		&i.SurchargeMode,
		&i.CreatedAt,
	)
	return i, err
}
