// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countJobs = `-- name: CountJobs :one
SELECT COUNT(*) FROM jobs
WHERE org_id = $1
  AND ($2 = '' OR status = $2)
`

type CountJobsParams struct {
	OrgID  uuid.NullUUID `json:"org_id"`
	Status interface{}   `json:"status"`
}

func (q *Queries) CountJobs(ctx context.Context, arg CountJobsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobs, arg.OrgID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (id, org_id, name, customer_name, surcharge_percent, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent, surcharge_mode, status, expires_at, client_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent, org_id, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup
`

type CreateJobParams struct {
	ID                        string          `json:"id"`
	OrgID                     uuid.NullUUID   `json:"org_id"`
	Name                      string          `json:"name"`
	CustomerName              sql.NullString  `json:"customer_name"`
	SurchargePercent          float64         `json:"surcharge_percent"`
	MaterialSurchargePercent  sql.NullFloat64 `json:"material_surcharge_percent"`
	LaborSurchargePercent     sql.NullFloat64 `json:"labor_surcharge_percent"`
	EquipmentSurchargePercent sql.NullFloat64 `json:"equipment_surcharge_percent"`
	SurchargeMode             string          `json:"surcharge_mode"`
	Status                    string          `json:"status"`
	ExpiresAt                 sql.NullString  `json:"expires_at"`
	ClientID                  sql.NullString  `json:"client_id"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.CustomerName,
		arg.SurchargePercent,
		arg.MaterialSurchargePercent,
		arg.LaborSurchargePercent,
		arg.EquipmentSurchargePercent,
		arg.SurchargeMode,
		arg.Status,
		arg.ExpiresAt,
		arg.ClientID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerName,
		&i.SurchargePercent,
		&i.SurchargeMode,
		&i.CreatedAt,
		&i.Status,
		&i.ExpiresAt,
		&i.ClientID,
		&i.MaterialSurchargePercent,
		&i.LaborSurchargePercent,
		&i.EquipmentSurchargePercent,
		&i.OrgID,
		&i.MaterialsMarkup,
		&i.LaborMarkup,
		&i.EquipmentMarkup,
		&i.SubsMarkup,
		&i.OtherMarkup,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1 AND org_id = $2
`

type DeleteJobParams struct {
	ID    string        `json:"id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) DeleteJob(ctx context.Context, arg DeleteJobParams) error {
	_, err := q.db.ExecContext(ctx, deleteJob, arg.ID, arg.OrgID)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent, org_id, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup FROM jobs
WHERE id = $1 AND org_id = $2
`

type GetJobParams struct {
	ID    string        `json:"id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, arg.ID, arg.OrgID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerName,
		&i.SurchargePercent,
		&i.SurchargeMode,
		&i.CreatedAt,
		&i.Status,
		&i.ExpiresAt,
		&i.ClientID,
		&i.MaterialSurchargePercent,
		&i.LaborSurchargePercent,
		&i.EquipmentSurchargePercent,
		&i.OrgID,
		&i.MaterialsMarkup,
		&i.LaborMarkup,
		&i.EquipmentMarkup,
		&i.SubsMarkup,
		&i.OtherMarkup,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent, org_id, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup FROM jobs
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListJobs(ctx context.Context, orgID uuid.NullUUID) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerName,
			&i.SurchargePercent,
			&i.SurchargeMode,
			&i.CreatedAt,
			&i.Status,
			&i.ExpiresAt,
			&i.ClientID,
			&i.MaterialSurchargePercent,
			&i.LaborSurchargePercent,
			&i.EquipmentSurchargePercent,
			&i.OrgID,
			&i.MaterialsMarkup,
			&i.LaborMarkup,
			&i.EquipmentMarkup,
			&i.SubsMarkup,
			&i.OtherMarkup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByClientWithEstimateStatus = `-- name: ListJobsByClientWithEstimateStatus :many
SELECT
    j.id, j.name, j.customer_name, j.surcharge_percent, j.surcharge_mode, j.created_at, j.status, j.expires_at, j.client_id, j.material_surcharge_percent, j.labor_surcharge_percent, j.equipment_surcharge_percent, j.org_id, j.materials_markup, j.labor_markup, j.equipment_markup, j.subs_markup, j.other_markup,
    (SELECT COUNT(*) FROM estimates WHERE job_id = j.id AND org_id = j.org_id) as estimate_count,
    (SELECT status FROM estimates WHERE job_id = j.id AND org_id = j.org_id ORDER BY version DESC LIMIT 1) as latest_estimate_status,
    (SELECT sr.status FROM signature_requests sr
     INNER JOIN estimates e ON sr.estimate_id = e.id
     WHERE e.job_id = j.id AND sr.org_id = j.org_id
     ORDER BY sr.created_at DESC LIMIT 1) as latest_signature_status
FROM jobs j
WHERE j.client_id = $1 AND j.org_id = $2
ORDER BY j.created_at DESC
`

type ListJobsByClientWithEstimateStatusParams struct {
	ClientID sql.NullString `json:"client_id"`
	OrgID    uuid.NullUUID  `json:"org_id"`
}

type ListJobsByClientWithEstimateStatusRow struct {
	ID                        string          `json:"id"`
	Name                      string          `json:"name"`
	CustomerName              sql.NullString  `json:"customer_name"`
	SurchargePercent          float64         `json:"surcharge_percent"`
	SurchargeMode             string          `json:"surcharge_mode"`
	CreatedAt                 string          `json:"created_at"`
	Status                    string          `json:"status"`
	ExpiresAt                 sql.NullString  `json:"expires_at"`
	ClientID                  sql.NullString  `json:"client_id"`
	MaterialSurchargePercent  sql.NullFloat64 `json:"material_surcharge_percent"`
	LaborSurchargePercent     sql.NullFloat64 `json:"labor_surcharge_percent"`
	EquipmentSurchargePercent sql.NullFloat64 `json:"equipment_surcharge_percent"`
	OrgID                     uuid.NullUUID   `json:"org_id"`
	MaterialsMarkup           float64         `json:"materials_markup"`
	LaborMarkup               float64         `json:"labor_markup"`
	EquipmentMarkup           float64         `json:"equipment_markup"`
	SubsMarkup                float64         `json:"subs_markup"`
	OtherMarkup               float64         `json:"other_markup"`
	EstimateCount             int64           `json:"estimate_count"`
	LatestEstimateStatus      string          `json:"latest_estimate_status"`
	LatestSignatureStatus     string          `json:"latest_signature_status"`
}

func (q *Queries) ListJobsByClientWithEstimateStatus(ctx context.Context, arg ListJobsByClientWithEstimateStatusParams) ([]ListJobsByClientWithEstimateStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByClientWithEstimateStatus, arg.ClientID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsByClientWithEstimateStatusRow{}
	for rows.Next() {
		var i ListJobsByClientWithEstimateStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerName,
			&i.SurchargePercent,
			&i.SurchargeMode,
			&i.CreatedAt,
			&i.Status,
			&i.ExpiresAt,
			&i.ClientID,
			&i.MaterialSurchargePercent,
			&i.LaborSurchargePercent,
			&i.EquipmentSurchargePercent,
			&i.OrgID,
			&i.MaterialsMarkup,
			&i.LaborMarkup,
			&i.EquipmentMarkup,
			&i.SubsMarkup,
			&i.OtherMarkup,
			&i.EstimateCount,
			&i.LatestEstimateStatus,
			&i.LatestSignatureStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsPaginated = `-- name: ListJobsPaginated :many
SELECT id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent, org_id, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup FROM jobs
WHERE org_id = $1
  AND ($2 = '' OR status = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListJobsPaginatedParams struct {
	OrgID  uuid.NullUUID `json:"org_id"`
	Status interface{}   `json:"status"`
	Offset int32         `json:"offset"`
	Limit  int32         `json:"limit"`
}

func (q *Queries) ListJobsPaginated(ctx context.Context, arg ListJobsPaginatedParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsPaginated,
		arg.OrgID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerName,
			&i.SurchargePercent,
			&i.SurchargeMode,
			&i.CreatedAt,
			&i.Status,
			&i.ExpiresAt,
			&i.ClientID,
			&i.MaterialSurchargePercent,
			&i.LaborSurchargePercent,
			&i.EquipmentSurchargePercent,
			&i.OrgID,
			&i.MaterialsMarkup,
			&i.LaborMarkup,
			&i.EquipmentMarkup,
			&i.SubsMarkup,
			&i.OtherMarkup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsPaginatedByName = `-- name: ListJobsPaginatedByName :many
SELECT id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent, org_id, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup FROM jobs
WHERE org_id = $1
  AND ($2 = '' OR status = $2)
ORDER BY name ASC
LIMIT $4 OFFSET $3
`

type ListJobsPaginatedByNameParams struct {
	OrgID  uuid.NullUUID `json:"org_id"`
	Status interface{}   `json:"status"`
	Offset int32         `json:"offset"`
	Limit  int32         `json:"limit"`
}

func (q *Queries) ListJobsPaginatedByName(ctx context.Context, arg ListJobsPaginatedByNameParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsPaginatedByName,
		arg.OrgID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerName,
			&i.SurchargePercent,
			&i.SurchargeMode,
			&i.CreatedAt,
			&i.Status,
			&i.ExpiresAt,
			&i.ClientID,
			&i.MaterialSurchargePercent,
			&i.LaborSurchargePercent,
			&i.EquipmentSurchargePercent,
			&i.OrgID,
			&i.MaterialsMarkup,
			&i.LaborMarkup,
			&i.EquipmentMarkup,
			&i.SubsMarkup,
			&i.OtherMarkup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsPaginatedByNameDesc = `-- name: ListJobsPaginatedByNameDesc :many
SELECT id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent, org_id, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup FROM jobs
WHERE org_id = $1
  AND ($2 = '' OR status = $2)
ORDER BY name DESC
LIMIT $4 OFFSET $3
`

type ListJobsPaginatedByNameDescParams struct {
	OrgID  uuid.NullUUID `json:"org_id"`
	Status interface{}   `json:"status"`
	Offset int32         `json:"offset"`
	Limit  int32         `json:"limit"`
}

func (q *Queries) ListJobsPaginatedByNameDesc(ctx context.Context, arg ListJobsPaginatedByNameDescParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsPaginatedByNameDesc,
		arg.OrgID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerName,
			&i.SurchargePercent,
			&i.SurchargeMode,
			&i.CreatedAt,
			&i.Status,
			&i.ExpiresAt,
			&i.ClientID,
			&i.MaterialSurchargePercent,
			&i.LaborSurchargePercent,
			&i.EquipmentSurchargePercent,
			&i.OrgID,
			&i.MaterialsMarkup,
			&i.LaborMarkup,
			&i.EquipmentMarkup,
			&i.SubsMarkup,
			&i.OtherMarkup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsPaginatedOldest = `-- name: ListJobsPaginatedOldest :many
SELECT id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent, org_id, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup FROM jobs
WHERE org_id = $1
  AND ($2 = '' OR status = $2)
ORDER BY created_at ASC
LIMIT $4 OFFSET $3
`

type ListJobsPaginatedOldestParams struct {
	OrgID  uuid.NullUUID `json:"org_id"`
	Status interface{}   `json:"status"`
	Offset int32         `json:"offset"`
	Limit  int32         `json:"limit"`
}

func (q *Queries) ListJobsPaginatedOldest(ctx context.Context, arg ListJobsPaginatedOldestParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsPaginatedOldest,
		arg.OrgID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerName,
			&i.SurchargePercent,
			&i.SurchargeMode,
			&i.CreatedAt,
			&i.Status,
			&i.ExpiresAt,
			&i.ClientID,
			&i.MaterialSurchargePercent,
			&i.LaborSurchargePercent,
			&i.EquipmentSurchargePercent,
			&i.OrgID,
			&i.MaterialsMarkup,
			&i.LaborMarkup,
			&i.EquipmentMarkup,
			&i.SubsMarkup,
			&i.OtherMarkup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsWithEstimateStatus = `-- name: ListJobsWithEstimateStatus :many
SELECT
    j.id, j.name, j.customer_name, j.surcharge_percent, j.surcharge_mode, j.created_at, j.status, j.expires_at, j.client_id, j.material_surcharge_percent, j.labor_surcharge_percent, j.equipment_surcharge_percent, j.org_id, j.materials_markup, j.labor_markup, j.equipment_markup, j.subs_markup, j.other_markup,
    (SELECT COUNT(*) FROM estimates WHERE job_id = j.id AND org_id = j.org_id) as estimate_count,
    (SELECT status FROM estimates WHERE job_id = j.id AND org_id = j.org_id ORDER BY version DESC LIMIT 1) as latest_estimate_status,
    (SELECT sr.status FROM signature_requests sr
     INNER JOIN estimates e ON sr.estimate_id = e.id
     WHERE e.job_id = j.id AND sr.org_id = j.org_id
     ORDER BY sr.created_at DESC LIMIT 1) as latest_signature_status
FROM jobs j
WHERE j.org_id = $1
  AND ($2 = '' OR j.status = $2)
ORDER BY j.created_at DESC
LIMIT $4 OFFSET $3
`

type ListJobsWithEstimateStatusParams struct {
	OrgID  uuid.NullUUID `json:"org_id"`
	Status interface{}   `json:"status"`
	Offset int32         `json:"offset"`
	Limit  int32         `json:"limit"`
}

type ListJobsWithEstimateStatusRow struct {
	ID                        string          `json:"id"`
	Name                      string          `json:"name"`
	CustomerName              sql.NullString  `json:"customer_name"`
	SurchargePercent          float64         `json:"surcharge_percent"`
	SurchargeMode             string          `json:"surcharge_mode"`
	CreatedAt                 string          `json:"created_at"`
	Status                    string          `json:"status"`
	ExpiresAt                 sql.NullString  `json:"expires_at"`
	ClientID                  sql.NullString  `json:"client_id"`
	MaterialSurchargePercent  sql.NullFloat64 `json:"material_surcharge_percent"`
	LaborSurchargePercent     sql.NullFloat64 `json:"labor_surcharge_percent"`
	EquipmentSurchargePercent sql.NullFloat64 `json:"equipment_surcharge_percent"`
	OrgID                     uuid.NullUUID   `json:"org_id"`
	MaterialsMarkup           float64         `json:"materials_markup"`
	LaborMarkup               float64         `json:"labor_markup"`
	EquipmentMarkup           float64         `json:"equipment_markup"`
	SubsMarkup                float64         `json:"subs_markup"`
	OtherMarkup               float64         `json:"other_markup"`
	EstimateCount             int64           `json:"estimate_count"`
	LatestEstimateStatus      string          `json:"latest_estimate_status"`
	LatestSignatureStatus     string          `json:"latest_signature_status"`
}

func (q *Queries) ListJobsWithEstimateStatus(ctx context.Context, arg ListJobsWithEstimateStatusParams) ([]ListJobsWithEstimateStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobsWithEstimateStatus,
		arg.OrgID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsWithEstimateStatusRow{}
	for rows.Next() {
		var i ListJobsWithEstimateStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerName,
			&i.SurchargePercent,
			&i.SurchargeMode,
			&i.CreatedAt,
			&i.Status,
			&i.ExpiresAt,
			&i.ClientID,
			&i.MaterialSurchargePercent,
			&i.LaborSurchargePercent,
			&i.EquipmentSurchargePercent,
			&i.OrgID,
			&i.MaterialsMarkup,
			&i.LaborMarkup,
			&i.EquipmentMarkup,
			&i.SubsMarkup,
			&i.OtherMarkup,
			&i.EstimateCount,
			&i.LatestEstimateStatus,
			&i.LatestSignatureStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs SET
    name = $1,
    customer_name = $2,
    surcharge_percent = $3,
    material_surcharge_percent = $4,
    labor_surcharge_percent = $5,
    equipment_surcharge_percent = $6,
    surcharge_mode = $7,
    status = $8,
    expires_at = $9,
    client_id = $10
WHERE id = $11 AND org_id = $12
RETURNING id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent, org_id, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup
`

type UpdateJobParams struct {
	Name                      string          `json:"name"`
	CustomerName              sql.NullString  `json:"customer_name"`
	SurchargePercent          float64         `json:"surcharge_percent"`
	MaterialSurchargePercent  sql.NullFloat64 `json:"material_surcharge_percent"`
	LaborSurchargePercent     sql.NullFloat64 `json:"labor_surcharge_percent"`
	EquipmentSurchargePercent sql.NullFloat64 `json:"equipment_surcharge_percent"`
	SurchargeMode             string          `json:"surcharge_mode"`
	Status                    string          `json:"status"`
	ExpiresAt                 sql.NullString  `json:"expires_at"`
	ClientID                  sql.NullString  `json:"client_id"`
	ID                        string          `json:"id"`
	OrgID                     uuid.NullUUID   `json:"org_id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJob,
		arg.Name,
		arg.CustomerName,
		arg.SurchargePercent,
		arg.MaterialSurchargePercent,
		arg.LaborSurchargePercent,
		arg.EquipmentSurchargePercent,
		arg.SurchargeMode,
		arg.Status,
		arg.ExpiresAt,
		arg.ClientID,
		arg.ID,
		arg.OrgID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerName,
		&i.SurchargePercent,
		&i.SurchargeMode,
		&i.CreatedAt,
		&i.Status,
		&i.ExpiresAt,
		&i.ClientID,
		&i.MaterialSurchargePercent,
		&i.LaborSurchargePercent,
		&i.EquipmentSurchargePercent,
		&i.OrgID,
		&i.MaterialsMarkup,
		&i.LaborMarkup,
		&i.EquipmentMarkup,
		&i.SubsMarkup,
		&i.OtherMarkup,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs SET status = $1 WHERE id = $2 AND org_id = $3 RETURNING id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent, org_id, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup
`

type UpdateJobStatusParams struct {
	Status string        `json:"status"`
	ID     string        `json:"id"`
	OrgID  uuid.NullUUID `json:"org_id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJobStatus, arg.Status, arg.ID, arg.OrgID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerName,
		&i.SurchargePercent,
		&i.SurchargeMode,
		&i.CreatedAt,
		&i.Status,
		&i.ExpiresAt,
		&i.ClientID,
		&i.MaterialSurchargePercent,
		&i.LaborSurchargePercent,
		&i.EquipmentSurchargePercent,
		&i.OrgID,
		&i.MaterialsMarkup,
		&i.LaborMarkup,
		&i.EquipmentMarkup,
		&i.SubsMarkup,
		&i.OtherMarkup,
	)
	return i, err
}
