// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package repository

import (
	"context"
	"database/sql"
)

const countJobs = `-- name: CountJobs :one
SELECT COUNT(*) FROM jobs
WHERE (?1 = '' OR status = ?1)
`

func (q *Queries) CountJobs(ctx context.Context, status interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobs, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (id, name, customer_name, surcharge_percent, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent, surcharge_mode, status, expires_at, client_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent
`

type CreateJobParams struct {
	ID                        string          `json:"id"`
	Name                      string          `json:"name"`
	CustomerName              sql.NullString  `json:"customer_name"`
	SurchargePercent          float64         `json:"surcharge_percent"`
	MaterialSurchargePercent  sql.NullFloat64 `json:"material_surcharge_percent"`
	LaborSurchargePercent     sql.NullFloat64 `json:"labor_surcharge_percent"`
	EquipmentSurchargePercent sql.NullFloat64 `json:"equipment_surcharge_percent"`
	SurchargeMode             string          `json:"surcharge_mode"`
	Status                    string          `json:"status"`
	ExpiresAt                 sql.NullString  `json:"expires_at"`
	ClientID                  sql.NullString  `json:"client_id"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.ID,
		arg.Name,
		arg.CustomerName,
		arg.SurchargePercent,
		arg.MaterialSurchargePercent,
		arg.LaborSurchargePercent,
		arg.EquipmentSurchargePercent,
		arg.SurchargeMode,
		arg.Status,
		arg.ExpiresAt,
		arg.ClientID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerName,
		&i.SurchargePercent,
		&i.SurchargeMode,
		&i.CreatedAt,
		&i.Status,
		&i.ExpiresAt,
		&i.ClientID,
		&i.MaterialSurchargePercent,
		&i.LaborSurchargePercent,
		&i.EquipmentSurchargePercent,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = ?
`

func (q *Queries) DeleteJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent FROM jobs
WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerName,
		&i.SurchargePercent,
		&i.SurchargeMode,
		&i.CreatedAt,
		&i.Status,
		&i.ExpiresAt,
		&i.ClientID,
		&i.MaterialSurchargePercent,
		&i.LaborSurchargePercent,
		&i.EquipmentSurchargePercent,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent FROM jobs
ORDER BY created_at DESC
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerName,
			&i.SurchargePercent,
			&i.SurchargeMode,
			&i.CreatedAt,
			&i.Status,
			&i.ExpiresAt,
			&i.ClientID,
			&i.MaterialSurchargePercent,
			&i.LaborSurchargePercent,
			&i.EquipmentSurchargePercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByClientWithEstimateStatus = `-- name: ListJobsByClientWithEstimateStatus :many
SELECT
    j.id, j.name, j.customer_name, j.surcharge_percent, j.surcharge_mode, j.created_at, j.status, j.expires_at, j.client_id, j.material_surcharge_percent, j.labor_surcharge_percent, j.equipment_surcharge_percent,
    (SELECT COUNT(*) FROM estimates WHERE job_id = j.id) as estimate_count,
    (SELECT status FROM estimates WHERE job_id = j.id ORDER BY version DESC LIMIT 1) as latest_estimate_status,
    (SELECT sr.status FROM signature_requests sr
     INNER JOIN estimates e ON sr.estimate_id = e.id
     WHERE e.job_id = j.id
     ORDER BY sr.created_at DESC LIMIT 1) as latest_signature_status
FROM jobs j
WHERE j.client_id = ?
ORDER BY j.created_at DESC
`

type ListJobsByClientWithEstimateStatusRow struct {
	ID                        string          `json:"id"`
	Name                      string          `json:"name"`
	CustomerName              sql.NullString  `json:"customer_name"`
	SurchargePercent          float64         `json:"surcharge_percent"`
	SurchargeMode             string          `json:"surcharge_mode"`
	CreatedAt                 string          `json:"created_at"`
	Status                    string          `json:"status"`
	ExpiresAt                 sql.NullString  `json:"expires_at"`
	ClientID                  sql.NullString  `json:"client_id"`
	MaterialSurchargePercent  sql.NullFloat64 `json:"material_surcharge_percent"`
	LaborSurchargePercent     sql.NullFloat64 `json:"labor_surcharge_percent"`
	EquipmentSurchargePercent sql.NullFloat64 `json:"equipment_surcharge_percent"`
	EstimateCount             int64           `json:"estimate_count"`
	LatestEstimateStatus      string          `json:"latest_estimate_status"`
	LatestSignatureStatus     string          `json:"latest_signature_status"`
}

func (q *Queries) ListJobsByClientWithEstimateStatus(ctx context.Context, clientID sql.NullString) ([]ListJobsByClientWithEstimateStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByClientWithEstimateStatus, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsByClientWithEstimateStatusRow{}
	for rows.Next() {
		var i ListJobsByClientWithEstimateStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerName,
			&i.SurchargePercent,
			&i.SurchargeMode,
			&i.CreatedAt,
			&i.Status,
			&i.ExpiresAt,
			&i.ClientID,
			&i.MaterialSurchargePercent,
			&i.LaborSurchargePercent,
			&i.EquipmentSurchargePercent,
			&i.EstimateCount,
			&i.LatestEstimateStatus,
			&i.LatestSignatureStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsPaginated = `-- name: ListJobsPaginated :many
SELECT id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent FROM jobs
WHERE (?1 = '' OR status = ?1)
ORDER BY created_at DESC
LIMIT ?3 OFFSET ?2
`

type ListJobsPaginatedParams struct {
	Status interface{} `json:"status"`
	Offset int64       `json:"offset"`
	Limit  int64       `json:"limit"`
}

func (q *Queries) ListJobsPaginated(ctx context.Context, arg ListJobsPaginatedParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsPaginated, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerName,
			&i.SurchargePercent,
			&i.SurchargeMode,
			&i.CreatedAt,
			&i.Status,
			&i.ExpiresAt,
			&i.ClientID,
			&i.MaterialSurchargePercent,
			&i.LaborSurchargePercent,
			&i.EquipmentSurchargePercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsPaginatedByName = `-- name: ListJobsPaginatedByName :many
SELECT id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent FROM jobs
WHERE (?1 = '' OR status = ?1)
ORDER BY name ASC
LIMIT ?3 OFFSET ?2
`

type ListJobsPaginatedByNameParams struct {
	Status interface{} `json:"status"`
	Offset int64       `json:"offset"`
	Limit  int64       `json:"limit"`
}

func (q *Queries) ListJobsPaginatedByName(ctx context.Context, arg ListJobsPaginatedByNameParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsPaginatedByName, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerName,
			&i.SurchargePercent,
			&i.SurchargeMode,
			&i.CreatedAt,
			&i.Status,
			&i.ExpiresAt,
			&i.ClientID,
			&i.MaterialSurchargePercent,
			&i.LaborSurchargePercent,
			&i.EquipmentSurchargePercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsPaginatedByNameDesc = `-- name: ListJobsPaginatedByNameDesc :many
SELECT id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent FROM jobs
WHERE (?1 = '' OR status = ?1)
ORDER BY name DESC
LIMIT ?3 OFFSET ?2
`

type ListJobsPaginatedByNameDescParams struct {
	Status interface{} `json:"status"`
	Offset int64       `json:"offset"`
	Limit  int64       `json:"limit"`
}

func (q *Queries) ListJobsPaginatedByNameDesc(ctx context.Context, arg ListJobsPaginatedByNameDescParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsPaginatedByNameDesc, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerName,
			&i.SurchargePercent,
			&i.SurchargeMode,
			&i.CreatedAt,
			&i.Status,
			&i.ExpiresAt,
			&i.ClientID,
			&i.MaterialSurchargePercent,
			&i.LaborSurchargePercent,
			&i.EquipmentSurchargePercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsPaginatedOldest = `-- name: ListJobsPaginatedOldest :many
SELECT id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent FROM jobs
WHERE (?1 = '' OR status = ?1)
ORDER BY created_at ASC
LIMIT ?3 OFFSET ?2
`

type ListJobsPaginatedOldestParams struct {
	Status interface{} `json:"status"`
	Offset int64       `json:"offset"`
	Limit  int64       `json:"limit"`
}

func (q *Queries) ListJobsPaginatedOldest(ctx context.Context, arg ListJobsPaginatedOldestParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsPaginatedOldest, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerName,
			&i.SurchargePercent,
			&i.SurchargeMode,
			&i.CreatedAt,
			&i.Status,
			&i.ExpiresAt,
			&i.ClientID,
			&i.MaterialSurchargePercent,
			&i.LaborSurchargePercent,
			&i.EquipmentSurchargePercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsWithEstimateStatus = `-- name: ListJobsWithEstimateStatus :many
SELECT
    j.id, j.name, j.customer_name, j.surcharge_percent, j.surcharge_mode, j.created_at, j.status, j.expires_at, j.client_id, j.material_surcharge_percent, j.labor_surcharge_percent, j.equipment_surcharge_percent,
    (SELECT COUNT(*) FROM estimates WHERE job_id = j.id) as estimate_count,
    (SELECT status FROM estimates WHERE job_id = j.id ORDER BY version DESC LIMIT 1) as latest_estimate_status,
    (SELECT sr.status FROM signature_requests sr
     INNER JOIN estimates e ON sr.estimate_id = e.id
     WHERE e.job_id = j.id
     ORDER BY sr.created_at DESC LIMIT 1) as latest_signature_status
FROM jobs j
WHERE (?1 = '' OR j.status = ?1)
ORDER BY j.created_at DESC
LIMIT ?3 OFFSET ?2
`

type ListJobsWithEstimateStatusParams struct {
	Status interface{} `json:"status"`
	Offset int64       `json:"offset"`
	Limit  int64       `json:"limit"`
}

type ListJobsWithEstimateStatusRow struct {
	ID                        string          `json:"id"`
	Name                      string          `json:"name"`
	CustomerName              sql.NullString  `json:"customer_name"`
	SurchargePercent          float64         `json:"surcharge_percent"`
	SurchargeMode             string          `json:"surcharge_mode"`
	CreatedAt                 string          `json:"created_at"`
	Status                    string          `json:"status"`
	ExpiresAt                 sql.NullString  `json:"expires_at"`
	ClientID                  sql.NullString  `json:"client_id"`
	MaterialSurchargePercent  sql.NullFloat64 `json:"material_surcharge_percent"`
	LaborSurchargePercent     sql.NullFloat64 `json:"labor_surcharge_percent"`
	EquipmentSurchargePercent sql.NullFloat64 `json:"equipment_surcharge_percent"`
	EstimateCount             int64           `json:"estimate_count"`
	LatestEstimateStatus      string          `json:"latest_estimate_status"`
	LatestSignatureStatus     string          `json:"latest_signature_status"`
}

func (q *Queries) ListJobsWithEstimateStatus(ctx context.Context, arg ListJobsWithEstimateStatusParams) ([]ListJobsWithEstimateStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobsWithEstimateStatus, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsWithEstimateStatusRow{}
	for rows.Next() {
		var i ListJobsWithEstimateStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerName,
			&i.SurchargePercent,
			&i.SurchargeMode,
			&i.CreatedAt,
			&i.Status,
			&i.ExpiresAt,
			&i.ClientID,
			&i.MaterialSurchargePercent,
			&i.LaborSurchargePercent,
			&i.EquipmentSurchargePercent,
			&i.EstimateCount,
			&i.LatestEstimateStatus,
			&i.LatestSignatureStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs SET
    name = ?,
    customer_name = ?,
    surcharge_percent = ?,
    material_surcharge_percent = ?,
    labor_surcharge_percent = ?,
    equipment_surcharge_percent = ?,
    surcharge_mode = ?,
    status = ?,
    expires_at = ?,
    client_id = ?
WHERE id = ?
RETURNING id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent
`

type UpdateJobParams struct {
	Name                      string          `json:"name"`
	CustomerName              sql.NullString  `json:"customer_name"`
	SurchargePercent          float64         `json:"surcharge_percent"`
	MaterialSurchargePercent  sql.NullFloat64 `json:"material_surcharge_percent"`
	LaborSurchargePercent     sql.NullFloat64 `json:"labor_surcharge_percent"`
	EquipmentSurchargePercent sql.NullFloat64 `json:"equipment_surcharge_percent"`
	SurchargeMode             string          `json:"surcharge_mode"`
	Status                    string          `json:"status"`
	ExpiresAt                 sql.NullString  `json:"expires_at"`
	ClientID                  sql.NullString  `json:"client_id"`
	ID                        string          `json:"id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJob,
		arg.Name,
		arg.CustomerName,
		arg.SurchargePercent,
		arg.MaterialSurchargePercent,
		arg.LaborSurchargePercent,
		arg.EquipmentSurchargePercent,
		arg.SurchargeMode,
		arg.Status,
		arg.ExpiresAt,
		arg.ClientID,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerName,
		&i.SurchargePercent,
		&i.SurchargeMode,
		&i.CreatedAt,
		&i.Status,
		&i.ExpiresAt,
		&i.ClientID,
		&i.MaterialSurchargePercent,
		&i.LaborSurchargePercent,
		&i.EquipmentSurchargePercent,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs SET status = ? WHERE id = ? RETURNING id, name, customer_name, surcharge_percent, surcharge_mode, created_at, status, expires_at, client_id, material_surcharge_percent, labor_surcharge_percent, equipment_surcharge_percent
`

type UpdateJobStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJobStatus, arg.Status, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerName,
		&i.SurchargePercent,
		&i.SurchargeMode,
		&i.CreatedAt,
		&i.Status,
		&i.ExpiresAt,
		&i.ClientID,
		&i.MaterialSurchargePercent,
		&i.LaborSurchargePercent,
		&i.EquipmentSurchargePercent,
	)
	return i, err
}
