// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: line_items.sql

package repository

import (
	"context"
	"database/sql"
)

const createLineItem = `-- name: CreateLineItem :one
INSERT INTO line_items (id, category_id, type, name, description, quantity, unit, unit_price, surcharge_percent, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, category_id, type, name, description, quantity, unit, unit_price, surcharge_percent, sort_order
`

type CreateLineItemParams struct {
	ID               string          `json:"id"`
	CategoryID       string          `json:"category_id"`
	Type             string          `json:"type"`
	Name             string          `json:"name"`
	Description      sql.NullString  `json:"description"`
	Quantity         float64         `json:"quantity"`
	Unit             string          `json:"unit"`
	UnitPrice        float64         `json:"unit_price"`
	SurchargePercent sql.NullFloat64 `json:"surcharge_percent"`
	SortOrder        int64           `json:"sort_order"`
}

func (q *Queries) CreateLineItem(ctx context.Context, arg CreateLineItemParams) (LineItem, error) {
	row := q.db.QueryRowContext(ctx, createLineItem,
		arg.ID,
		arg.CategoryID,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.Quantity,
		arg.Unit,
		arg.UnitPrice,
		arg.SurchargePercent,
		arg.SortOrder,
	)
	var i LineItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.UnitPrice,
		&i.SurchargePercent,
		&i.SortOrder,
	)
	return i, err
}

const deleteLineItem = `-- name: DeleteLineItem :exec
DELETE FROM line_items
WHERE id = ?
`

func (q *Queries) DeleteLineItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLineItem, id)
	return err
}

const getLineItem = `-- name: GetLineItem :one
SELECT id, category_id, type, name, description, quantity, unit, unit_price, surcharge_percent, sort_order FROM line_items
WHERE id = ?
`

func (q *Queries) GetLineItem(ctx context.Context, id string) (LineItem, error) {
	row := q.db.QueryRowContext(ctx, getLineItem, id)
	var i LineItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.UnitPrice,
		&i.SurchargePercent,
		&i.SortOrder,
	)
	return i, err
}

const listLineItemsByCategory = `-- name: ListLineItemsByCategory :many
SELECT id, category_id, type, name, description, quantity, unit, unit_price, surcharge_percent, sort_order FROM line_items
WHERE category_id = ?
ORDER BY sort_order ASC
`

func (q *Queries) ListLineItemsByCategory(ctx context.Context, categoryID string) ([]LineItem, error) {
	rows, err := q.db.QueryContext(ctx, listLineItemsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LineItem{}
	for rows.Next() {
		var i LineItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Unit,
			&i.UnitPrice,
			&i.SurchargePercent,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLineItemsByJob = `-- name: ListLineItemsByJob :many
SELECT li.id, li.category_id, li.type, li.name, li.description, li.quantity, li.unit, li.unit_price, li.surcharge_percent, li.sort_order FROM line_items li
JOIN categories c ON li.category_id = c.id
WHERE c.job_id = ?
ORDER BY li.sort_order ASC
`

func (q *Queries) ListLineItemsByJob(ctx context.Context, jobID string) ([]LineItem, error) {
	rows, err := q.db.QueryContext(ctx, listLineItemsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LineItem{}
	for rows.Next() {
		var i LineItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Unit,
			&i.UnitPrice,
			&i.SurchargePercent,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLineItem = `-- name: UpdateLineItem :one
UPDATE line_items SET
    type = ?,
    name = ?,
    description = ?,
    quantity = ?,
    unit = ?,
    unit_price = ?,
    surcharge_percent = ?,
    sort_order = ?
WHERE id = ?
RETURNING id, category_id, type, name, description, quantity, unit, unit_price, surcharge_percent, sort_order
`

type UpdateLineItemParams struct {
	Type             string          `json:"type"`
	Name             string          `json:"name"`
	Description      sql.NullString  `json:"description"`
	Quantity         float64         `json:"quantity"`
	Unit             string          `json:"unit"`
	UnitPrice        float64         `json:"unit_price"`
	SurchargePercent sql.NullFloat64 `json:"surcharge_percent"`
	SortOrder        int64           `json:"sort_order"`
	ID               string          `json:"id"`
}

func (q *Queries) UpdateLineItem(ctx context.Context, arg UpdateLineItemParams) (LineItem, error) {
	row := q.db.QueryRowContext(ctx, updateLineItem,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.Quantity,
		arg.Unit,
		arg.UnitPrice,
		arg.SurchargePercent,
		arg.SortOrder,
		arg.ID,
	)
	var i LineItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.UnitPrice,
		&i.SurchargePercent,
		&i.SortOrder,
	)
	return i, err
}
