// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: materials.sql

package repository

import (
	"context"
	"database/sql"
)

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO materials (id, name, supplier_id, unit_price, unit, supplier_code, price_source)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, supplier_id, unit_price, unit, supplier_code, price_source, last_updated, created_at
`

type CreateMaterialParams struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	SupplierID   string         `json:"supplier_id"`
	UnitPrice    float64        `json:"unit_price"`
	Unit         string         `json:"unit"`
	SupplierCode sql.NullString `json:"supplier_code"`
	PriceSource  string         `json:"price_source"`
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error) {
	row := q.db.QueryRowContext(ctx, createMaterial,
		arg.ID,
		arg.Name,
		arg.SupplierID,
		arg.UnitPrice,
		arg.Unit,
		arg.SupplierCode,
		arg.PriceSource,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SupplierID,
		&i.UnitPrice,
		&i.Unit,
		&i.SupplierCode,
		&i.PriceSource,
		&i.LastUpdated,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMaterial = `-- name: DeleteMaterial :exec
DELETE FROM materials WHERE id = $1
`

func (q *Queries) DeleteMaterial(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMaterial, id)
	return err
}

const getMaterial = `-- name: GetMaterial :one
SELECT id, name, supplier_id, unit_price, unit, supplier_code, price_source, last_updated, created_at FROM materials WHERE id = $1
`

func (q *Queries) GetMaterial(ctx context.Context, id string) (Material, error) {
	row := q.db.QueryRowContext(ctx, getMaterial, id)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SupplierID,
		&i.UnitPrice,
		&i.Unit,
		&i.SupplierCode,
		&i.PriceSource,
		&i.LastUpdated,
		&i.CreatedAt,
	)
	return i, err
}

const listMaterials = `-- name: ListMaterials :many
SELECT id, name, supplier_id, unit_price, unit, supplier_code, price_source, last_updated, created_at FROM materials ORDER BY name ASC
`

func (q *Queries) ListMaterials(ctx context.Context) ([]Material, error) {
	rows, err := q.db.QueryContext(ctx, listMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Material{}
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SupplierID,
			&i.UnitPrice,
			&i.Unit,
			&i.SupplierCode,
			&i.PriceSource,
			&i.LastUpdated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialsByPriceSource = `-- name: ListMaterialsByPriceSource :many
SELECT id, name, supplier_id, unit_price, unit, supplier_code, price_source, last_updated, created_at FROM materials WHERE price_source = $1 ORDER BY name ASC
`

func (q *Queries) ListMaterialsByPriceSource(ctx context.Context, priceSource string) ([]Material, error) {
	rows, err := q.db.QueryContext(ctx, listMaterialsByPriceSource, priceSource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Material{}
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SupplierID,
			&i.UnitPrice,
			&i.Unit,
			&i.SupplierCode,
			&i.PriceSource,
			&i.LastUpdated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialsBySupplier = `-- name: ListMaterialsBySupplier :many
SELECT id, name, supplier_id, unit_price, unit, supplier_code, price_source, last_updated, created_at FROM materials WHERE supplier_id = $1 ORDER BY name ASC
`

func (q *Queries) ListMaterialsBySupplier(ctx context.Context, supplierID string) ([]Material, error) {
	rows, err := q.db.QueryContext(ctx, listMaterialsBySupplier, supplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Material{}
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SupplierID,
			&i.UnitPrice,
			&i.Unit,
			&i.SupplierCode,
			&i.PriceSource,
			&i.LastUpdated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialsBySupplierAndSource = `-- name: ListMaterialsBySupplierAndSource :many
SELECT id, name, supplier_id, unit_price, unit, supplier_code, price_source, last_updated, created_at FROM materials
WHERE supplier_id = $1 AND price_source = $2
ORDER BY name ASC
`

type ListMaterialsBySupplierAndSourceParams struct {
	SupplierID  string `json:"supplier_id"`
	PriceSource string `json:"price_source"`
}

func (q *Queries) ListMaterialsBySupplierAndSource(ctx context.Context, arg ListMaterialsBySupplierAndSourceParams) ([]Material, error) {
	rows, err := q.db.QueryContext(ctx, listMaterialsBySupplierAndSource, arg.SupplierID, arg.PriceSource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Material{}
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SupplierID,
			&i.UnitPrice,
			&i.Unit,
			&i.SupplierCode,
			&i.PriceSource,
			&i.LastUpdated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMaterials = `-- name: SearchMaterials :many
SELECT id, name, supplier_id, unit_price, unit, supplier_code, price_source, last_updated, created_at FROM materials
WHERE name ILIKE '%' || $1::text || '%'
   OR supplier_code ILIKE '%' || $1::text || '%'
ORDER BY name ASC
`

func (q *Queries) SearchMaterials(ctx context.Context, searchTerm string) ([]Material, error) {
	rows, err := q.db.QueryContext(ctx, searchMaterials, searchTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Material{}
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SupplierID,
			&i.UnitPrice,
			&i.Unit,
			&i.SupplierCode,
			&i.PriceSource,
			&i.LastUpdated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMaterialsBySupplier = `-- name: SearchMaterialsBySupplier :many
SELECT id, name, supplier_id, unit_price, unit, supplier_code, price_source, last_updated, created_at FROM materials
WHERE supplier_id = $1
  AND (name ILIKE '%' || $2::text || '%'
       OR supplier_code ILIKE '%' || $2::text || '%')
ORDER BY name ASC
`

type SearchMaterialsBySupplierParams struct {
	SupplierID string `json:"supplier_id"`
	SearchTerm string `json:"search_term"`
}

func (q *Queries) SearchMaterialsBySupplier(ctx context.Context, arg SearchMaterialsBySupplierParams) ([]Material, error) {
	rows, err := q.db.QueryContext(ctx, searchMaterialsBySupplier, arg.SupplierID, arg.SearchTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Material{}
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SupplierID,
			&i.UnitPrice,
			&i.Unit,
			&i.SupplierCode,
			&i.PriceSource,
			&i.LastUpdated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaterial = `-- name: UpdateMaterial :one
UPDATE materials
SET name = $2, supplier_id = $3, unit_price = $4, unit = $5,
    supplier_code = $6, price_source = $7, last_updated = now()
WHERE id = $1
RETURNING id, name, supplier_id, unit_price, unit, supplier_code, price_source, last_updated, created_at
`

type UpdateMaterialParams struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	SupplierID   string         `json:"supplier_id"`
	UnitPrice    float64        `json:"unit_price"`
	Unit         string         `json:"unit"`
	SupplierCode sql.NullString `json:"supplier_code"`
	PriceSource  string         `json:"price_source"`
}

func (q *Queries) UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) (Material, error) {
	row := q.db.QueryRowContext(ctx, updateMaterial,
		arg.ID,
		arg.Name,
		arg.SupplierID,
		arg.UnitPrice,
		arg.Unit,
		arg.SupplierCode,
		arg.PriceSource,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SupplierID,
		&i.UnitPrice,
		&i.Unit,
		&i.SupplierCode,
		&i.PriceSource,
		&i.LastUpdated,
		&i.CreatedAt,
	)
	return i, err
}
