// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Category struct {
	ID               string          `json:"id"`
	JobID            string          `json:"job_id"`
	ParentID         sql.NullString  `json:"parent_id"`
	Name             string          `json:"name"`
	SurchargePercent sql.NullFloat64 `json:"surcharge_percent"`
	SortOrder        int64           `json:"sort_order"`
}

type ItemTemplate struct {
	ID           int64   `json:"id"`
	Type         string  `json:"type"`
	Category     string  `json:"category"`
	Name         string  `json:"name"`
	DefaultUnit  string  `json:"default_unit"`
	DefaultPrice float64 `json:"default_price"`
}

type Job struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	CustomerName     sql.NullString `json:"customer_name"`
	SurchargePercent float64        `json:"surcharge_percent"`
	SurchargeMode    string         `json:"surcharge_mode"`
	CreatedAt        string         `json:"created_at"`
	Status           string         `json:"status"`
	ExpiresAt        sql.NullString `json:"expires_at"`
}

type LineItem struct {
	ID               string          `json:"id"`
	CategoryID       string          `json:"category_id"`
	Type             string          `json:"type"`
	Name             string          `json:"name"`
	Description      sql.NullString  `json:"description"`
	Quantity         float64         `json:"quantity"`
	Unit             string          `json:"unit"`
	UnitPrice        float64         `json:"unit_price"`
	SurchargePercent sql.NullFloat64 `json:"surcharge_percent"`
	SortOrder        int64           `json:"sort_order"`
}

type Setting struct {
	ID                      string  `json:"id"`
	DefaultSurchargeMode    string  `json:"default_surcharge_mode"`
	DefaultSurchargePercent float64 `json:"default_surcharge_percent"`
}
