// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Client struct {
	ID          string         `json:"id"`
	CompanyName string         `json:"company_name"`
	ContactName sql.NullString `json:"contact_name"`
	Email       sql.NullString `json:"email"`
	Phone       sql.NullString `json:"phone"`
	Address     sql.NullString `json:"address"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   time.Time      `json:"created_at"`
}

type CompanyProfile struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Email     sql.NullString `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Address   sql.NullString `json:"address"`
	City      sql.NullString `json:"city"`
	State     sql.NullString `json:"state"`
	Zip       sql.NullString `json:"zip"`
	LogoPath  sql.NullString `json:"logo_path"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type ComponentGroup struct {
	ID            string `json:"id"`
	SubcategoryID string `json:"subcategory_id"`
	Name          string `json:"name"`
	SortOrder     int64  `json:"sort_order"`
}

type LineItem struct {
	ID               string         `json:"id"`
	SubcategoryID    string         `json:"subcategory_id"`
	ComponentGroupID sql.NullString `json:"component_group_id"`
	CategoryType     string         `json:"category_type"`
	ItemName         string         `json:"item_name"`
	Quantity         float64        `json:"quantity"`
	Unit             string         `json:"unit"`
	UnitPrice        float64        `json:"unit_price"`
	IsCustom         bool           `json:"is_custom"`
	MaterialID       sql.NullString `json:"material_id"`
	PriceOverride    bool           `json:"price_override"`
	Description      sql.NullString `json:"description"`
	SortOrder        int64          `json:"sort_order"`
	SubcontractorID  sql.NullString `json:"subcontractor_id"`
	VisualGroup      sql.NullString `json:"visual_group"`
}

type Material struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	SupplierID   string         `json:"supplier_id"`
	UnitPrice    float64        `json:"unit_price"`
	Unit         string         `json:"unit"`
	SupplierCode sql.NullString `json:"supplier_code"`
	PriceSource  string         `json:"price_source"`
	LastUpdated  time.Time      `json:"last_updated"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Project struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	ClientID        sql.NullString `json:"client_id"`
	ClientName      sql.NullString `json:"client_name"`
	Status          string         `json:"status"`
	Total           float64        `json:"total"`
	Description     sql.NullString `json:"description"`
	MaterialsMarkup float64        `json:"materials_markup"`
	LaborMarkup     float64        `json:"labor_markup"`
	EquipmentMarkup float64        `json:"equipment_markup"`
	SubsMarkup      float64        `json:"subs_markup"`
	OtherMarkup     float64        `json:"other_markup"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Quote struct {
	ID               string                `json:"id"`
	ProjectID        string                `json:"project_id"`
	Version          int64                 `json:"version"`
	Status           string                `json:"status"`
	EstimateSnapshot pqtype.NullRawMessage `json:"estimate_snapshot"`
	TotalsSnapshot   pqtype.NullRawMessage `json:"totals_snapshot"`
	Token            sql.NullString        `json:"token"`
	ExpiresAt        sql.NullTime          `json:"expires_at"`
	SentAt           sql.NullTime          `json:"sent_at"`
	CreatedAt        time.Time             `json:"created_at"`
	CreatedBy        sql.NullString        `json:"created_by"`
}

type QuoteEmail struct {
	ID         string         `json:"id"`
	QuoteID    string         `json:"quote_id"`
	Recipient  string         `json:"recipient"`
	SentAt     time.Time      `json:"sent_at"`
	ProviderID sql.NullString `json:"provider_id"`
}

type QuoteSignature struct {
	ID         string         `json:"id"`
	QuoteID    string         `json:"quote_id"`
	SignerName string         `json:"signer_name"`
	SignerIp   sql.NullString `json:"signer_ip"`
	SignedAt   time.Time      `json:"signed_at"`
}

type Rate struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	CategoryID  string         `json:"category_id"`
	Supplier    sql.NullString `json:"supplier"`
	Rate        float64        `json:"rate"`
	Unit        string         `json:"unit"`
	Notes       sql.NullString `json:"notes"`
	LastUpdated time.Time      `json:"last_updated"`
	CreatedAt   time.Time      `json:"created_at"`
}

type RateCategory struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	SortOrder int64     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
}

type Section struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
}

type Session struct {
	ID             string         `json:"id"`
	UserID         string         `json:"user_id"`
	TokenHash      string         `json:"token_hash"`
	UserAgent      sql.NullString `json:"user_agent"`
	IpAddress      sql.NullString `json:"ip_address"`
	ExpiresAt      time.Time      `json:"expires_at"`
	LastActivityAt time.Time      `json:"last_activity_at"`
	CreatedAt      time.Time      `json:"created_at"`
}

type Subcategory struct {
	ID                     string          `json:"id"`
	SectionID              string          `json:"section_id"`
	Name                   string          `json:"name"`
	SortOrder              int64           `json:"sort_order"`
	LumpSum                float64         `json:"lump_sum"`
	MaterialsMarkup        sql.NullFloat64 `json:"materials_markup"`
	LaborMarkup            sql.NullFloat64 `json:"labor_markup"`
	EquipmentMarkup        sql.NullFloat64 `json:"equipment_markup"`
	SubsMarkup             sql.NullFloat64 `json:"subs_markup"`
	OtherMarkup            sql.NullFloat64 `json:"other_markup"`
	MaterialsMarkupEnabled bool            `json:"materials_markup_enabled"`
	LaborMarkupEnabled     bool            `json:"labor_markup_enabled"`
	EquipmentMarkupEnabled bool            `json:"equipment_markup_enabled"`
	SubsMarkupEnabled      bool            `json:"subs_markup_enabled"`
	OtherMarkupEnabled     bool            `json:"other_markup_enabled"`
}

type Subcontractor struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Company    sql.NullString `json:"company"`
	Phone      sql.NullString `json:"phone"`
	Email      sql.NullString `json:"email"`
	Address    sql.NullString `json:"address"`
	Notes      sql.NullString `json:"notes"`
	IsFavorite bool           `json:"is_favorite"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type SubcontractorTrade struct {
	SubcontractorID string `json:"subcontractor_id"`
	TradeID         string `json:"trade_id"`
	Position        int64  `json:"position"`
}

type Supplier struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	SortOrder int64     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
}

type Template struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type TemplateComponentGroup struct {
	ID                    string `json:"id"`
	TemplateSubcategoryID string `json:"template_subcategory_id"`
	Name                  string `json:"name"`
	SortOrder             int64  `json:"sort_order"`
}

type TemplateSection struct {
	ID         string `json:"id"`
	TemplateID string `json:"template_id"`
	Name       string `json:"name"`
	SortOrder  int64  `json:"sort_order"`
}

type TemplateSubcategory struct {
	ID                string `json:"id"`
	TemplateSectionID string `json:"template_section_id"`
	Name              string `json:"name"`
	SortOrder         int64  `json:"sort_order"`
}

type Trade struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
}

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
