// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Category struct {
	ID               string          `json:"id"`
	JobID            string          `json:"job_id"`
	ParentID         sql.NullString  `json:"parent_id"`
	Name             string          `json:"name"`
	SurchargePercent sql.NullFloat64 `json:"surcharge_percent"`
	SortOrder        int64           `json:"sort_order"`
}

type Client struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Company   sql.NullString `json:"company"`
	Email     sql.NullString `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Address   sql.NullString `json:"address"`
	City      sql.NullString `json:"city"`
	State     sql.NullString `json:"state"`
	Zip       sql.NullString `json:"zip"`
	TaxID     sql.NullString `json:"tax_id"`
	Notes     sql.NullString `json:"notes"`
	CreatedAt string         `json:"created_at"`
}

type CompanyProfile struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Email     sql.NullString `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Address   sql.NullString `json:"address"`
	City      sql.NullString `json:"city"`
	State     sql.NullString `json:"state"`
	Zip       sql.NullString `json:"zip"`
	LogoPath  sql.NullString `json:"logo_path"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type Estimate struct {
	ID          string         `json:"id"`
	JobID       string         `json:"job_id"`
	Version     int64          `json:"version"`
	Status      string         `json:"status"`
	GrandTotal  float64        `json:"grand_total"`
	Notes       sql.NullString `json:"notes"`
	SentAt      sql.NullString `json:"sent_at"`
	RespondedAt sql.NullString `json:"responded_at"`
	CreatedAt   string         `json:"created_at"`
}

type EstimateCategory struct {
	ID               string         `json:"id"`
	EstimateID       string         `json:"estimate_id"`
	CategoryID       string         `json:"category_id"`
	ParentCategoryID sql.NullString `json:"parent_category_id"`
	Tier             int64          `json:"tier"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	Total            float64        `json:"total"`
	SortOrder        int64          `json:"sort_order"`
}

type ItemTemplate struct {
	ID           int64   `json:"id"`
	Type         string  `json:"type"`
	Category     string  `json:"category"`
	Name         string  `json:"name"`
	DefaultUnit  string  `json:"default_unit"`
	DefaultPrice float64 `json:"default_price"`
}

type Job struct {
	ID                        string          `json:"id"`
	Name                      string          `json:"name"`
	CustomerName              sql.NullString  `json:"customer_name"`
	SurchargePercent          float64         `json:"surcharge_percent"`
	SurchargeMode             string          `json:"surcharge_mode"`
	CreatedAt                 string          `json:"created_at"`
	Status                    string          `json:"status"`
	ExpiresAt                 sql.NullString  `json:"expires_at"`
	ClientID                  sql.NullString  `json:"client_id"`
	MaterialSurchargePercent  sql.NullFloat64 `json:"material_surcharge_percent"`
	LaborSurchargePercent     sql.NullFloat64 `json:"labor_surcharge_percent"`
	EquipmentSurchargePercent sql.NullFloat64 `json:"equipment_surcharge_percent"`
}

type JobItemType struct {
	ID               string          `json:"id"`
	JobID            string          `json:"job_id"`
	Name             string          `json:"name"`
	Slug             string          `json:"slug"`
	Color            string          `json:"color"`
	SortOrder        int64           `json:"sort_order"`
	CreatedAt        string          `json:"created_at"`
	SurchargePercent sql.NullFloat64 `json:"surcharge_percent"`
}

type LineItem struct {
	ID               string          `json:"id"`
	CategoryID       string          `json:"category_id"`
	Type             string          `json:"type"`
	Name             string          `json:"name"`
	Description      sql.NullString  `json:"description"`
	Quantity         float64         `json:"quantity"`
	Unit             string          `json:"unit"`
	UnitPrice        float64         `json:"unit_price"`
	SurchargePercent sql.NullFloat64 `json:"surcharge_percent"`
	SortOrder        int64           `json:"sort_order"`
	Tag              sql.NullString  `json:"tag"`
}

type PriceImport struct {
	ID           string         `json:"id"`
	Filename     string         `json:"filename"`
	Status       string         `json:"status"`
	TotalRows    int64          `json:"total_rows"`
	MatchedRows  int64          `json:"matched_rows"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    string         `json:"created_at"`
	AppliedAt    sql.NullString `json:"applied_at"`
}

type PriceImportMatch struct {
	ID                int64          `json:"id"`
	ImportID          string         `json:"import_id"`
	RowNumber         int64          `json:"row_number"`
	SourceName        string         `json:"source_name"`
	SourceUnit        sql.NullString `json:"source_unit"`
	SourcePrice       float64        `json:"source_price"`
	MatchedTemplateID sql.NullInt64  `json:"matched_template_id"`
	Confidence        float64        `json:"confidence"`
	MatchReason       sql.NullString `json:"match_reason"`
	Status            string         `json:"status"`
	NewName           sql.NullString `json:"new_name"`
	CreatedAt         string         `json:"created_at"`
}

type Setting struct {
	ID                      string  `json:"id"`
	DefaultSurchargeMode    string  `json:"default_surcharge_mode"`
	DefaultSurchargePercent float64 `json:"default_surcharge_percent"`
}

type Signature struct {
	ID                 string         `json:"id"`
	RequestID          string         `json:"request_id"`
	LegalName          string         `json:"legal_name"`
	ConsentText        string         `json:"consent_text"`
	DocumentHash       string         `json:"document_hash"`
	SignedAt           string         `json:"signed_at"`
	SignerIp           string         `json:"signer_ip"`
	SignerUserAgent    string         `json:"signer_user_agent"`
	SignerEmail        string         `json:"signer_email"`
	CertificatePdfPath sql.NullString `json:"certificate_pdf_path"`
	CreatedAt          string         `json:"created_at"`
}

type SignatureRequest struct {
	ID              string         `json:"id"`
	EstimateID      string         `json:"estimate_id"`
	RecipientEmail  string         `json:"recipient_email"`
	RecipientName   string         `json:"recipient_name"`
	Token           string         `json:"token"`
	DocumentHash    string         `json:"document_hash"`
	QuoteSnapshot   string         `json:"quote_snapshot"`
	Message         sql.NullString `json:"message"`
	Status          string         `json:"status"`
	ExpiresAt       string         `json:"expires_at"`
	SenderIp        sql.NullString `json:"sender_ip"`
	SenderUserAgent sql.NullString `json:"sender_user_agent"`
	CreatedAt       string         `json:"created_at"`
}
