// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    name,
    subdomain,
    stripe_customer_id,
    plan,
    status,
    trial_ends_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, subdomain, stripe_customer_id, plan, status, trial_ends_at, subscription_ends_at, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name             string         `json:"name"`
	Subdomain        string         `json:"subdomain"`
	StripeCustomerID sql.NullString `json:"stripe_customer_id"`
	Plan             string         `json:"plan"`
	Status           string         `json:"status"`
	TrialEndsAt      sql.NullTime   `json:"trial_ends_at"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganization,
		arg.Name,
		arg.Subdomain,
		arg.StripeCustomerID,
		arg.Plan,
		arg.Status,
		arg.TrialEndsAt,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subdomain,
		&i.StripeCustomerID,
		&i.Plan,
		&i.Status,
		&i.TrialEndsAt,
		&i.SubscriptionEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations
WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrganization, id)
	return err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, subdomain, stripe_customer_id, plan, status, trial_ends_at, subscription_ends_at, created_at, updated_at FROM organizations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subdomain,
		&i.StripeCustomerID,
		&i.Plan,
		&i.Status,
		&i.TrialEndsAt,
		&i.SubscriptionEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByStripeCustomerID = `-- name: GetOrganizationByStripeCustomerID :one
SELECT id, name, subdomain, stripe_customer_id, plan, status, trial_ends_at, subscription_ends_at, created_at, updated_at FROM organizations
WHERE stripe_customer_id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationByStripeCustomerID(ctx context.Context, stripeCustomerID sql.NullString) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByStripeCustomerID, stripeCustomerID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subdomain,
		&i.StripeCustomerID,
		&i.Plan,
		&i.Status,
		&i.TrialEndsAt,
		&i.SubscriptionEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySubdomain = `-- name: GetOrganizationBySubdomain :one
SELECT id, name, subdomain, stripe_customer_id, plan, status, trial_ends_at, subscription_ends_at, created_at, updated_at FROM organizations
WHERE subdomain = $1 LIMIT 1
`

func (q *Queries) GetOrganizationBySubdomain(ctx context.Context, subdomain string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationBySubdomain, subdomain)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subdomain,
		&i.StripeCustomerID,
		&i.Plan,
		&i.Status,
		&i.TrialEndsAt,
		&i.SubscriptionEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveOrganizations = `-- name: ListActiveOrganizations :many
SELECT id, name, subdomain, stripe_customer_id, plan, status, trial_ends_at, subscription_ends_at, created_at, updated_at FROM organizations
WHERE status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListActiveOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listActiveOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Subdomain,
			&i.StripeCustomerID,
			&i.Plan,
			&i.Status,
			&i.TrialEndsAt,
			&i.SubscriptionEndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, subdomain, stripe_customer_id, plan, status, trial_ends_at, subscription_ends_at, created_at, updated_at FROM organizations
ORDER BY created_at DESC
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Subdomain,
			&i.StripeCustomerID,
			&i.Plan,
			&i.Status,
			&i.TrialEndsAt,
			&i.SubscriptionEndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET
    name = COALESCE($1, name),
    subdomain = COALESCE($2, subdomain),
    stripe_customer_id = COALESCE($3, stripe_customer_id),
    plan = COALESCE($4, plan),
    status = COALESCE($5, status),
    trial_ends_at = COALESCE($6, trial_ends_at),
    subscription_ends_at = COALESCE($7, subscription_ends_at),
    updated_at = NOW()
WHERE id = $8
RETURNING id, name, subdomain, stripe_customer_id, plan, status, trial_ends_at, subscription_ends_at, created_at, updated_at
`

type UpdateOrganizationParams struct {
	Name               sql.NullString `json:"name"`
	Subdomain          sql.NullString `json:"subdomain"`
	StripeCustomerID   sql.NullString `json:"stripe_customer_id"`
	Plan               sql.NullString `json:"plan"`
	Status             sql.NullString `json:"status"`
	TrialEndsAt        sql.NullTime   `json:"trial_ends_at"`
	SubscriptionEndsAt sql.NullTime   `json:"subscription_ends_at"`
	ID                 uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, updateOrganization,
		arg.Name,
		arg.Subdomain,
		arg.StripeCustomerID,
		arg.Plan,
		arg.Status,
		arg.TrialEndsAt,
		arg.SubscriptionEndsAt,
		arg.ID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subdomain,
		&i.StripeCustomerID,
		&i.Plan,
		&i.Status,
		&i.TrialEndsAt,
		&i.SubscriptionEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
