// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package repository

import (
	"context"
	"database/sql"
)

const countProjectsByStatus = `-- name: CountProjectsByStatus :one
SELECT
    COUNT(*) FILTER (WHERE status = 'Draft') AS draft_count,
    COUNT(*) FILTER (WHERE status = 'In Review') AS in_review_count,
    COUNT(*) FILTER (WHERE status = 'Active') AS active_count,
    COUNT(*) FILTER (WHERE status = 'Completed') AS completed_count,
    COALESCE(SUM(total) FILTER (WHERE status = 'Draft'), 0)::real AS draft_total,
    COALESCE(SUM(total) FILTER (WHERE status = 'In Review'), 0)::real AS in_review_total,
    COALESCE(SUM(total) FILTER (WHERE status = 'Active'), 0)::real AS active_total,
    COALESCE(SUM(total) FILTER (WHERE status = 'Completed'), 0)::real AS completed_total
FROM projects
`

type CountProjectsByStatusRow struct {
	DraftCount     int64   `json:"draft_count"`
	InReviewCount  int64   `json:"in_review_count"`
	ActiveCount    int64   `json:"active_count"`
	CompletedCount int64   `json:"completed_count"`
	DraftTotal     float64 `json:"draft_total"`
	InReviewTotal  float64 `json:"in_review_total"`
	ActiveTotal    float64 `json:"active_total"`
	CompletedTotal float64 `json:"completed_total"`
}

func (q *Queries) CountProjectsByStatus(ctx context.Context) (CountProjectsByStatusRow, error) {
	row := q.db.QueryRowContext(ctx, countProjectsByStatus)
	var i CountProjectsByStatusRow
	err := row.Scan(
		&i.DraftCount,
		&i.InReviewCount,
		&i.ActiveCount,
		&i.CompletedCount,
		&i.DraftTotal,
		&i.InReviewTotal,
		&i.ActiveTotal,
		&i.CompletedTotal,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, name, client_id, client_name, description, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, client_id, client_name, status, total, description, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup, created_at, updated_at
`

type CreateProjectParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	ClientID    sql.NullString `json:"client_id"`
	ClientName  sql.NullString `json:"client_name"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.ClientID,
		arg.ClientName,
		arg.Description,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.ClientName,
		&i.Status,
		&i.Total,
		&i.Description,
		&i.MaterialsMarkup,
		&i.LaborMarkup,
		&i.EquipmentMarkup,
		&i.SubsMarkup,
		&i.OtherMarkup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, client_id, client_name, status, total, description, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.ClientName,
		&i.Status,
		&i.Total,
		&i.Description,
		&i.MaterialsMarkup,
		&i.LaborMarkup,
		&i.EquipmentMarkup,
		&i.SubsMarkup,
		&i.OtherMarkup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, client_id, client_name, status, total, description, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup, created_at, updated_at FROM projects ORDER BY updated_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClientID,
			&i.ClientName,
			&i.Status,
			&i.Total,
			&i.Description,
			&i.MaterialsMarkup,
			&i.LaborMarkup,
			&i.EquipmentMarkup,
			&i.SubsMarkup,
			&i.OtherMarkup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByStatus = `-- name: ListProjectsByStatus :many
SELECT id, name, client_id, client_name, status, total, description, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup, created_at, updated_at FROM projects WHERE status = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListProjectsByStatus(ctx context.Context, status string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClientID,
			&i.ClientName,
			&i.Status,
			&i.Total,
			&i.Description,
			&i.MaterialsMarkup,
			&i.LaborMarkup,
			&i.EquipmentMarkup,
			&i.SubsMarkup,
			&i.OtherMarkup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProjects = `-- name: SearchProjects :many
SELECT id, name, client_id, client_name, status, total, description, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup, created_at, updated_at FROM projects
WHERE name ILIKE '%' || $1::text || '%' OR client_name ILIKE '%' || $1::text || '%'
ORDER BY updated_at DESC
`

func (q *Queries) SearchProjects(ctx context.Context, searchTerm string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, searchProjects, searchTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClientID,
			&i.ClientName,
			&i.Status,
			&i.Total,
			&i.Description,
			&i.MaterialsMarkup,
			&i.LaborMarkup,
			&i.EquipmentMarkup,
			&i.SubsMarkup,
			&i.OtherMarkup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProjectsByStatus = `-- name: SearchProjectsByStatus :many
SELECT id, name, client_id, client_name, status, total, description, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup, created_at, updated_at FROM projects
WHERE (name ILIKE '%' || $1::text || '%' OR client_name ILIKE '%' || $1::text || '%')
  AND status = $2
ORDER BY updated_at DESC
`

type SearchProjectsByStatusParams struct {
	SearchTerm string `json:"search_term"`
	Status     string `json:"status"`
}

func (q *Queries) SearchProjectsByStatus(ctx context.Context, arg SearchProjectsByStatusParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, searchProjectsByStatus, arg.SearchTerm, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClientID,
			&i.ClientName,
			&i.Status,
			&i.Total,
			&i.Description,
			&i.MaterialsMarkup,
			&i.LaborMarkup,
			&i.EquipmentMarkup,
			&i.SubsMarkup,
			&i.OtherMarkup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, client_id = $3, client_name = $4, description = $5, updated_at = now()
WHERE id = $1
RETURNING id, name, client_id, client_name, status, total, description, materials_markup, labor_markup, equipment_markup, subs_markup, other_markup, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	ClientID    sql.NullString `json:"client_id"`
	ClientName  sql.NullString `json:"client_name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.ClientID,
		arg.ClientName,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.ClientName,
		&i.Status,
		&i.Total,
		&i.Description,
		&i.MaterialsMarkup,
		&i.LaborMarkup,
		&i.EquipmentMarkup,
		&i.SubsMarkup,
		&i.OtherMarkup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectClient = `-- name: UpdateProjectClient :exec
UPDATE projects SET client_id = $2, client_name = $3, updated_at = now() WHERE id = $1
`

type UpdateProjectClientParams struct {
	ID         string         `json:"id"`
	ClientID   sql.NullString `json:"client_id"`
	ClientName sql.NullString `json:"client_name"`
}

func (q *Queries) UpdateProjectClient(ctx context.Context, arg UpdateProjectClientParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectClient, arg.ID, arg.ClientID, arg.ClientName)
	return err
}

const updateProjectStatus = `-- name: UpdateProjectStatus :exec
UPDATE projects SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateProjectStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectStatus, arg.ID, arg.Status)
	return err
}

const updateProjectTotal = `-- name: UpdateProjectTotal :exec
UPDATE projects SET total = $2, updated_at = now() WHERE id = $1
`

type UpdateProjectTotalParams struct {
	ID    string  `json:"id"`
	Total float64 `json:"total"`
}

func (q *Queries) UpdateProjectTotal(ctx context.Context, arg UpdateProjectTotalParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectTotal, arg.ID, arg.Total)
	return err
}
