// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quotes.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const createQuote = `-- name: CreateQuote :one
INSERT INTO quotes (id, project_id, version, status, estimate_snapshot, totals_snapshot, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, version, status, estimate_snapshot, totals_snapshot, token, expires_at, sent_at, created_at, created_by
`

type CreateQuoteParams struct {
	ID               string                `json:"id"`
	ProjectID        string                `json:"project_id"`
	Version          int64                 `json:"version"`
	Status           string                `json:"status"`
	EstimateSnapshot pqtype.NullRawMessage `json:"estimate_snapshot"`
	TotalsSnapshot   pqtype.NullRawMessage `json:"totals_snapshot"`
	CreatedBy        sql.NullString        `json:"created_by"`
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error) {
	row := q.db.QueryRowContext(ctx, createQuote,
		arg.ID,
		arg.ProjectID,
		arg.Version,
		arg.Status,
		arg.EstimateSnapshot,
		arg.TotalsSnapshot,
		arg.CreatedBy,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Status,
		&i.EstimateSnapshot,
		&i.TotalsSnapshot,
		&i.Token,
		&i.ExpiresAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createQuoteEmail = `-- name: CreateQuoteEmail :one
INSERT INTO quote_emails (id, quote_id, recipient, provider_id)
VALUES ($1, $2, $3, $4)
RETURNING id, quote_id, recipient, sent_at, provider_id
`

type CreateQuoteEmailParams struct {
	ID         string         `json:"id"`
	QuoteID    string         `json:"quote_id"`
	Recipient  string         `json:"recipient"`
	ProviderID sql.NullString `json:"provider_id"`
}

func (q *Queries) CreateQuoteEmail(ctx context.Context, arg CreateQuoteEmailParams) (QuoteEmail, error) {
	row := q.db.QueryRowContext(ctx, createQuoteEmail,
		arg.ID,
		arg.QuoteID,
		arg.Recipient,
		arg.ProviderID,
	)
	var i QuoteEmail
	err := row.Scan(
		&i.ID,
		&i.QuoteID,
		&i.Recipient,
		&i.SentAt,
		&i.ProviderID,
	)
	return i, err
}

const createQuoteSignature = `-- name: CreateQuoteSignature :one
INSERT INTO quote_signatures (id, quote_id, signer_name, signer_ip)
VALUES ($1, $2, $3, $4)
RETURNING id, quote_id, signer_name, signer_ip, signed_at
`

type CreateQuoteSignatureParams struct {
	ID         string         `json:"id"`
	QuoteID    string         `json:"quote_id"`
	SignerName string         `json:"signer_name"`
	SignerIp   sql.NullString `json:"signer_ip"`
}

func (q *Queries) CreateQuoteSignature(ctx context.Context, arg CreateQuoteSignatureParams) (QuoteSignature, error) {
	row := q.db.QueryRowContext(ctx, createQuoteSignature,
		arg.ID,
		arg.QuoteID,
		arg.SignerName,
		arg.SignerIp,
	)
	var i QuoteSignature
	err := row.Scan(
		&i.ID,
		&i.QuoteID,
		&i.SignerName,
		&i.SignerIp,
		&i.SignedAt,
	)
	return i, err
}

const getLatestQuoteVersion = `-- name: GetLatestQuoteVersion :one
SELECT COALESCE(MAX(version), 0)::integer AS version FROM quotes WHERE project_id = $1
`

func (q *Queries) GetLatestQuoteVersion(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLatestQuoteVersion, projectID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getQuote = `-- name: GetQuote :one
SELECT id, project_id, version, status, estimate_snapshot, totals_snapshot, token, expires_at, sent_at, created_at, created_by FROM quotes WHERE id = $1
`

func (q *Queries) GetQuote(ctx context.Context, id string) (Quote, error) {
	row := q.db.QueryRowContext(ctx, getQuote, id)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Status,
		&i.EstimateSnapshot,
		&i.TotalsSnapshot,
		&i.Token,
		&i.ExpiresAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getQuoteByToken = `-- name: GetQuoteByToken :one
SELECT q.id, q.project_id, q.version, q.status, q.estimate_snapshot, q.totals_snapshot, q.token, q.expires_at, q.sent_at, q.created_at, q.created_by,
    p.name AS project_name, p.client_name AS project_client_name,
    c.company_name AS client_company, c.contact_name AS client_contact,
    c.email AS client_email, c.phone AS client_phone
FROM quotes q
JOIN projects p ON p.id = q.project_id
LEFT JOIN clients c ON c.id = p.client_id
WHERE q.token = $1
`

type GetQuoteByTokenRow struct {
	ID                string                `json:"id"`
	ProjectID         string                `json:"project_id"`
	Version           int64                 `json:"version"`
	Status            string                `json:"status"`
	EstimateSnapshot  pqtype.NullRawMessage `json:"estimate_snapshot"`
	TotalsSnapshot    pqtype.NullRawMessage `json:"totals_snapshot"`
	Token             sql.NullString        `json:"token"`
	ExpiresAt         sql.NullTime          `json:"expires_at"`
	SentAt            sql.NullTime          `json:"sent_at"`
	CreatedAt         time.Time             `json:"created_at"`
	CreatedBy         sql.NullString        `json:"created_by"`
	ProjectName       string                `json:"project_name"`
	ProjectClientName sql.NullString        `json:"project_client_name"`
	ClientCompany     sql.NullString        `json:"client_company"`
	ClientContact     sql.NullString        `json:"client_contact"`
	ClientEmail       sql.NullString        `json:"client_email"`
	ClientPhone       sql.NullString        `json:"client_phone"`
}

func (q *Queries) GetQuoteByToken(ctx context.Context, token sql.NullString) (GetQuoteByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getQuoteByToken, token)
	var i GetQuoteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Status,
		&i.EstimateSnapshot,
		&i.TotalsSnapshot,
		&i.Token,
		&i.ExpiresAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ProjectName,
		&i.ProjectClientName,
		&i.ClientCompany,
		&i.ClientContact,
		&i.ClientEmail,
		&i.ClientPhone,
	)
	return i, err
}

const getQuoteSignature = `-- name: GetQuoteSignature :one
SELECT id, quote_id, signer_name, signer_ip, signed_at FROM quote_signatures WHERE quote_id = $1
`

func (q *Queries) GetQuoteSignature(ctx context.Context, quoteID string) (QuoteSignature, error) {
	row := q.db.QueryRowContext(ctx, getQuoteSignature, quoteID)
	var i QuoteSignature
	err := row.Scan(
		&i.ID,
		&i.QuoteID,
		&i.SignerName,
		&i.SignerIp,
		&i.SignedAt,
	)
	return i, err
}

const listQuoteEmails = `-- name: ListQuoteEmails :many
SELECT id, quote_id, recipient, sent_at, provider_id FROM quote_emails WHERE quote_id = $1 ORDER BY sent_at DESC
`

func (q *Queries) ListQuoteEmails(ctx context.Context, quoteID string) ([]QuoteEmail, error) {
	rows, err := q.db.QueryContext(ctx, listQuoteEmails, quoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuoteEmail{}
	for rows.Next() {
		var i QuoteEmail
		if err := rows.Scan(
			&i.ID,
			&i.QuoteID,
			&i.Recipient,
			&i.SentAt,
			&i.ProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotesByProject = `-- name: ListQuotesByProject :many
SELECT id, project_id, version, status, estimate_snapshot, totals_snapshot, token, expires_at, sent_at, created_at, created_by FROM quotes WHERE project_id = $1 ORDER BY version DESC
`

func (q *Queries) ListQuotesByProject(ctx context.Context, projectID string) ([]Quote, error) {
	rows, err := q.db.QueryContext(ctx, listQuotesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quote{}
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.Status,
			&i.EstimateSnapshot,
			&i.TotalsSnapshot,
			&i.Token,
			&i.ExpiresAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeActiveQuotes = `-- name: SupersedeActiveQuotes :exec
UPDATE quotes SET status = 'superseded' WHERE project_id = $1 AND status IN ('draft', 'sent')
`

func (q *Queries) SupersedeActiveQuotes(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, supersedeActiveQuotes, projectID)
	return err
}

const updateQuoteSent = `-- name: UpdateQuoteSent :exec
UPDATE quotes SET token = $2, sent_at = $3, expires_at = $4, status = 'sent' WHERE id = $1
`

type UpdateQuoteSentParams struct {
	ID        string         `json:"id"`
	Token     sql.NullString `json:"token"`
	SentAt    sql.NullTime   `json:"sent_at"`
	ExpiresAt sql.NullTime   `json:"expires_at"`
}

func (q *Queries) UpdateQuoteSent(ctx context.Context, arg UpdateQuoteSentParams) error {
	_, err := q.db.ExecContext(ctx, updateQuoteSent,
		arg.ID,
		arg.Token,
		arg.SentAt,
		arg.ExpiresAt,
	)
	return err
}

const updateQuoteStatus = `-- name: UpdateQuoteStatus :exec
UPDATE quotes SET status = $2 WHERE id = $1
`

type UpdateQuoteStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateQuoteStatus(ctx context.Context, arg UpdateQuoteStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateQuoteStatus, arg.ID, arg.Status)
	return err
}
