// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rates.sql

package repository

import (
	"context"
	"database/sql"
)

const createRate = `-- name: CreateRate :one
INSERT INTO rates (id, name, category_id, supplier, rate, unit, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, category_id, supplier, rate, unit, notes, last_updated, created_at
`

type CreateRateParams struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	CategoryID string         `json:"category_id"`
	Supplier   sql.NullString `json:"supplier"`
	Rate       float64        `json:"rate"`
	Unit       string         `json:"unit"`
	Notes      sql.NullString `json:"notes"`
}

func (q *Queries) CreateRate(ctx context.Context, arg CreateRateParams) (Rate, error) {
	row := q.db.QueryRowContext(ctx, createRate,
		arg.ID,
		arg.Name,
		arg.CategoryID,
		arg.Supplier,
		arg.Rate,
		arg.Unit,
		arg.Notes,
	)
	var i Rate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Supplier,
		&i.Rate,
		&i.Unit,
		&i.Notes,
		&i.LastUpdated,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRate = `-- name: DeleteRate :exec
DELETE FROM rates WHERE id = $1
`

func (q *Queries) DeleteRate(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRate, id)
	return err
}

const getRate = `-- name: GetRate :one
SELECT id, name, category_id, supplier, rate, unit, notes, last_updated, created_at FROM rates WHERE id = $1
`

func (q *Queries) GetRate(ctx context.Context, id string) (Rate, error) {
	row := q.db.QueryRowContext(ctx, getRate, id)
	var i Rate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Supplier,
		&i.Rate,
		&i.Unit,
		&i.Notes,
		&i.LastUpdated,
		&i.CreatedAt,
	)
	return i, err
}

const listRates = `-- name: ListRates :many
SELECT id, name, category_id, supplier, rate, unit, notes, last_updated, created_at FROM rates ORDER BY name ASC
`

func (q *Queries) ListRates(ctx context.Context) ([]Rate, error) {
	rows, err := q.db.QueryContext(ctx, listRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rate{}
	for rows.Next() {
		var i Rate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.Supplier,
			&i.Rate,
			&i.Unit,
			&i.Notes,
			&i.LastUpdated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatesByCategory = `-- name: ListRatesByCategory :many
SELECT id, name, category_id, supplier, rate, unit, notes, last_updated, created_at FROM rates WHERE category_id = $1 ORDER BY name ASC
`

func (q *Queries) ListRatesByCategory(ctx context.Context, categoryID string) ([]Rate, error) {
	rows, err := q.db.QueryContext(ctx, listRatesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rate{}
	for rows.Next() {
		var i Rate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.Supplier,
			&i.Rate,
			&i.Unit,
			&i.Notes,
			&i.LastUpdated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRates = `-- name: SearchRates :many
SELECT id, name, category_id, supplier, rate, unit, notes, last_updated, created_at FROM rates
WHERE name ILIKE '%' || $1::text || '%'
   OR supplier ILIKE '%' || $1::text || '%'
   OR notes ILIKE '%' || $1::text || '%'
ORDER BY name ASC
`

func (q *Queries) SearchRates(ctx context.Context, searchTerm string) ([]Rate, error) {
	rows, err := q.db.QueryContext(ctx, searchRates, searchTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rate{}
	for rows.Next() {
		var i Rate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.Supplier,
			&i.Rate,
			&i.Unit,
			&i.Notes,
			&i.LastUpdated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRatesByCategory = `-- name: SearchRatesByCategory :many
SELECT id, name, category_id, supplier, rate, unit, notes, last_updated, created_at FROM rates
WHERE category_id = $1
  AND (name ILIKE '%' || $2::text || '%'
       OR supplier ILIKE '%' || $2::text || '%'
       OR notes ILIKE '%' || $2::text || '%')
ORDER BY name ASC
`

type SearchRatesByCategoryParams struct {
	CategoryID string `json:"category_id"`
	SearchTerm string `json:"search_term"`
}

func (q *Queries) SearchRatesByCategory(ctx context.Context, arg SearchRatesByCategoryParams) ([]Rate, error) {
	rows, err := q.db.QueryContext(ctx, searchRatesByCategory, arg.CategoryID, arg.SearchTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rate{}
	for rows.Next() {
		var i Rate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.Supplier,
			&i.Rate,
			&i.Unit,
			&i.Notes,
			&i.LastUpdated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRate = `-- name: UpdateRate :one
UPDATE rates
SET name = $2, category_id = $3, supplier = $4, rate = $5, unit = $6, notes = $7, last_updated = now()
WHERE id = $1
RETURNING id, name, category_id, supplier, rate, unit, notes, last_updated, created_at
`

type UpdateRateParams struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	CategoryID string         `json:"category_id"`
	Supplier   sql.NullString `json:"supplier"`
	Rate       float64        `json:"rate"`
	Unit       string         `json:"unit"`
	Notes      sql.NullString `json:"notes"`
}

func (q *Queries) UpdateRate(ctx context.Context, arg UpdateRateParams) (Rate, error) {
	row := q.db.QueryRowContext(ctx, updateRate,
		arg.ID,
		arg.Name,
		arg.CategoryID,
		arg.Supplier,
		arg.Rate,
		arg.Unit,
		arg.Notes,
	)
	var i Rate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Supplier,
		&i.Rate,
		&i.Unit,
		&i.Notes,
		&i.LastUpdated,
		&i.CreatedAt,
	)
	return i, err
}
