// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rate_categories.sql

package repository

import (
	"context"
)

const countRatesByCategory = `-- name: CountRatesByCategory :one
SELECT COUNT(*) AS total FROM rates WHERE category_id = $1
`

func (q *Queries) CountRatesByCategory(ctx context.Context, categoryID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRatesByCategory, categoryID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createRateCategory = `-- name: CreateRateCategory :one
INSERT INTO rate_categories (id, name, sort_order)
VALUES ($1, $2, $3)
RETURNING id, name, sort_order, created_at
`

type CreateRateCategoryParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) CreateRateCategory(ctx context.Context, arg CreateRateCategoryParams) (RateCategory, error) {
	row := q.db.QueryRowContext(ctx, createRateCategory, arg.ID, arg.Name, arg.SortOrder)
	var i RateCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRateCategory = `-- name: DeleteRateCategory :exec
DELETE FROM rate_categories WHERE id = $1
`

func (q *Queries) DeleteRateCategory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRateCategory, id)
	return err
}

const getRateCategory = `-- name: GetRateCategory :one
SELECT id, name, sort_order, created_at FROM rate_categories WHERE id = $1
`

func (q *Queries) GetRateCategory(ctx context.Context, id string) (RateCategory, error) {
	row := q.db.QueryRowContext(ctx, getRateCategory, id)
	var i RateCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listRateCategories = `-- name: ListRateCategories :many
SELECT id, name, sort_order, created_at FROM rate_categories ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListRateCategories(ctx context.Context) ([]RateCategory, error) {
	rows, err := q.db.QueryContext(ctx, listRateCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RateCategory{}
	for rows.Next() {
		var i RateCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
