// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, user_agent, ip_address, expires_at, last_activity_at, created_at
`

type CreateSessionParams struct {
	UserID    string         `json:"user_id"`
	TokenHash string         `json:"token_hash"`
	UserAgent sql.NullString `json:"user_agent"`
	IpAddress sql.NullString `json:"ip_address"`
	ExpiresAt time.Time      `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    s.id, s.user_id, s.token_hash, s.user_agent, s.ip_address,
    s.expires_at, s.last_activity_at, s.created_at,
    u.email, u.name, u.status AS user_status
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionByTokenHashRow struct {
	ID             string         `json:"id"`
	UserID         string         `json:"user_id"`
	TokenHash      string         `json:"token_hash"`
	UserAgent      sql.NullString `json:"user_agent"`
	IpAddress      sql.NullString `json:"ip_address"`
	ExpiresAt      time.Time      `json:"expires_at"`
	LastActivityAt time.Time      `json:"last_activity_at"`
	CreatedAt      time.Time      `json:"created_at"`
	Email          string         `json:"email"`
	Name           string         `json:"name"`
	UserStatus     string         `json:"user_status"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
		&i.UserStatus,
	)
	return i, err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE sessions SET last_activity_at = now() WHERE id = $1
`

func (q *Queries) UpdateSessionActivity(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateSessionActivity, id)
	return err
}
