// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package repository

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT id, default_surcharge_mode, default_surcharge_percent FROM settings
WHERE id = 'default'
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(&i.ID, &i.DefaultSurchargeMode, &i.DefaultSurchargePercent)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings SET
    default_surcharge_mode = ?,
    default_surcharge_percent = ?
WHERE id = 'default'
RETURNING id, default_surcharge_mode, default_surcharge_percent
`

type UpdateSettingsParams struct {
	DefaultSurchargeMode    string  `json:"default_surcharge_mode"`
	DefaultSurchargePercent float64 `json:"default_surcharge_percent"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, updateSettings, arg.DefaultSurchargeMode, arg.DefaultSurchargePercent)
	var i Setting
	err := row.Scan(&i.ID, &i.DefaultSurchargeMode, &i.DefaultSurchargePercent)
	return i, err
}
