// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signatures.sql

package repository

import (
	"context"
	"database/sql"
)

const cancelSignatureRequest = `-- name: CancelSignatureRequest :one
UPDATE signature_requests SET status = 'cancelled'
WHERE id = ? AND status = 'pending'
RETURNING id, estimate_id, recipient_email, recipient_name, token, document_hash, quote_snapshot, message, status, expires_at, sender_ip, sender_user_agent, created_at
`

func (q *Queries) CancelSignatureRequest(ctx context.Context, id string) (SignatureRequest, error) {
	row := q.db.QueryRowContext(ctx, cancelSignatureRequest, id)
	var i SignatureRequest
	err := row.Scan(
		&i.ID,
		&i.EstimateID,
		&i.RecipientEmail,
		&i.RecipientName,
		&i.Token,
		&i.DocumentHash,
		&i.QuoteSnapshot,
		&i.Message,
		&i.Status,
		&i.ExpiresAt,
		&i.SenderIp,
		&i.SenderUserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createSignature = `-- name: CreateSignature :one

INSERT INTO signatures (
    id, request_id, legal_name, consent_text, document_hash,
    signed_at, signer_ip, signer_user_agent, signer_email,
    certificate_pdf_path
)
VALUES (?, ?, ?, ?, ?, datetime('now'), ?, ?, ?, ?)
RETURNING id, request_id, legal_name, consent_text, document_hash, signed_at, signer_ip, signer_user_agent, signer_email, certificate_pdf_path, created_at
`

type CreateSignatureParams struct {
	ID                 string         `json:"id"`
	RequestID          string         `json:"request_id"`
	LegalName          string         `json:"legal_name"`
	ConsentText        string         `json:"consent_text"`
	DocumentHash       string         `json:"document_hash"`
	SignerIp           string         `json:"signer_ip"`
	SignerUserAgent    string         `json:"signer_user_agent"`
	SignerEmail        string         `json:"signer_email"`
	CertificatePdfPath sql.NullString `json:"certificate_pdf_path"`
}

// Signatures
func (q *Queries) CreateSignature(ctx context.Context, arg CreateSignatureParams) (Signature, error) {
	row := q.db.QueryRowContext(ctx, createSignature,
		arg.ID,
		arg.RequestID,
		arg.LegalName,
		arg.ConsentText,
		arg.DocumentHash,
		arg.SignerIp,
		arg.SignerUserAgent,
		arg.SignerEmail,
		arg.CertificatePdfPath,
	)
	var i Signature
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.LegalName,
		&i.ConsentText,
		&i.DocumentHash,
		&i.SignedAt,
		&i.SignerIp,
		&i.SignerUserAgent,
		&i.SignerEmail,
		&i.CertificatePdfPath,
		&i.CreatedAt,
	)
	return i, err
}

const createSignatureRequest = `-- name: CreateSignatureRequest :one

INSERT INTO signature_requests (
    id, estimate_id, recipient_email, recipient_name, token,
    document_hash, quote_snapshot, message, status, expires_at,
    sender_ip, sender_user_agent
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, estimate_id, recipient_email, recipient_name, token, document_hash, quote_snapshot, message, status, expires_at, sender_ip, sender_user_agent, created_at
`

type CreateSignatureRequestParams struct {
	ID              string         `json:"id"`
	EstimateID      string         `json:"estimate_id"`
	RecipientEmail  string         `json:"recipient_email"`
	RecipientName   string         `json:"recipient_name"`
	Token           string         `json:"token"`
	DocumentHash    string         `json:"document_hash"`
	QuoteSnapshot   string         `json:"quote_snapshot"`
	Message         sql.NullString `json:"message"`
	Status          string         `json:"status"`
	ExpiresAt       string         `json:"expires_at"`
	SenderIp        sql.NullString `json:"sender_ip"`
	SenderUserAgent sql.NullString `json:"sender_user_agent"`
}

// Signature Requests
func (q *Queries) CreateSignatureRequest(ctx context.Context, arg CreateSignatureRequestParams) (SignatureRequest, error) {
	row := q.db.QueryRowContext(ctx, createSignatureRequest,
		arg.ID,
		arg.EstimateID,
		arg.RecipientEmail,
		arg.RecipientName,
		arg.Token,
		arg.DocumentHash,
		arg.QuoteSnapshot,
		arg.Message,
		arg.Status,
		arg.ExpiresAt,
		arg.SenderIp,
		arg.SenderUserAgent,
	)
	var i SignatureRequest
	err := row.Scan(
		&i.ID,
		&i.EstimateID,
		&i.RecipientEmail,
		&i.RecipientName,
		&i.Token,
		&i.DocumentHash,
		&i.QuoteSnapshot,
		&i.Message,
		&i.Status,
		&i.ExpiresAt,
		&i.SenderIp,
		&i.SenderUserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const expireOldSignatureRequests = `-- name: ExpireOldSignatureRequests :exec
UPDATE signature_requests SET status = 'expired'
WHERE status = 'pending' AND expires_at < datetime('now')
`

func (q *Queries) ExpireOldSignatureRequests(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, expireOldSignatureRequests)
	return err
}

const getPendingSignatureRequestByEstimate = `-- name: GetPendingSignatureRequestByEstimate :one
SELECT id, estimate_id, recipient_email, recipient_name, token, document_hash, quote_snapshot, message, status, expires_at, sender_ip, sender_user_agent, created_at FROM signature_requests
WHERE estimate_id = ? AND status = 'pending'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPendingSignatureRequestByEstimate(ctx context.Context, estimateID string) (SignatureRequest, error) {
	row := q.db.QueryRowContext(ctx, getPendingSignatureRequestByEstimate, estimateID)
	var i SignatureRequest
	err := row.Scan(
		&i.ID,
		&i.EstimateID,
		&i.RecipientEmail,
		&i.RecipientName,
		&i.Token,
		&i.DocumentHash,
		&i.QuoteSnapshot,
		&i.Message,
		&i.Status,
		&i.ExpiresAt,
		&i.SenderIp,
		&i.SenderUserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getSignature = `-- name: GetSignature :one
SELECT id, request_id, legal_name, consent_text, document_hash, signed_at, signer_ip, signer_user_agent, signer_email, certificate_pdf_path, created_at FROM signatures WHERE id = ?
`

func (q *Queries) GetSignature(ctx context.Context, id string) (Signature, error) {
	row := q.db.QueryRowContext(ctx, getSignature, id)
	var i Signature
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.LegalName,
		&i.ConsentText,
		&i.DocumentHash,
		&i.SignedAt,
		&i.SignerIp,
		&i.SignerUserAgent,
		&i.SignerEmail,
		&i.CertificatePdfPath,
		&i.CreatedAt,
	)
	return i, err
}

const getSignatureByRequest = `-- name: GetSignatureByRequest :one
SELECT id, request_id, legal_name, consent_text, document_hash, signed_at, signer_ip, signer_user_agent, signer_email, certificate_pdf_path, created_at FROM signatures WHERE request_id = ?
`

func (q *Queries) GetSignatureByRequest(ctx context.Context, requestID string) (Signature, error) {
	row := q.db.QueryRowContext(ctx, getSignatureByRequest, requestID)
	var i Signature
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.LegalName,
		&i.ConsentText,
		&i.DocumentHash,
		&i.SignedAt,
		&i.SignerIp,
		&i.SignerUserAgent,
		&i.SignerEmail,
		&i.CertificatePdfPath,
		&i.CreatedAt,
	)
	return i, err
}

const getSignatureRequest = `-- name: GetSignatureRequest :one
SELECT id, estimate_id, recipient_email, recipient_name, token, document_hash, quote_snapshot, message, status, expires_at, sender_ip, sender_user_agent, created_at FROM signature_requests WHERE id = ?
`

func (q *Queries) GetSignatureRequest(ctx context.Context, id string) (SignatureRequest, error) {
	row := q.db.QueryRowContext(ctx, getSignatureRequest, id)
	var i SignatureRequest
	err := row.Scan(
		&i.ID,
		&i.EstimateID,
		&i.RecipientEmail,
		&i.RecipientName,
		&i.Token,
		&i.DocumentHash,
		&i.QuoteSnapshot,
		&i.Message,
		&i.Status,
		&i.ExpiresAt,
		&i.SenderIp,
		&i.SenderUserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getSignatureRequestByEstimate = `-- name: GetSignatureRequestByEstimate :one
SELECT id, estimate_id, recipient_email, recipient_name, token, document_hash, quote_snapshot, message, status, expires_at, sender_ip, sender_user_agent, created_at FROM signature_requests
WHERE estimate_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetSignatureRequestByEstimate(ctx context.Context, estimateID string) (SignatureRequest, error) {
	row := q.db.QueryRowContext(ctx, getSignatureRequestByEstimate, estimateID)
	var i SignatureRequest
	err := row.Scan(
		&i.ID,
		&i.EstimateID,
		&i.RecipientEmail,
		&i.RecipientName,
		&i.Token,
		&i.DocumentHash,
		&i.QuoteSnapshot,
		&i.Message,
		&i.Status,
		&i.ExpiresAt,
		&i.SenderIp,
		&i.SenderUserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getSignatureRequestByToken = `-- name: GetSignatureRequestByToken :one
SELECT id, estimate_id, recipient_email, recipient_name, token, document_hash, quote_snapshot, message, status, expires_at, sender_ip, sender_user_agent, created_at FROM signature_requests WHERE token = ?
`

func (q *Queries) GetSignatureRequestByToken(ctx context.Context, token string) (SignatureRequest, error) {
	row := q.db.QueryRowContext(ctx, getSignatureRequestByToken, token)
	var i SignatureRequest
	err := row.Scan(
		&i.ID,
		&i.EstimateID,
		&i.RecipientEmail,
		&i.RecipientName,
		&i.Token,
		&i.DocumentHash,
		&i.QuoteSnapshot,
		&i.Message,
		&i.Status,
		&i.ExpiresAt,
		&i.SenderIp,
		&i.SenderUserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const hasPendingSignatureRequest = `-- name: HasPendingSignatureRequest :one
SELECT EXISTS(
    SELECT 1 FROM signature_requests
    WHERE estimate_id = ? AND status = 'pending'
) as has_pending
`

// Check if estimate has any pending signature requests (for locking)
func (q *Queries) HasPendingSignatureRequest(ctx context.Context, estimateID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasPendingSignatureRequest, estimateID)
	var has_pending int64
	err := row.Scan(&has_pending)
	return has_pending, err
}

const hasSignedRequest = `-- name: HasSignedRequest :one
SELECT EXISTS(
    SELECT 1 FROM signature_requests sr
    INNER JOIN signatures s ON s.request_id = sr.id
    WHERE sr.estimate_id = ?
) as has_signed
`

// Check if estimate has been signed
func (q *Queries) HasSignedRequest(ctx context.Context, estimateID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasSignedRequest, estimateID)
	var has_signed int64
	err := row.Scan(&has_signed)
	return has_signed, err
}

const listSignatureRequestsByEstimate = `-- name: ListSignatureRequestsByEstimate :many
SELECT id, estimate_id, recipient_email, recipient_name, token, document_hash, quote_snapshot, message, status, expires_at, sender_ip, sender_user_agent, created_at FROM signature_requests
WHERE estimate_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListSignatureRequestsByEstimate(ctx context.Context, estimateID string) ([]SignatureRequest, error) {
	rows, err := q.db.QueryContext(ctx, listSignatureRequestsByEstimate, estimateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignatureRequest{}
	for rows.Next() {
		var i SignatureRequest
		if err := rows.Scan(
			&i.ID,
			&i.EstimateID,
			&i.RecipientEmail,
			&i.RecipientName,
			&i.Token,
			&i.DocumentHash,
			&i.QuoteSnapshot,
			&i.Message,
			&i.Status,
			&i.ExpiresAt,
			&i.SenderIp,
			&i.SenderUserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSignatureCertificatePath = `-- name: UpdateSignatureCertificatePath :one
UPDATE signatures SET certificate_pdf_path = ?
WHERE id = ?
RETURNING id, request_id, legal_name, consent_text, document_hash, signed_at, signer_ip, signer_user_agent, signer_email, certificate_pdf_path, created_at
`

type UpdateSignatureCertificatePathParams struct {
	CertificatePdfPath sql.NullString `json:"certificate_pdf_path"`
	ID                 string         `json:"id"`
}

func (q *Queries) UpdateSignatureCertificatePath(ctx context.Context, arg UpdateSignatureCertificatePathParams) (Signature, error) {
	row := q.db.QueryRowContext(ctx, updateSignatureCertificatePath, arg.CertificatePdfPath, arg.ID)
	var i Signature
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.LegalName,
		&i.ConsentText,
		&i.DocumentHash,
		&i.SignedAt,
		&i.SignerIp,
		&i.SignerUserAgent,
		&i.SignerEmail,
		&i.CertificatePdfPath,
		&i.CreatedAt,
	)
	return i, err
}

const updateSignatureRequestStatus = `-- name: UpdateSignatureRequestStatus :one
UPDATE signature_requests SET status = ?
WHERE id = ?
RETURNING id, estimate_id, recipient_email, recipient_name, token, document_hash, quote_snapshot, message, status, expires_at, sender_ip, sender_user_agent, created_at
`

type UpdateSignatureRequestStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateSignatureRequestStatus(ctx context.Context, arg UpdateSignatureRequestStatusParams) (SignatureRequest, error) {
	row := q.db.QueryRowContext(ctx, updateSignatureRequestStatus, arg.Status, arg.ID)
	var i SignatureRequest
	err := row.Scan(
		&i.ID,
		&i.EstimateID,
		&i.RecipientEmail,
		&i.RecipientName,
		&i.Token,
		&i.DocumentHash,
		&i.QuoteSnapshot,
		&i.Message,
		&i.Status,
		&i.ExpiresAt,
		&i.SenderIp,
		&i.SenderUserAgent,
		&i.CreatedAt,
	)
	return i, err
}
