// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subcontractors.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const clearSubcontractorTrades = `-- name: ClearSubcontractorTrades :exec
DELETE FROM subcontractor_trades WHERE subcontractor_id = $1
`

func (q *Queries) ClearSubcontractorTrades(ctx context.Context, subcontractorID string) error {
	_, err := q.db.ExecContext(ctx, clearSubcontractorTrades, subcontractorID)
	return err
}

const countFavoriteSubcontractors = `-- name: CountFavoriteSubcontractors :one
SELECT count(*) FROM subcontractors WHERE is_favorite = true
`

func (q *Queries) CountFavoriteSubcontractors(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFavoriteSubcontractors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubcontractors = `-- name: CountSubcontractors :one
SELECT count(*) FROM subcontractors
`

func (q *Queries) CountSubcontractors(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubcontractors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubcontractor = `-- name: CreateSubcontractor :one
INSERT INTO subcontractors (id, name, company, phone, email, address, notes, is_favorite)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, company, phone, email, address, notes, is_favorite, created_at, updated_at
`

type CreateSubcontractorParams struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Company    sql.NullString `json:"company"`
	Phone      sql.NullString `json:"phone"`
	Email      sql.NullString `json:"email"`
	Address    sql.NullString `json:"address"`
	Notes      sql.NullString `json:"notes"`
	IsFavorite bool           `json:"is_favorite"`
}

func (q *Queries) CreateSubcontractor(ctx context.Context, arg CreateSubcontractorParams) (Subcontractor, error) {
	row := q.db.QueryRowContext(ctx, createSubcontractor,
		arg.ID,
		arg.Name,
		arg.Company,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.Notes,
		arg.IsFavorite,
	)
	var i Subcontractor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Notes,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubcontractor = `-- name: DeleteSubcontractor :exec
DELETE FROM subcontractors WHERE id = $1
`

func (q *Queries) DeleteSubcontractor(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSubcontractor, id)
	return err
}

const getSubcontractor = `-- name: GetSubcontractor :one
SELECT id, name, company, phone, email, address, notes, is_favorite, created_at, updated_at FROM subcontractors WHERE id = $1
`

func (q *Queries) GetSubcontractor(ctx context.Context, id string) (Subcontractor, error) {
	row := q.db.QueryRowContext(ctx, getSubcontractor, id)
	var i Subcontractor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Notes,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubcontractorTrades = `-- name: GetSubcontractorTrades :many
SELECT t.id, t.name, t.sort_order, st.position
FROM trades t
JOIN subcontractor_trades st ON st.trade_id = t.id
WHERE st.subcontractor_id = $1
ORDER BY st.position ASC
`

type GetSubcontractorTradesRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
	Position  int64  `json:"position"`
}

func (q *Queries) GetSubcontractorTrades(ctx context.Context, subcontractorID string) ([]GetSubcontractorTradesRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubcontractorTrades, subcontractorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSubcontractorTradesRow{}
	for rows.Next() {
		var i GetSubcontractorTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubcontractors = `-- name: ListSubcontractors :many
SELECT
    s.id, s.name, s.company, s.phone, s.email, s.address, s.notes, s.is_favorite, s.created_at, s.updated_at,
    t.name AS primary_trade
FROM subcontractors s
LEFT JOIN subcontractor_trades st ON st.subcontractor_id = s.id AND st.position = 0
LEFT JOIN trades t ON t.id = st.trade_id
ORDER BY s.is_favorite DESC, s.name ASC
`

type ListSubcontractorsRow struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Company      sql.NullString `json:"company"`
	Phone        sql.NullString `json:"phone"`
	Email        sql.NullString `json:"email"`
	Address      sql.NullString `json:"address"`
	Notes        sql.NullString `json:"notes"`
	IsFavorite   bool           `json:"is_favorite"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	PrimaryTrade sql.NullString `json:"primary_trade"`
}

func (q *Queries) ListSubcontractors(ctx context.Context) ([]ListSubcontractorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubcontractors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubcontractorsRow{}
	for rows.Next() {
		var i ListSubcontractorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Company,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.Notes,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryTrade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubcontractorsByTrade = `-- name: ListSubcontractorsByTrade :many
SELECT
    s.id, s.name, s.company, s.phone, s.email, s.address, s.notes, s.is_favorite, s.created_at, s.updated_at,
    t.name AS primary_trade
FROM subcontractors s
JOIN subcontractor_trades st ON st.subcontractor_id = s.id AND st.position = 0
JOIN trades t ON t.id = st.trade_id
WHERE t.id = $1
ORDER BY s.is_favorite DESC, s.name ASC
`

type ListSubcontractorsByTradeRow struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Company      sql.NullString `json:"company"`
	Phone        sql.NullString `json:"phone"`
	Email        sql.NullString `json:"email"`
	Address      sql.NullString `json:"address"`
	Notes        sql.NullString `json:"notes"`
	IsFavorite   bool           `json:"is_favorite"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	PrimaryTrade string         `json:"primary_trade"`
}

func (q *Queries) ListSubcontractorsByTrade(ctx context.Context, id string) ([]ListSubcontractorsByTradeRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubcontractorsByTrade, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubcontractorsByTradeRow{}
	for rows.Next() {
		var i ListSubcontractorsByTradeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Company,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.Notes,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryTrade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrades = `-- name: ListTrades :many
SELECT id, name, sort_order FROM trades ORDER BY sort_order, name
`

func (q *Queries) ListTrades(ctx context.Context) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, listTrades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trade{}
	for rows.Next() {
		var i Trade
		if err := rows.Scan(&i.ID, &i.Name, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSubcontractors = `-- name: SearchSubcontractors :many
SELECT
    s.id, s.name, s.company, s.phone, s.email, s.address, s.notes, s.is_favorite, s.created_at, s.updated_at,
    t.name AS primary_trade
FROM subcontractors s
LEFT JOIN subcontractor_trades st ON st.subcontractor_id = s.id AND st.position = 0
LEFT JOIN trades t ON t.id = st.trade_id
WHERE s.name ILIKE '%' || $1::text || '%'
   OR s.company ILIKE '%' || $1::text || '%'
ORDER BY s.is_favorite DESC, s.name ASC
`

type SearchSubcontractorsRow struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Company      sql.NullString `json:"company"`
	Phone        sql.NullString `json:"phone"`
	Email        sql.NullString `json:"email"`
	Address      sql.NullString `json:"address"`
	Notes        sql.NullString `json:"notes"`
	IsFavorite   bool           `json:"is_favorite"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	PrimaryTrade sql.NullString `json:"primary_trade"`
}

func (q *Queries) SearchSubcontractors(ctx context.Context, searchTerm string) ([]SearchSubcontractorsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchSubcontractors, searchTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSubcontractorsRow{}
	for rows.Next() {
		var i SearchSubcontractorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Company,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.Notes,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryTrade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSubcontractorTrade = `-- name: SetSubcontractorTrade :exec
INSERT INTO subcontractor_trades (subcontractor_id, trade_id, position)
VALUES ($1, $2, $3)
`

type SetSubcontractorTradeParams struct {
	SubcontractorID string `json:"subcontractor_id"`
	TradeID         string `json:"trade_id"`
	Position        int64  `json:"position"`
}

func (q *Queries) SetSubcontractorTrade(ctx context.Context, arg SetSubcontractorTradeParams) error {
	_, err := q.db.ExecContext(ctx, setSubcontractorTrade, arg.SubcontractorID, arg.TradeID, arg.Position)
	return err
}

const toggleFavorite = `-- name: ToggleFavorite :one
UPDATE subcontractors
SET is_favorite = NOT is_favorite,
    updated_at = now()
WHERE id = $1
RETURNING id, name, company, phone, email, address, notes, is_favorite, created_at, updated_at
`

func (q *Queries) ToggleFavorite(ctx context.Context, id string) (Subcontractor, error) {
	row := q.db.QueryRowContext(ctx, toggleFavorite, id)
	var i Subcontractor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Notes,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubcontractor = `-- name: UpdateSubcontractor :one
UPDATE subcontractors
SET name = $2, company = $3, phone = $4, email = $5, address = $6, notes = $7,
    is_favorite = $8, updated_at = now()
WHERE id = $1
RETURNING id, name, company, phone, email, address, notes, is_favorite, created_at, updated_at
`

type UpdateSubcontractorParams struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Company    sql.NullString `json:"company"`
	Phone      sql.NullString `json:"phone"`
	Email      sql.NullString `json:"email"`
	Address    sql.NullString `json:"address"`
	Notes      sql.NullString `json:"notes"`
	IsFavorite bool           `json:"is_favorite"`
}

func (q *Queries) UpdateSubcontractor(ctx context.Context, arg UpdateSubcontractorParams) (Subcontractor, error) {
	row := q.db.QueryRowContext(ctx, updateSubcontractor,
		arg.ID,
		arg.Name,
		arg.Company,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.Notes,
		arg.IsFavorite,
	)
	var i Subcontractor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Notes,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
