// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppliers.sql

package repository

import (
	"context"
)

const countMaterialsBySupplier = `-- name: CountMaterialsBySupplier :one
SELECT COUNT(*) AS total FROM materials WHERE supplier_id = $1
`

func (q *Queries) CountMaterialsBySupplier(ctx context.Context, supplierID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMaterialsBySupplier, supplierID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (id, name, sort_order)
VALUES ($1, $2, $3)
RETURNING id, name, sort_order, created_at
`

type CreateSupplierParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, createSupplier, arg.ID, arg.Name, arg.SortOrder)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSupplier = `-- name: DeleteSupplier :exec
DELETE FROM suppliers WHERE id = $1
`

func (q *Queries) DeleteSupplier(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSupplier, id)
	return err
}

const getSupplier = `-- name: GetSupplier :one
SELECT id, name, sort_order, created_at FROM suppliers WHERE id = $1
`

func (q *Queries) GetSupplier(ctx context.Context, id string) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, getSupplier, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, name, sort_order, created_at FROM suppliers ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListSuppliers(ctx context.Context) ([]Supplier, error) {
	rows, err := q.db.QueryContext(ctx, listSuppliers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
