// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package repository

import (
	"context"
	"database/sql"
)

const countTemplateSections = `-- name: CountTemplateSections :one
SELECT COUNT(*) FROM template_sections WHERE template_id = $1
`

func (q *Queries) CountTemplateSections(ctx context.Context, templateID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTemplateSections, templateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (id, name, description)
VALUES ($1, $2, $3)
RETURNING id, name, description, created_at, updated_at
`

type CreateTemplateParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, createTemplate, arg.ID, arg.Name, arg.Description)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplateComponentGroup = `-- name: CreateTemplateComponentGroup :one
INSERT INTO template_component_groups (id, template_subcategory_id, name, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, template_subcategory_id, name, sort_order
`

type CreateTemplateComponentGroupParams struct {
	ID                    string `json:"id"`
	TemplateSubcategoryID string `json:"template_subcategory_id"`
	Name                  string `json:"name"`
	SortOrder             int64  `json:"sort_order"`
}

func (q *Queries) CreateTemplateComponentGroup(ctx context.Context, arg CreateTemplateComponentGroupParams) (TemplateComponentGroup, error) {
	row := q.db.QueryRowContext(ctx, createTemplateComponentGroup,
		arg.ID,
		arg.TemplateSubcategoryID,
		arg.Name,
		arg.SortOrder,
	)
	var i TemplateComponentGroup
	err := row.Scan(
		&i.ID,
		&i.TemplateSubcategoryID,
		&i.Name,
		&i.SortOrder,
	)
	return i, err
}

const createTemplateSection = `-- name: CreateTemplateSection :one
INSERT INTO template_sections (id, template_id, name, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, template_id, name, sort_order
`

type CreateTemplateSectionParams struct {
	ID         string `json:"id"`
	TemplateID string `json:"template_id"`
	Name       string `json:"name"`
	SortOrder  int64  `json:"sort_order"`
}

func (q *Queries) CreateTemplateSection(ctx context.Context, arg CreateTemplateSectionParams) (TemplateSection, error) {
	row := q.db.QueryRowContext(ctx, createTemplateSection,
		arg.ID,
		arg.TemplateID,
		arg.Name,
		arg.SortOrder,
	)
	var i TemplateSection
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.SortOrder,
	)
	return i, err
}

const createTemplateSubcategory = `-- name: CreateTemplateSubcategory :one
INSERT INTO template_subcategories (id, template_section_id, name, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, template_section_id, name, sort_order
`

type CreateTemplateSubcategoryParams struct {
	ID                string `json:"id"`
	TemplateSectionID string `json:"template_section_id"`
	Name              string `json:"name"`
	SortOrder         int64  `json:"sort_order"`
}

func (q *Queries) CreateTemplateSubcategory(ctx context.Context, arg CreateTemplateSubcategoryParams) (TemplateSubcategory, error) {
	row := q.db.QueryRowContext(ctx, createTemplateSubcategory,
		arg.ID,
		arg.TemplateSectionID,
		arg.Name,
		arg.SortOrder,
	)
	var i TemplateSubcategory
	err := row.Scan(
		&i.ID,
		&i.TemplateSectionID,
		&i.Name,
		&i.SortOrder,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplate, id)
	return err
}

const deleteTemplateComponentGroup = `-- name: DeleteTemplateComponentGroup :exec
DELETE FROM template_component_groups WHERE id = $1
`

func (q *Queries) DeleteTemplateComponentGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateComponentGroup, id)
	return err
}

const deleteTemplateSection = `-- name: DeleteTemplateSection :exec
DELETE FROM template_sections WHERE id = $1
`

func (q *Queries) DeleteTemplateSection(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateSection, id)
	return err
}

const deleteTemplateSubcategory = `-- name: DeleteTemplateSubcategory :exec
DELETE FROM template_subcategories WHERE id = $1
`

func (q *Queries) DeleteTemplateSubcategory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateSubcategory, id)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, name, description, created_at, updated_at FROM templates WHERE id = $1
`

func (q *Queries) GetTemplate(ctx context.Context, id string) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplateComponentGroups = `-- name: ListTemplateComponentGroups :many

SELECT id, template_subcategory_id, name, sort_order FROM template_component_groups
WHERE template_subcategory_id = $1
ORDER BY sort_order ASC
`

// Template Component Groups
func (q *Queries) ListTemplateComponentGroups(ctx context.Context, templateSubcategoryID string) ([]TemplateComponentGroup, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateComponentGroups, templateSubcategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateComponentGroup{}
	for rows.Next() {
		var i TemplateComponentGroup
		if err := rows.Scan(
			&i.ID,
			&i.TemplateSubcategoryID,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateSections = `-- name: ListTemplateSections :many

SELECT id, template_id, name, sort_order FROM template_sections
WHERE template_id = $1
ORDER BY sort_order ASC
`

// Template Sections
func (q *Queries) ListTemplateSections(ctx context.Context, templateID string) ([]TemplateSection, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateSections, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateSection{}
	for rows.Next() {
		var i TemplateSection
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateSubcategories = `-- name: ListTemplateSubcategories :many

SELECT id, template_section_id, name, sort_order FROM template_subcategories
WHERE template_section_id = $1
ORDER BY sort_order ASC
`

// Template Subcategories
func (q *Queries) ListTemplateSubcategories(ctx context.Context, templateSectionID string) ([]TemplateSubcategory, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateSubcategories, templateSectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateSubcategory{}
	for rows.Next() {
		var i TemplateSubcategory
		if err := rows.Scan(
			&i.ID,
			&i.TemplateSectionID,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many

SELECT id, name, description, created_at, updated_at FROM templates ORDER BY name ASC
`

// Templates
func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, updateTemplate, arg.ID, arg.Name, arg.Description)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTemplateComponentGroup = `-- name: UpdateTemplateComponentGroup :one
UPDATE template_component_groups
SET name = $2, sort_order = $3
WHERE id = $1
RETURNING id, template_subcategory_id, name, sort_order
`

type UpdateTemplateComponentGroupParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) UpdateTemplateComponentGroup(ctx context.Context, arg UpdateTemplateComponentGroupParams) (TemplateComponentGroup, error) {
	row := q.db.QueryRowContext(ctx, updateTemplateComponentGroup, arg.ID, arg.Name, arg.SortOrder)
	var i TemplateComponentGroup
	err := row.Scan(
		&i.ID,
		&i.TemplateSubcategoryID,
		&i.Name,
		&i.SortOrder,
	)
	return i, err
}

const updateTemplateSection = `-- name: UpdateTemplateSection :one
UPDATE template_sections
SET name = $2, sort_order = $3
WHERE id = $1
RETURNING id, template_id, name, sort_order
`

type UpdateTemplateSectionParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) UpdateTemplateSection(ctx context.Context, arg UpdateTemplateSectionParams) (TemplateSection, error) {
	row := q.db.QueryRowContext(ctx, updateTemplateSection, arg.ID, arg.Name, arg.SortOrder)
	var i TemplateSection
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.SortOrder,
	)
	return i, err
}

const updateTemplateSubcategory = `-- name: UpdateTemplateSubcategory :one
UPDATE template_subcategories
SET name = $2, sort_order = $3
WHERE id = $1
RETURNING id, template_section_id, name, sort_order
`

type UpdateTemplateSubcategoryParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) UpdateTemplateSubcategory(ctx context.Context, arg UpdateTemplateSubcategoryParams) (TemplateSubcategory, error) {
	row := q.db.QueryRowContext(ctx, updateTemplateSubcategory, arg.ID, arg.Name, arg.SortOrder)
	var i TemplateSubcategory
	err := row.Scan(
		&i.ID,
		&i.TemplateSectionID,
		&i.Name,
		&i.SortOrder,
	)
	return i, err
}
